### ISSUE TITLE
rfk_resstrings vs rfk_module in msei18n

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#10]
About use of rfk_resstrings vs rfk_module for files to be translated.

Indeed there are more rows with `rfk_module` but, after check, all that rows must be set as NT (not translate) so maybe `rfk_resstrings` mode is enough if only translation is needed.

But maybe I am wrong.

**Comment by fredvs** [comment]
After deeper test it appear that using rfk_resstrings in the mseide project gives more words to translate than with rfk_module.

@glixx you may try with your russian mseide file.

**Comment by fredvs** [comment]
Indeed with `rfk_module` there are much more strings to translate and this should be used.

OK, the msei18n bug become more targeted.

**Comment by glixx** [comment]
For mselang:
rfk_module shows 70 translatable strings, rfk_resstrings shows 16 translatable strings.

**Comment by fredvs** [comment]
Yes, I have see that.
Aaargh, the no NT bug is strong, mostly because on some project it does not appear and on other yes.
And the debugger do not give useful infos.
;(
