### ISSUE TITLE
Application icon corrupted

### ISSUE THREAD

**Issue by circular17** [mse-org/mseide-msegui#10]
Apparently due to ASCII conversion. Here are the original files:
msegui_24.png
![msegui_24](https://user-images.githubusercontent.com/9092455/79681019-55e23180-8216-11ea-9cf5-4acd9193aa88.png)
msegui_32.png
![msegui_32](https://user-images.githubusercontent.com/9092455/79681020-567ac800-8216-11ea-887d-ace16931797f.png)
msegui_48.png
![msegui_48](https://user-images.githubusercontent.com/9092455/79681021-57135e80-8216-11ea-8531-fa6539ae648d.png)
msegui_64.png
![msegui_64](https://user-images.githubusercontent.com/9092455/79681022-57135e80-8216-11ea-9349-dbf2c1a857bc.png)

**Comment by circular17** [comment]
Une petite requête de fusion: 
https://github.com/mse-org/mseide-msegui/pull/12

**Comment by fredvs** [comment]
Fusion faite.

**Comment by circular17** [comment]
Merci

**Comment by fredvs** [comment]
Merci à toi. Huh, je peux Closer l'issue?

**Comment by circular17** [comment]
Voui
