### ISSUE TITLE
Localization constants by gettext

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#11]
Right now constants were localized by pas files, but need to go by PO way. So needs to include all constants into mfm file. In this way they will be localized by MO or library.

**Comment by glixx** [comment]
And to write converter from PO into pas to save old implementation.

**Comment by glixx** [comment]
POT file generation:
xgettext -L Lua -a mseconsts.pas -o mseconsts.pot
and delete not needed strings.

Problem is how to read translations from mseconsts_*.pas in native language. Do you know how to convert strings in human language?

**Comment by fredvs** [comment]
Did you test to add mseconst.pas and mseconsts_mfm.pas into list of fies in project?
Maybe msei18n does the job?

**Comment by glixx** [comment]
This file mseconsts_mfm.pas is missing.
mseconst.pas is not readable by msei18n.

**Comment by fredvs** [comment]
> This file mseconsts_mfm.pas is missing.
> mseconst.pas is not readable by msei18n.

Then better to use strings container.

**Comment by fredvs** [comment]
And sing the already translated mseconst_xx.pas ?

They are in` `/mseide-msegui/lib/common/kernel/mseconsts_xx.pas``

You should have one for `Russian` too.

I did it for french long time ago.

**Comment by fredvs** [comment]
Ha, but there is one `ru`, so what the problem?

**Comment by fredvs** [comment]
I see the problem.
Very complicated.

**Comment by glixx** [comment]
To create PO files I need string "Конфигурировать MSEi18n" instead of string
"#1050#1086#1085#1092#1080#1075#1091#1088#1080#1088#1086#1074#1072#1090#1100#32#77#83#69#105#49#56#110"

**Comment by glixx** [comment]
This is converter from human language into encoded language:
```
#/bin/bash
rm -f 1 2 3
# convert string into HEX (after recode into dump to delete the latest number and two the first numbers)
echo Конфигурировать MSEi18n| recode UTF8..dump|awk '{print $1}' |sed '$d'|sed '1,2d' > 1
for str in `cat 1`
do
  # convert number from HEX into DEC
  echo "obase=10;ibase=16;$str" | bc >> 2
done
# add # in the start of number
sed -i "s|^|#|g" 2
# delete all EOL
cat 2|tr -d '\n' > 3
# file 3 is result
cat 3;echo
# cleanup
rm -f 1 2 3
```
But  I need to recode back.

**Comment by fredvs** [comment]
> To create PO files I need string "Конфигурировать MSEi18n" instead of string
> "#1050#1086#1085#1092#1080#1075#1091#1088#1080#1088#1086#1074#1072#1090#1100#32#77#83#69#105#49#56#110"

Ok, understand.


> This is converter from human language into encoded language

https://stackoverflow.com/questions/49310401/convert-hexadecimal-to-human-readable-string-with-delphi

https://stackoverflow.com/questions/47947794/delphi-tokyo-function-string-to-hex-and-hex-to-string

**Comment by glixx** [comment]
Solution: https://www.branah.com/unicode-converter

**Comment by glixx** [comment]
PO files with constants are available for translation. While constants are moving into mfm translators can translate them already.

**Comment by glixx** [comment]
@fredvs just convert mseconsts.pas into mfm and drop pas files. Translations are already in translation memory of transifex, so they can be moved in any POT file to stay translated.
I guess they will be in mseide.pot.

**Comment by fredvs** [comment]
> @fredvs just convert mseconsts.pas into mfm and drop pas files. T

Not sure to understand, only change the extension mseconsts.pas --> mseconsts.mfm?

**Comment by fredvs** [comment]
No, sorry I do not understand, it does not work when changing mseconsts.mfm,  msei18n does not recognize it.

**Comment by fredvs** [comment]
Even transforming mseconsts.pas in a datamodule does not work.
The mseconsts.mfm produced does not have data of the const.
For this const must be in a sting-container.

No, sorry, I o not catch something.

**Comment by glixx** [comment]
Yes. String containers. In this case they will be available in mfm file.
But after thinking they must stay in mseconsts.pot file. All applications use them. Same with fpgui. To localize uidesigner needs 2 po files from fpgui and uidesigner.
It means needs to support loading of 2 libraries.

**Comment by fredvs** [comment]
But then you must have the library language.

I like the way t is now, `mseconst_xx`.pas and have a individual for unit for each language.

But here to do the conversion from `mseconst_en` to a other language, `mseconsts_xy` for example, a other tool than msei18n is needed.

Can `Gettext` do that job?

**Comment by fredvs** [comment]
> Yes. String containers. In this case they will be available in mfm file.

Sorry but I do not ave the scale for this, I did try to understand `mseconst.pas` code but without success.
I apologize.

**Comment by glixx** [comment]
Ok, let's keep current way to work with constants.

We have POT file generation from mseconsts.pas:

`xgettext -L Lua -a mseconsts.pas -o mseconsts.pot`

We need converter from po files into mseconsts_*.pas.
mseconsts.pas is template.

This job can be done by msei18n in console mode (do not need gui).
`msei18n --constants`
or by new tool.

**Comment by fredvs** [comment]
> Ok, let's keep current way to work with constants.
> 
> We have POT file generation from mseconsts.pas:
> 
> `xgettext -L Lua -a mseconsts.pas -o mseconsts.pot`
> 
> We need converter from po files into mseconsts_*.pas.
> mseconsts.pas is template.
> 
> This job can be done by msei18n in console mode (do not need gui).
> `msei18n --constants`
> or by new tool.

Dont you think it would be easier to create a default `mseconsts_en.pas` that takes the data from `mseconsts.pas` and convert `mseconsts_en.pas` into `mseconsts_xy.pas` ?

Because code of `mseconsts.pas` is very different of `mseconsts_xx.pas`

**Comment by glixx** [comment]
> Dont you think it would be easier to create a default mseconsts_en.pas that takes the data from mseconsts.pas and convert mseconsts_en.pas into mseconsts_xy.pas ?

Yes. And move function delete_n_selected_rows (https://github.com/mse-org/mseide-msegui/blob/master/lib/common/kernel/mseconsts_fr.pas)

Move into constants:
'Effacer le fichier s'#0233'lectionn'#0233' ?'
'Delete selected row?'

We cannot support by gettext:
'Effacer les '+inttostrmse(vinteger)+' fichiers s'#0233'lectionn'#0233's ?';
'Delete '+inttostrmse(vinteger)+' selected rows?'

Move this string into constants and write it language independent:
'Delete selected rows? Rows:'
by 2 constants:
'Delete selected rows?'
'Rows'
and concatenate them:
'Delete selected rows?' + ' ' + 'Rows' + ':'

**Comment by fredvs** [comment]
Ok, I will try.

Other thing, when you are talking about 

> Po, All applications use them

Are you talking about using po files live, at loading or about using po files for compilation?

**Comment by glixx** [comment]
> Are you talking about using po files live, at loading or about using po files for compilation?

About constants. Never mind.

**Comment by fredvs** [comment]
OK for all, using const for all words, but for this one:

> And move function delete_n_selected_rows

Where to move it?
In mseconst.pas?
But then how to assign the translated values?

**Comment by fredvs** [comment]
> Where to move it?
> In mseconst.pas?

Cannot, there is already `delete_n_selected_rows` in `mseconst.pas`.
Maybe I misunderstand something.

**Comment by glixx** [comment]
> Where to move it? In mseconst.pas?

Yes.

> But then how to assign the translated values?

Same with other translated values. Martin moved this function into `mseconsts_*.pas`. He wanted to have translations for string with `%s`:
'Delete %s selected rows?'

It possible by gettext. We can have constant 'Delete %s selected rows?',
but before using it to change `%s` on `inttostrmse(vinteger)`

**Comment by fredvs** [comment]
In `mseconst_fr.`pas it uses as name for consts  `fr_modalresulttext`, `fr_modalresulttextnoshortcut`, `fr_stockcaption`.

I do not understand why the `fr_` is needed.
I did try with `modalresulttext` and others, and this with different language and all are working ok.

Maybe cut the `fr_`  for name of const, this to make conversion more easy?
Or do you see a inconvenient?

**Comment by fredvs** [comment]
> Where to move it? In mseconst.pas?
> Yes.

I do not know how to do.

**Comment by fredvs** [comment]
> Where to move it? In mseconst.pas?

There is already that function.

**Comment by glixx** [comment]
> There is already that function.

Yes. Delete all functions from `mseconst_*.pas`.
And 2 ways:
* use language independend strings
* use %s

**Comment by fredvs** [comment]
> Yes. Delete all functions from mseconst_*.pas.

`mseconsts_fr.pas(274,36) Error: Identifier not found "delete_n_selected_rows"`

Line 274:
```
const
 textgenerator: defaultgeneratortextty = (
              {$ifdef FPC}@{$endif}delete_n_selected_rows //tg_delete_n_selected_rows
```

**Comment by glixx** [comment]
Delete fr_textgenerator

**Comment by fredvs** [comment]
> Delete fr_textgenerator

`mseconsts_fr.pas(279,60) Error: Identifier not found "textgenerator"`

line 279:

```
initialization
 registerlangconsts(langnames[la_fr],@stockcaption,@modalresulttext,
                               @modalresulttextnoshortcut,@textgenerator);
```

Do you want ?

```
initialization
 registerlangconsts(langnames[la_fr],@stockcaption,@modalresulttext,
                               @modalresulttextnoshortcut,nil);
```

**Comment by glixx** [comment]
```
function delete_n_selected_rows(const params: array of const): msestring;
begin
 with params[0] do begin
  if vinteger = 1 then begin
   result:= 'Effacer le fichier s'#0233'lectionn'#0233' ?'
  end
  else begin
   result:= 'Effacer les '+inttostrmse(vinteger)+
            ' fichiers s'#0233'lectionn'#0233's ?';
  end;
 end;
end;

const
 fr_textgenerator: defaultgeneratortextty = (
              {$ifdef FPC}@{$endif}delete_n_selected_rows //tg_delete_n_selected_rows
                                     );
initialization
 registerlangconsts(langnames[la_fr],@fr_stockcaption,@fr_modalresulttext,
                               @fr_modalresulttextnoshortcut,@fr_textgenerator);
end.
```
->
```
initialization
 registerlangconsts(langnames[la_fr],@fr_stockcaption,@fr_modalresulttext,
                               @fr_modalresulttextnoshortcut
end.
```

**Comment by fredvs** [comment]
```
initialization
 registerlangconsts(langnames[la_fr],@stockcaption,@modalresulttext,
                               @modalresulttextnoshortcut);
```
...

```
mseconsts_fr.pas(278,2) Error: Wrong number of parameters specified for call to "registerlangconsts"
mseconsts.pas(312,11) Error: Found declaration: registerlangconsts(const AnsiString;const pstockcaptionaty;const pdefaultmodalresulttextty;const pdefaultmodalresulttextty;const pdefaultgeneratortextty);
mseconsts_fr.pas(281) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
```

**Comment by fredvs** [comment]
Or like say in previous post, you want?:

```
initialization
 registerlangconsts(langnames[la_fr],@stockcaption,@modalresulttext,
                               @modalresulttextnoshortcut, nil);
```

**Comment by glixx** [comment]
nil or:
```

const
 fr_textgenerator: defaultmodalresulttextty =
 ( Effacer le fichier s'#0233'lectionn'#0233' ?,
  'Effacer les %s fichiers s'#0233'lectionn'#0233's ?'
);
```

**Comment by fredvs** [comment]
> nil or:
> 
> ```
> 
> const
>  fr_textgenerator: defaultmodalresulttextty =
>  ( 'Effacer le fichier s'#0233'lectionn'#0233' ?', //tg_delete_n_selected_rows
>   'Effacer les %s fichiers s'#0233'lectionn'#0233's ?' //tg_delete_n_selected_rows_plural
> );
> ```

```
mseconsts_fr.pas(279,4) Error: Incompatible types: got "UnicodeString" expected "<procedure variable type of function(const Array Of Const):UnicodeString;Register>"
mseconsts_fr.pas(279,50) Fatal: Syntax error, ")" expected but "," found
Fatal: Compilation aborted

```

In that case, code must be changed in `mseconsts.pas`:


 ----> `defaultgeneratortextty = array[textgeneratorty] of textgeneratorfuncty;`

into

 ----> `defaultgeneratortextty = array[textgeneratorty] of msestring;`

And so no more difference for plural.

And use a unique const:

`Delete the file(s) ?`

`Effacer le(s) fichier(s) ?`  

I am a little afraid about nil.

**Comment by glixx** [comment]
Other way:
```
 ( 'Effacer le fichier s'#0233'lectionn'#0233' ?', //tg_delete_selected_row
  'Effacer les %s fichiers s'#0233'lectionn'#0233's ?' //tg_delete_n_selected_rows
);

```
```
function delete_n_selected_rows(const params: array of const): msestring;
var str0: msestring;
begin
 str0:=tg_delete_n_selected_rows
 with params[0] do begin
  if vinteger = 1 then begin
   ... changing str0: changing %s on inttostrmse(vinteger) ...
   result:= tg_delete_selected_row
  end
  else begin
   result:= str0
  end;
 end;
end;
```

**Comment by fredvs** [comment]
I will study this tomorrow because it is not out of the box and mse code is complicated.

**Comment by glixx** [comment]
This way is good https://github.com/mse-org/mseide-msegui/issues/11#issuecomment-479729178
We need mseconst_en.pas template. So we can keep this function, just to change it a little.

**Comment by fredvs** [comment]
> function delete_n_selected_rows(const params: array of const): msestring;
> var str0: msestring;
> begin
>  str0:=tg_delete_n_selected_rows
>  with params[0] do begin
>   if vinteger = 1 then begin
>    result:= tg_delete_selected_row
>   end
>   else begin
>      // changing str0: changing %s on inttostrmse(vinteger)
>    str0 := StringReplace(str0,  '%s', inttostrmse(vinteger), [rfReplaceAll]);
>      // or
>    str0 := StringReplace(str0,  '#37''s', inttostrmse(vinteger), [rfReplaceAll]);
>    result:= str0
>   end;
>  end;
> end;

`mseconsts_fr.pas(279,8) Error: Identifier not found "tg_delete_n_selected_rows"`

**Comment by fredvs** [comment]
I did understand why function `delete_n_selected_rows` is part of each unit language.
It is about the syntax of language, it differs by language.

Anyway, here is the default `mseconsts_en`, I did commit for `ru`, `es`, `de` and `fr`:
Is it ok for you?

```
unit mseconsts_en;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}
interface
uses
 mseconsts;
 
implementation
uses
 msetypes{msestrings},sysutils,mseformatstr;
 
const 
extendedconst: extendedaty =
 ('en',  // ex_lang
  'Delete selected row?',   // ex_delfileselected
  'Delete',                 // ex_deletefiles
  'selected rows?'          //ex_selected
  ); 

 modalresulttext: defaultmodalresulttextty =
 ('',          //mr_none
  '',          //mr_canclose
  '',          //mr_windowclosed
  '',          //mr_windowdestroyed
  '',          //mr_escape
  '',          //mr_f10
  '',          //mr_exception
  '&Cancel',   //mr_cancel
  '&Abort',    //mr_abort
  '&OK',       //mr_ok
  '&Yes',      //mr_yes
  '&No',       //mr_no
  '&All',      //mr_all
  'Yes &all',  //mr_yesall
  'N&o all',   //mr_noall
  '&Ignore',   //mr_ignore
  '&Skip',     //mr_skip
  'Skip a&ll', //mr_skipall
  'Co&ntinue'  //mr_continue
  );

 modalresulttextnoshortcut: defaultmodalresulttextty =
 ('',         //mr_none
  '',         //mr_canclose
  '',         //mr_windowclosed
  '',         //mr_windowdestroyed
  '',         //mr_esc
  '',         //mr_f10
  '',         //mr_exception
  'Cancel',   //mr_cancel
  'Abort',    //mr_abort
  'OK',       //mr_ok
  'Yes',      //mr_yes
  'No',       //mr_no
  'All',      //mr_all
  'Yes all',  //mr_yesall
  'No all',   //mr_noall
  'Ignore',   //mr_ignore
  'Skip',     //mr_skip
  'Skip all', //mr_skipall
  'Continue'  //mr_continue
  );

 stockcaption: stockcaptionaty = (
  '',                   //sc_none
  'is invalid',         //sc_is_invalid
  'Format error',       //sc_Format_error
  'Value is required',  //sc_Value_is_required
  'Error',              //sc_Error
  'Min',                //sc_Min
  'Max',                //sc_Max
  'Range error',        //sc_Range_error  

  '&Undo',              //sc_Undohk       ///         ///
  '&Redo',              //sc_Redohk        //          //
  '&Copy',              //sc_Copyhk        // hotkeys  //
  'Cu&t',               //sc_Cuthk         //          //
  '&Paste',             //sc_Pastehk       //          // hotkeys
  'Select &all',        //sc_Select_allhk ///          //
  '&Insert Row',        //sc_insert_rowhk ///          //
  '&Append Row',        //sc_append_rowhk  // hotkeys  //
  '&Delete Row',        //sc_delete_rowhk ///         ///

  '&Dir',               //sc_Dirhk               /// 
  '&Home',              //sc_homehk               //
  '&Up',                //sc_Uphk                 //
  '&New dir',           //sc_New_dirhk            // hotkeys
  '&Name',              //sc_Namehk               //
  '&Show hidden files', //sc_Show_hidden_fileshk  //
  '&Filter',            //sc_Filterhk            /// 
  'Save',               //sc_save 
  'Open',               //sc_open
  'Name',                //sc_name
  'Create new directory',//sc_create_new_directory
  'Back',                //sc_back
  'Forward',             //sc_forward
  'Up',                  //sc_up
  'File',                //sc_file
  'exists, do you want to overwrite?', //sc_exists_overwrite
  'is modified. Save?',  //sc_is_modified_save
  'WARNING',               //sc_warningupper
  'ERROR',                 //sc_errorupper
  'Exception',             //sc_exception
  'System',                //sc_system
  'does not exist',        //sc_does_not_exist
  'PASSWORD',              //sc_passwordupper
  'Enter password',        //sc_enterpassword
  'Invalid password!',     //sc_invalidpassword
  'Can not read directory', //sc_can_not_read_directory
  'Graphic format not supported', //sc_graphic_not_supported
  'Graphic format error', //sc_graphic_format_error
  'MS Bitmap',          //sc_MS_Bitmap
  'MS Icon',            //sc_MS_Icon
  'JPEG Image',         //sc_JPEG_Image 
  'PNG Image',          //sc_PNG_Image
  'XPM Image',          //sc_XPM_Image
  'PNM Image',          //sc_PNM_Image
  'TARGA Image',        //sc_TARGA_image
  'TIFF Image',         //sc_TIFF_image
  'All',                //sc_All
  'Confirmation',       //sc_Confirmation
  'Delete record?',     //sc_Delete_record_question
  'Copy record?',       //sc_Copy_record_question
  'Close page',         //sc_close_page
  'First',              //sc_first
  'Prior',              //sc_prior
  'Next',               //sc_next
  'Last',               //sc_last
  'Append',             //sc_append
  'Delete',             //sc_delete
  'Edit',               //sc_edit
  'Post',               //sc_post
  'Cancel',             //sc_cancel
  'Refresh',            //sc_refresh
  'Edit filter',        //sc_filter_filter
  'Edit filter minimum',//sc_edit_filter_min
  'Edit filter maximum',//sc_filter_edit_max
  'Reset filter',       //sc_reset_filter
  'Filter on',          //sc_filter_on
  'Search',             //sc_search
  'Auto edit',          //sc_auto_edit
  'Copy record',        //sc_copy_record
  'Dialog',             //sc_dialog
  'Insert',             //sc_insert
  'Copy',               //sc_copy
  'Paste',              //sc_paste
  'Row insert',         //sc_row_insert
  'Row append',         //sc_row_append
  'Row delete',         //sc_row_delete
  'Undo',               //sc_undo
  'Redo',               //sc_redo
  'Cut',                //sc_cut
  'Select all',         //sc_select_all
  
  'Filter off',         //sc_filter_off
  'Portrait',           //sc_portrait print orientation
  'Landscape',          //sc_landscape print orientation
  'Delete row?',        //sc_Delete_row_question
  'selected rows?',     //sc_selected_rows
  'Single item only',    //sc_Single_item_only
  'Copy Cells',          //sc_Copy_Cells
  'Paste Cells',         //sc_Paste_Cells
  'Close',               //sc_close
  'Maximize',            //sc_maximize
  'Normalize',           //sc_normalize
  'Minimize',            //sc_minimize
  'Fix size',            //sc_fix_size
  'Float',               //sc_float
  'Stay on top',         //sc_stay_on_top
  'Stay in background',  //sc_stay_in_background
  'Lock children',       //sc_lock_children
  'No lock',             //sc_no_lock
  'Input',               //sc_input
  'Button',              //sc_button
  'On',                  //sc_on
  'Off',                 //sc_off
  'Left border',         //sc_leftborder
  'Top border',          //sc_topborder
  'Right border',        //sc_rightborder
  'Bottom border',       //sc_bottomborder
  'Begin of text',       //sc_beginoftext
  'End of text',         //sc_endoftext
  'Inputmode',           //sc_inputmode
  'Overwrite',           //sc_overwrite
  'Deleted',             //sc_deleted
  'Copied',              //sc_copied
  'Inserted',            //sc_inserted
  'Pasted',              //sc_pasted
  'Withdrawn',           //sc_withdrawn
  'Window activated',    //sc_windowactivated
  'Menu',                //sc_menu
  'Beginning of file',   //sc_bof
  'End of file',         //sc_eof
  'Voice output',        //sc_voiceoutput
  'Speak again',         //sc_speakagain
  'First column',        //sc_firstcol
  'First row',           //sc_firstrow
  'Last column',         //sc_lastcol
  'Last row',            //sc_lastrow
  'Selection',           //sc_selection
  'Speak path',          //sc_speakpath
  'Disabled button',     //sc_disabledbutton
  'First field',         //sc_firstfield
  'Last field',          //sc_lastfield
  'First element',       //sc_firstelement
  'Last element',        //sc_lastelement
  'Slower',              //sc_slower
  'Faster',              //sc_faster
  'Window',              //sc_window
  'Area',                //sc_area
  'Area activated',      //sc_areaactivated
  'Volume down',         //sc_volumedown
  'Volume up',           //sc_volumeup
  'Cancel speech'        //sc_cancelspeech
);

function delete_n_selected_rows(const params: array of const): msestring;
begin
 with params[0] do begin
  if vinteger = 1 then begin
   result:= extendedconst[ex_delfileselected];
  end
  else begin
   result:= extendedconst[ex_deletefiles] + ' ' + inttostrmse(vinteger)+
          ' ' + extendedconst[ex_selected];
  end;
 end;
end;

const
 textgenerator: defaultgeneratortextty = (
              {$ifdef FPC}@{$endif}delete_n_selected_rows
                                     );
initialization
 registerlangconsts(extendedconst[ex_lang],@stockcaption,@modalresulttext, 
        @modalresulttextnoshortcut,@textgenerator);
                               
end.

```

**Comment by glixx** [comment]
> mseconsts_fr.pas(279,8) Error: Identifier not found "tg_delete_n_selected_rows"

It must be constant instead. I wrote just example how to do. It should be extendedconst[ex_delfileselected] instead of tg_delete_n_selected_rows
Try again using %s

**Comment by fredvs** [comment]
Please, that is old story, take a look at commits.

**Comment by glixx** [comment]
Try again using %s please.

**Comment by glixx** [comment]
And I'm not sure translated strings are following order. Needs to write converver to recreate files. And we have new languages

**Comment by glixx** [comment]
Your way is workaround. Only one way is standard - using %s.

**Comment by fredvs** [comment]
> Your way is workaround. Only one way is standard - using %s.

Martin's way:

```
function delete_n_selected_rows(const params: array of const): msestring;
begin
 with params[0] do begin
  if vinteger = 1 then begin
   result:= 'Delete selected row?'
  end
  else begin
   result:= 'Delete '+inttostrmse(vinteger)+' selected rows?';
  end;
 end;
end;
```

My way (working perfectly and inspired by Martin's way):

```
function delete_n_selected_rows(const params: array of const): msestring;
begin
 with params[0] do begin
  if vinteger = 1 then begin
   result:= extendedconst[ex_delfileselected];
  end
  else begin
   result:= extendedconst[ex_deletefiles] + ' ' + inttostrmse(vinteger)+
          ' ' + extendedconst[ex_selected];
  end;
 end;
end;

```

PS: I did try your way without success.

**Comment by glixx** [comment]
> My way (working perfectly and inspired by Martin's way):

No. You did not write equally.

**Comment by fredvs** [comment]
> > My way (working perfectly and inspired by Martin's way):
> 
> No. You did not write equally.

What is different apart the constant used?

**Comment by fredvs** [comment]
I stop, goodnight.

**Comment by glixx** [comment]
Command:
`xgettext -L Lua -a mseconsts_en.pas -o mseconsts.pot`
adds 'en' string in POT file.
It can be changed on `#101#110`
I used `#37#115` already for `%s`

**Comment by glixx** [comment]
If you're doing localization constants by one file only, then https://github.com/mse-org/mseide-msegui/issues/25 using console mode needs to use all PO files to generate pas files.

**Comment by glixx** [comment]
https://github.com/mse-org/mseide-msegui/commit/ab3e45cc5a5d5a017eb7d3aee3f5f9a223de791b
Do you see now how to use `%s`? And compare German to see differences.

**Comment by glixx** [comment]
> Command:
xgettext -L Lua -a mseconsts_en.pas -o mseconsts.pot
adds 'en' string in POT file.
It can be changed on #101#110
I used #37#115 already for %s

Still actual

**Comment by fredvs** [comment]
I do not understand %s is used now.

**Comment by glixx** [comment]
No more mseconsts_en.pas for xgettext.
To pass "en" from POT file it can be changed on #37#115

**Comment by fredvs** [comment]
OK "en" will be omitted for export/import in po files.

**Comment by fredvs** [comment]
Done in last commit.
