### ISSUE TITLE
Fix of all msei18n -no NT- + resize problems.

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#12]
I think that commit `bcb8735` fixes all the problems of `no NT` and resizing in `msei18n`.
There was a problem in `tmainfo.filternode`.
@glixx could you try last commit with your `mselang_i18n.trp`?
Thanks.

**Comment by fredvs** [comment]
In last 2 commits i reversed all the changes in `msei18n/main.pas` for the grid (widthmax, widthmin, autoresize-off, etc).
This to have the same original behavior of the grid (auto-reside, etc) than Martin gave.
And because, IMHO, the bug it fixed.

**Comment by glixx** [comment]
It works only if "strings only" and "no NT" are enabled together, but if "strings only" is disabled and  "no NT" is enabled, then filter works wrong.
![Screenshot_20190311_005939](https://user-images.githubusercontent.com/2681872/54094457-1f4eac00-43b2-11e9-9e61-3413c82da025.png)

**Comment by fredvs** [comment]
Aarrgh, ok, i know where to fight.
The bug resists but agonizes too.

OK,  I go back to war.
Write you later.

**Comment by fredvs** [comment]
Huh, for what do you need "strings only"  disabled?

**Comment by glixx** [comment]
"strings only" does not work many years, so I do not enable it.

**Comment by fredvs** [comment]
What  I do not understand is why with mine mselang_i18n2.trd all works including cvs but with yours no.

**Comment by fredvs** [comment]
Here the trd and the csv:

[mselang_i18n2.trd.zip](https://github.com/mse-org/mseide-msegui/files/2950403/mselang_i18n2.trd.zip)

**Comment by glixx** [comment]
Cannot be tested without your trp file.

**Comment by fredvs** [comment]
It is the same than yours.
Copy mselang_i18n2.trd in `/en` and "edit" change datafile with  mselang_i18n2.trd

**Comment by fredvs** [comment]
[mselang_i18n.trp.zip](https://github.com/mse-org/mseide-msegui/files/2950416/mselang_i18n.trp.zip)

**Comment by glixx** [comment]
Msei18n with "strings only" shows all strings for mseide, msei18n, mselang. So you fixed this bug.
Yes, your project works.

**Comment by fredvs** [comment]
Re-arghh, with your last committed `mselang_i18n.trp,` auto-sizing is not working ok.
In last commit I re-enable widthmax and widthmin and auto-size for grid in msei18n.

That way your last mselang_i18n.trd and my mselang_i18n2.trd is workng here.

>Yes, your project works.

Ha, for you too?

**Comment by glixx** [comment]
You filtered by NT only strings, but I filtered all lines.

> Ha, for you too?

Only my project is buggy, but it's good, cause helps to fix bugs.

"no NT" problem https://github.com/mse-org/mseide-msegui/issues/12#issuecomment-471372841 is still not fixed.

**Comment by fredvs** [comment]
You mean "no NT"  enabled + "string only" disabled ?

If so, yes, I will attack it asap.

**Comment by glixx** [comment]
Yes

**Comment by fredvs** [comment]
Hello.

OK, fixed with commit  0a0af98.
This uses a workaround to remove the NT rows if "no NT" enabled + "string only" disabled.
(There is a problem with node-filter that must be fixed in msegui-widgetset).

Tested here for export cvs and works too.
Added a "refresh" button (useful if you play with "NT" field).

PS: It works only if the `trd` file is not corrupted, otherwise delete the `trd` and re-recreate a new one.

**Comment by glixx** [comment]
Your workaround works.
CSV export is still empty.

**Comment by fredvs** [comment]
> CSV export is still empty:

Here it works.
