### ISSUE TITLE
CSV export is empty

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#13]
If "no NT" enabled, then CSV export is empty for mselang project.

**Comment by fredvs** [comment]
Hello.
I do not understand what you did because here it is working.

[nont.zip](https://github.com/mse-org/mseide-msegui/files/2956372/nont.zip)
[msei18n.trd.zip](https://github.com/mse-org/mseide-msegui/files/2956377/msei18n.trd.zip)

**Comment by glixx** [comment]
Just enable no NT and press export on current mselang project.

**Comment by fredvs** [comment]
It is what I did with the nont.zip in attachment.
What `trd` file are you using?

Could you sent it as attachment?

I really want to understand why it is working here and not for you.

**Comment by glixx** [comment]
Files from Mselang -> lang_en from git.

**Comment by fredvs** [comment]
OK,I will try with this and (try to) understand what appends.
Write you later.

**Comment by fredvs** [comment]
Hello.

I did this:
- clone mseide-msegui (to be sure t is the last from github).
- compile `msei18n` project + run it.
- choose project /`mseide-msegui/apps/ide/lang_en/mseide_i18n.trp`
- export as csv with `no NT` + not `String only `and `no NT` +  `String only` 

Result:
[mseide.csv.zip](https://github.com/mse-org/mseide-msegui/files/2957293/mseide.csv.zip)

For me it seems ok.

**Comment by fredvs** [comment]
Ooops, you are talking about mselang project.
Ha, ok, I will try this later.
(But strange that mseide is working, it is much bigger and complex that mselang)

**Comment by fredvs** [comment]
Ooops, you are talking about `mselang` project.
Ok, I will try this asap.

**Comment by fredvs** [comment]
Yes, indeed with from last commit  `mselang/src/lang_en/mselang_i18n.trp` the `csv` is empty.
IMHO, the `trp` is corrupted.
I will try to understand why (or maybe you have a idea).
If it works for `mseide` (that is much bigger for translation) it should work for `mselang` too.

**Comment by fredvs** [comment]
I think I get it (maybe).
Maybe it is because you have set the root-object to NT.
If you set for example patheditfo, mainfo to NT = false, and this for all rows with type of vaNull, it will work.

Maybe the Martin idea is to set translation on/off for all the object and childs and if you set it to NT, all childs will not be translated.

Anyway, doing this make work your `mselang/src/lang_en/mselang_i18n.trp`

**Comment by fredvs** [comment]
And maybe there was no bug `not String only + no NT`.

In fact it was wanted, the rows that appear with `NT=true` are warnings.
Most of then should be set to `NT=false`  to make export working.

I did try with your original mselang_i18n.trp with my fix for no NT disabled.
And yes, setting most of the row with `NT=true` to false make your file work.

What do you think of all of this?
Maybe I can revert my my fix for no NT and for all rows with NT=true, change the color to yellow.
This to (try to) explain that those row are warnings-row.

**Comment by fredvs** [comment]
Hello.
More and more it seems to me that it was not a bug but wanted to show the possible trouble rows.

If you set a vaString as NT=true, it will not appear in the grid with `String only=false + no NT=true`
This because there is no warning to give.

Huh, if so, once again, **big** wow to Martin.

**Comment by fredvs** [comment]
Maybe add "`Warning`" check-box.
If enabled, the warning-row will be show otherwise use the workaround-fix to hide the rows.

**Comment by fredvs** [comment]
If you agree I may commit those change.

**Comment by glixx** [comment]
If to go this way msei18n will be too hard for translators. The first of all this tool is not for developers, but for users, who knows nothing about parents and childs.
I preffer to write msei18n tool easier. For users it should work like: what I see on display, it must be exported.
So let's disable Martin's alghorithm and will go own way. Anyway I don't see situations when it was really needed.
And the next problem, that msei18n does not keep original string and translated string together. Disabling this function will help to work with each string independently.

**Comment by fredvs** [comment]
OK, so I will not commit those change.

But what about your mseide_i18n.trp ?
Did you try to set some  `vaNull` as `NT=false` and then export as `csv`?

Is it still empty?

**Comment by fredvs** [comment]
`So let's disable Martin's alghorithm and will go by own way. Anyway I don't see situations when it was really needed.`

Maybe with your mseide_i18n.trp?

;)

**Comment by fredvs** [comment]
> And the next problem, that msei18n does not keep original string and translated string together. Disabling this function will help to work with each string independently.

That is not really a problem.
"Show warning" can be set to false by code when cliquing on "Export".

**Comment by glixx** [comment]
I understood what wanted Martin and you reproduced issue and found reason. But I do not agree with disabling/enabling translations for childs. Noone translation tool goes this way. Poedit is simple enought.
Needs to be more user friendly.

**Comment by fredvs** [comment]
OK, so if I understand ok, you want to keep only my workaround to hide the vaNull as NT=true.

OK,

But, sorry to repeat, did you find a solution for your mseide_i18n.trp ?
Did you try to set some vaNull as NT=false and then export as csv?
Is it ok for you or does it problems for the exported csv?

**Comment by fredvs** [comment]
> But I do not agree with disabling/enabling translations for childs.

Do you want to re-write this?

**Comment by fredvs** [comment]
What can be done easy is to set automatically NT=true in the grid in place of remove it (like my workaround does).
That way the user do not need to do it.

**Comment by glixx** [comment]
I wrote on Pascal 10 more years ago, forgot a lot, and just support Pascal in repository at the moment.
But you can set for all VaNull as NT=true directly in code and hide them from msei18n tool by filter.

> But, sorry to repeat, did you find a solution for your mseide_i18n.trp ?

I did not test yet. But I guess you are right what will happen.

**Comment by fredvs** [comment]
> But you can set for all VaNull as NT=true directly in code and hide them from msei18n tool by filter.

Not sure to understand this: VaNull as NT=true
Should t not be VaNull as NT=false ?

**Comment by fredvs** [comment]
`But you can set for all VaNull as NT=true directly in code and hide them from msei18n tool by filter.`

OK to set all VaNull as NT=false and to hide.
But maybe there are other type than vaNull that could be hidden too.
Maybe vaCollection is not really needed too.
 (and with "String only", if all VaNull are set NT=false , will show all the strings to translate).

If so, maybe OK to set all VaNull as NT=false automatic but not hide it (for this use "String only").

**Comment by fredvs** [comment]
OK, I will do like you said.
Set all VaNull as NT=false and to hide.

**Comment by glixx** [comment]
> Maybe vaCollection is not really needed too.

Filter is not perfect. Some types are a priori not translatable. Good if you work on improving it.

**Comment by fredvs** [comment]
> Filter is not perfect. Some types are a priori not translatable. Good if you work on improving it.

I am inside but it you set automatic all VaNull as NT=false then I do not see more strings to translate when you use `String only `enable or disable.

So maybe ok to automatic set  all VaNull as NT=false but maybe not hide it.

**Comment by glixx** [comment]
> So maybe ok to automatic set all VaNull as NT=false but maybe not hide it, String only will do it

Yes. ok.

**Comment by fredvs** [comment]
OK done in commit b13ab9f.

Now loading your original mseide_i18n.trp and exporting as csv works out-of-the-box here.
(I hope for you too).

**Comment by fredvs** [comment]
Warning: Auto correction is working only if `String only=false + no NT=true`
              This will correct all the VaNull are set NT=true.
              If you do `String only=true + no NT=true` without having done before  `String only=false + no NT=true`, export to csv will not work.

Note that if you do once `String only=false + no NT=true`, export to csv will not work always, even for String only=true.

**Comment by glixx** [comment]
Very bad. Trying to fix issue new issues were created. Revert again :(

**Comment by glixx** [comment]
Let's revert.

Default Matin's alghorithm: I did not enable NT for VaNull for mselang and some strings were exported into csv:

"mainfo,tgroupbox4,llvmbindir,controller.filterlist.data,0:,0:",vaString,F,,MSElang source,MSElang source
"mainfo,tgroupbox4,filena,controller.filterlist.data,0:,0:",vaString,F,,All Pascal source,All Pascal source
"mainfo,tgroupbox4,filena,controller.filterlist.data,1:,0:",vaString,F,,MSElang source,MSElang source
"mainfo,tgroupbox4,filena,controller.filterlist.data,4:,0:",vaString,F,,All,All

So csv export doe not work for data strings.

**Comment by glixx** [comment]
`vaNull,T,` does not present in mseide, msei18n projects. So better does not touch vaNull.

**Comment by fredvs** [comment]
What do you think of my propositon to revert to Martin algorithm but colorize the row with NT=true?

**Comment by glixx** [comment]
Just revert the latest commit and test the latest mselang why data strings were exported into csv.
And yes, let's it will be warnings.

**Comment by fredvs** [comment]
OK, done.

**Comment by glixx** [comment]
> So csv export does not work for data strings.

Fixed by https://github.com/mse-org/mselang/commit/7087b5c27e854e7d4001503c20b6213ec1aee199

But needs to add warnings for vaList too.

**Comment by fredvs** [comment]
I redo a commit, maybe not needed?

**Comment by fredvs** [comment]
The last commit was a regression to original Martin algorithm.

**Comment by fredvs** [comment]
`But needs to add warnings for vaList too.`

I think it is fixed in last commit.

**Comment by glixx** [comment]
I guess CSV export is OK now.

**Comment by glixx** [comment]
> But what about your mseide_i18n.trp ?
> Did you try to set some vaNull as NT=false and then export as csv?
> Is it still empty?

All childs do not export into csv.
