### ISSUE TITLE
Button "refresh" looks good only in English

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#14]
![Screenshot_20190312_015011](https://user-images.githubusercontent.com/2681872/54169664-c0a63280-4484-11e9-84f6-01d53c040071.png)
Not enougth space for translated strings and for text of button.

**Comment by fredvs** [comment]
What do you propose?
Do you prefer to delete the button?
Because if the button is bigger, it will tke more space than the menu.
For me it is not a problem but maybe you want to keep the "lilliputian" design of Martin.

**Comment by fredvs** [comment]
Do you prefer to add a menu item "refresh" ?

**Comment by glixx** [comment]
> Do you prefer to add a menu item "refresh" ?

I guess so. Anchors are big problem of msegui.

**Comment by glixx** [comment]
But please restore place of checkboxes. They were ok before adding button.

**Comment by fredvs** [comment]
OK, I will do it.

**Comment by fredvs** [comment]
OK. done in commit a2cdb71.

What do you think, to help people, to add some infos in the `hint` fields for each menu-item + check-boxes?

**Comment by glixx** [comment]
Hints are good. Msei18n is not easy, any help system is good.

**Comment by fredvs** [comment]
Yes, IMHO, `hint` is a easy way to help people.

**Comment by glixx** [comment]
Yes

**Comment by glixx** [comment]
Fixed
