### ISSUE TITLE
msei18n: Add "Set all not string to NT" ?

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#15]
What do you think to add a button/menu "Set all not string to NT"?
This will check all the rows that are not string type.
It can be also a ""Set all string to not NT".

This because doing manually is hard work, mainly for a project like mseide.

**Comment by glixx** [comment]
I had same idea and was thinking about it yesterday, but you wrote issue faster :)
I just did not find way who to draw it in GUI better.

But today I know how to draw it!

We have checkbox "string only". Needs to add "not string" checkbox.
Pressing on NT (header of table) will enable/disable all rows that are visible at the moment.

**Comment by fredvs** [comment]
> I just did not find way how to draw it in GUI better.

To enable/disable NT by code it is a little tricky.
Maybe you may take a look how to do in my last commit  b13ab9f

**Comment by fredvs** [comment]
`Pressing on NT (header of table) will enable/disable all rows that are visible at the moment.`

Yes good idea (and I know how to do that).

**Comment by glixx** [comment]
I guess this proposal is not actual now except adding "not string" checkbox.

**Comment by fredvs** [comment]
Yes, imho, this is not necessary anymore.
