### ISSUE TITLE
Hints for msei18n

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#16]
To help people, to add some infos in the hint fields for each menu-item + check-boxes.

**Comment by fredvs** [comment]
Yes but now I have to go to sleep.

**Comment by glixx** [comment]
Why did you delete hint "Reset translated words to root value" for "Reset" ?

**Comment by fredvs** [comment]
> Why did you delete hint "Reset translated words to root value" for "Reset" ?

I do not know, fixed in last commit
