### ISSUE TITLE
Warnings do not show without pressing "Refresh" button.

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#17]
Msei18n: Warnings do not show without pressing "Refresh" button.

**Comment by glixx** [comment]
Needs to trigger colorizing event on mouse click on NT field.

**Comment by fredvs** [comment]
Yes I  now, I did try lot of things.

The only work around that works is to use a timer.
Are you ok for that?

**Comment by fredvs** [comment]
> Msei18n: Warnings do not show without pressing "Refresh" button.

> Needs to trigger colorizing event on mouse click on NT field.

> Msei18n: Warnings do not show without pressing "Refresh" button.

OK, fixed in last commit  8d05553  (without using timer).

**Comment by glixx** [comment]
No more warnings.

**Comment by fredvs** [comment]
> No more warnings.

Cannot reproduce, what project are you testing?
![warning](https://user-images.githubusercontent.com/3421249/54500521-dbadf200-491d-11e9-95e4-a9ada8ec80ed.png)

**Comment by glixx** [comment]
I tested all projects.

**Comment by fredvs** [comment]
> > I tested all projects.
> 
> The projects that are in https://github.com/mse-org/mseide-msegui ?

Hu, previous post seems a github bug, did you sent it?...

**Comment by fredvs** [comment]
OK,  get your files, I will test t tomorrow.

**Comment by glixx** [comment]
Tested same project with you - no more warnings.

**Comment by fredvs** [comment]
> Tested same project with you - no more warnings.

Here with your russian files, it works, sorry  do not understand.
If you set for example mainfo as NT=true, the row will become yellow but not hidden,

**Comment by glixx** [comment]
I see. Why not for disabled "no NT" too?

**Comment by fredvs** [comment]
> I see. Why not for disabled "no NT" too?

Because it is much more difficult!

**Comment by fredvs** [comment]
And because it is logic, if you do not set "no NT", there is no reason to give a warning, all will be exported   
like it appear.

**Comment by glixx** [comment]
Export is not only for "no NT".

**Comment by fredvs** [comment]
> Export is not only for "no NT".
> "no NT" is just special case, that we use, but developers use all cases.

OK, I will try.

**Comment by glixx** [comment]
I guess better to export all visible strings at the moment.

**Comment by fredvs** [comment]
> I guess better to export all visible strings at the moment.

All is working now.
If you only want to export visible strings, just select it.
(Huh, did you ask for full export a few issues ago?)

**Comment by glixx** [comment]
Warnings do not show without pressing "Refresh" button.

**Comment by fredvs** [comment]
Pfffffffffffff.

**Comment by fredvs** [comment]
I think I will do a break.
Just commit last changes with tools conversion of mseconst.
Only export root value is enabled now.
Importing po will be for later.

Thanks for all your attention.

Fre;D
