### ISSUE TITLE
Visual Studio Code plugin

### ISSUE THREAD

**Issue by lainz** [mse-org/mseide-msegui#17]
I think the IDE works for it's purpouse, but will be nice as well to have say a Visual Studio Code plugin, so I can edit the apps in a better code editor (text highlighted, where I can autocomplete, etc) and then compile these apps.

Of course I have no idea on how to do that, but there are some pascal stuff for Visual Studio Code in the vscode plugin downloads. Instead of having an IDE, maybe is time to have a plugin for a code editor?

Is just an idea, is just because at work I use Visual Studio Code.

**Comment by lainz** [comment]
https://github.com/alefragnani/vscode-language-pascal

**Comment by lainz** [comment]
Ok, I tested the plugin and is not that good, no autocomplete, so better keep with the IDE.

**Comment by fredvs** [comment]
You may try ideU, it has autocomplete features (supervised by Circular) and much others add-in.
https://github.com/fredvs/ideU

**Comment by lainz** [comment]
Thanks, I will try the improved version.

**Comment by fredvs** [comment]
To enable Auto-completion, click on the lamp icon on left side of commandor-form.

And if you want more infos about auto-completion, here some tips:
https://github.com/fredvs/ideU/issues/29

**Comment by lainz** [comment]
Nice, thanks. I'm on vacation so I will try new stuff. Maybe I create some nice icon for Ide U and MSE. The same icon in vector format.

**Comment by fredvs** [comment]
Wow, yes thanks.

If you are on Windows 10 there are some problems with the last release and file path formatting.

So it is better to recompile ideU.exe using trunk of ideU-source and msegui-source.

But you still need to install the release to have all the pluggins (and replace only the new binary of ideU.exe)

I will release a new version Windows 10 full tested asap.

**Comment by lainz** [comment]
Here are the icons, first try... I'm a bit rusty with graphic design, too much coding!

[mse icon.pdf](https://github.com/mse-org/mseide-msegui/files/5197879/mse.icon.pdf)
[ide u icon.pdf](https://github.com/mse-org/mseide-msegui/files/5197884/ide.u.icon.pdf)

The IDE U icon is totally different, the MSE icon is very similar not 100% equal.

**Comment by fredvs** [comment]
Wow, I like it.

For ideU it is in one word with a U maj at end (but maybe it is better in 2 words).
And maybe the point on the i bigger and in yellow?

**Comment by fredvs** [comment]
> I will release a new version Windows 10 full tested asap.

Ok, there is a new binary release:
https://github.com/fredvs/ideU/releases/tag/2.4.2

**Comment by lainz** [comment]
> Wow, I like it.
> 
> For ideU it is in one word with a U maj at end (but maybe it is better in 2 words).
> And maybe the point on the i bigger and in yellow?

Hi, yes the original icon is very different. But I'm not sure on how to draw it on vector, maybe using a kind of gradient but again I'm a bit rusty, I used to know how to do that.
