### ISSUE TITLE
Adding a readme.md?

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#18]
Hello everybody.

What do you think to add a `readme.md` file that will be loaded by the GitHub site as main page instead of the `readme.txt`?

Imho, the `readme.txt` should be mentioned in the `readme.md` file as a "must read" but `readme.md` could be more attractive, with a beautiful layout, with images, ... for main page of the web site.

Sadly I am not a pro in `md` files, maybe somebody that knows `md` and how to nicely present mse-ide/gui could give some tips.

(or even better (help to) do it...)

Fre;D

**Comment by lainz** [comment]
Hi, I've created the readme.md based on the .txt file

Pull request
https://github.com/mse-org/mseide-msegui/pull/19

**Comment by fredvs** [comment]
Hello Leandro.

Many thanks.

About the text to use, maybe we can use the one of
https://pascal.developpez.com presenting mseide-msegui:

https://pascal.developpez.com/telecharger/detail/id/4121/MSEideplusMSEgui-un-RAD-pour-Free-Pascal

It is in french but easy to translate.

Fre;D

**Comment by lainz** [comment]
Unfortunately my french is not as good, I can say bonjour and the numbers from 1 to 10, my french course didn't went well this year.

**Comment by fredvs** [comment]
OK,  I will try to do something (but it will never have the perfect verve of Roland).

Fre;D




.

**Comment by fredvs** [comment]
By the way, like it is now is much more attractive than the original readme.txt.
