### ISSUE TITLE
msei18n: Default value not correct when adding new object.

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#18]
This is the continuation of this issue: https://github.com/mse-org/mseide-msegui/issues/1#issuecomment-472302081

**Comment by fredvs** [comment]
Hello.
It seems that the problem comes from menu item and their index.
I did insert a new menu-item "Refresh" after "Settings" and it assign the index in grid as the last one.
If the new menu-item was added at end (and not inserted), it would not be problem.

Can you please check if there are problems with other components or is it only with menu?

**Comment by fredvs** [comment]
Contrary at other components that are indexed by their name, menu-items are indexed by the position in the array of items. 

And msei1n sees only that array of items is bigger and just add rows, without to know if thos items were inserted or added at end.

When they are added to end, no problem, the order is ok, but if they are inserted, all the order is destroyed.

What I see as solution for the program msei18n is to change the menu for buttons.
This will solve the problem for the program.

Of course t will not solve the menu problem for other programs, like msede (not pssible to replace menu by buttons).

What I see as workaround for menu-items treated by msei18n is to change the color of all rows of menu-items to prevent to give attention for maybe index error in names.

**Comment by glixx** [comment]
I translated mseide many years and it is always big mess with translations for any components.

**Comment by fredvs** [comment]
OK, but now it s time to fix that.
Do you have problems with other components than menu or other object with index, like list-boxes, etc...

**Comment by glixx** [comment]
No. Needs to remember original strings and there translations. trd file keeps this information, msei18n must read trd file better.

> Do you have problems with other components than menu or other object with index, like list-boxes, etc...

All components are problematic.

**Comment by fredvs** [comment]
That say, I am not fan to use library as language file.
First because they are fpc libraries, so big and slow.
Second because you are slave of a program, here msei18n.
Three I prefer simple txt files.

**Comment by glixx** [comment]
Do not touch menu of msei18n. Needs to fix bug, but not workaround it. msei18n must display all strings correctly and it must not have matter where they were placed.

**Comment by fredvs** [comment]
> it must not have matter where they were placed.

That will be the most difficult to fix.

**Comment by glixx** [comment]
msei18n will works with pot/po, this bug is not only for library.

**Comment by fredvs** [comment]
> msei18n will works with pot/po, this bug is not only for library.

Ha, ok.

**Comment by glixx** [comment]
> That will be the most difficult to fix.

I don't think so. Needs to add reading of trd file and update all rows with according trd file. As a result we will see right rows. All appended srings will not updated, just to fix there default value.

**Comment by fredvs** [comment]
So you will do a check on the default value of the item and not to the index-item of the menu (like msei18n does)?

Hum, doable.

**Comment by glixx** [comment]
Needs to read each string of trd file.
"Name Type Comment Value"
If msei18n has same row  with "Name Type Comment Value", then update NT, translation (if translation = "" then translation=Value) from trd file.

> So you will do a check on the default value of the menu-item and not to the index of menu-item (like msei18n does)?

Both. The first by index. The second by "Name Type Comment Value". But if indexing works wrong, then without index.

**Comment by glixx** [comment]
Import works wrong too.
![Screenshot_20190314_093040](https://user-images.githubusercontent.com/2681872/54321225-31725980-4601-11e9-8420-a743e5ecce40.png)

**Comment by fredvs** [comment]
Good challenge, if we solve one, we solve the other.

**Comment by glixx** [comment]
Still not fixed. It uses value+1.

**Comment by fredvs** [comment]
Is it fixed now?

**Comment by glixx** [comment]
This bug is on control. When you will add new strings then to test this issue.

**Comment by glixx** [comment]
I sent you by email prjoect of 2013 to reproduce this bug. I hope you will fix. It uses value+1 string.

**Comment by fredvs** [comment]
Please re-upload the original msei18n.trp so I can see the problem of a new item added.

**Comment by fredvs** [comment]
OK, I did try your file and indeed &Refresh is not on the right place.

Can you see other problems?

**Comment by fredvs** [comment]
Ooops, indeed, inserting a new menu-item break all.
The bug is still there, I have to recheck all.

Sorry for this.  But now I know a little better were is the problem.
Ok, I rejump into it.

**Comment by glixx** [comment]
I tried to check my old mseide project, but it has big mess of strings and I could see nothing, I'll test again after fix this bug.

**Comment by glixx** [comment]
If to open mseide project, 2013, Russian, then files of mseide were changed. So after this error all translated Value='', but not default Value.

**Comment by fredvs** [comment]
> If to open mseide project, 2013, Russian, then files of mseide were changed. So after this error all translated Value='', but not default Value.

Not well understood, is it ok with new commit?

**Comment by glixx** [comment]
I am about if translated value='' then translated value should be = value

**Comment by fredvs** [comment]
> I am about if translated value='' then translated value should be = value

Interesting, I did not think of this, I will do it now.

**Comment by fredvs** [comment]
Done:  a3df3df
