### ISSUE TITLE
mse18n: Missing rows with "no NT"

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#19]
Hello.
I think the bug of missing rows with `no NT = true` is fixed with commit 2ed6e12.
The problem came with a wrong implementation of the index for string lists.

For all string lists like menu, string-container, etc, ... `NT` is set to false now at loading of the project and if it was before set to `true`, the original language-value will be used.

I agree it is not perfect because for that kind of object with string-list, you will need to check the translation because `NT` column will be set always to false at loading of the project.

So for string-list object, just keep the original value to set as not to translate.
For all other objects, `NT` column is working.

But it should fix the missing items.

About wrong implementation of translated word, it should be fixed it too.
(But not for your last `trp` because you did save already `&Refresh` as `E&xit`, for this you need to recreate a  new `trd` file, or correct the errors).

**Comment by glixx** [comment]
Hi,
I just opened Russian project of msei18 and msei18n and half of translated strings were lost.
Problematic components:
```
*.data.*
*.c.*
*.defs.*
```

"&Refresh" is still wrong.

**Comment by glixx** [comment]
No more yellow warnings even if to press Refresh.

**Comment by glixx** [comment]
Tested mselang project. NT flag was restored from trd file.

**Comment by fredvs** [comment]
> Hi,
> I just opened Russian project of mseide and msei18n and half of translated strings were lost.
> Problematic components:
> 
> ```
> *.data.*
> *.c.*
> *.defs.*
> ```
> "&Refresh" is still wrong.

Please, can you sent me a Russian project so  may see what is wrong.

**Comment by fredvs** [comment]
> Tested mselang project. NT flag was not restored from trd file.

Please read first post of the issue.

**Comment by fredvs** [comment]
> No more yellow warnings even if to press Refresh.

https://github.com/mse-org/mseide-msegui/issues/17#issuecomment-473732182

**Comment by glixx** [comment]
Regress is too big.

**Comment by glixx** [comment]
It's ok if you set NT=false at loading of the project for all strings, but need to restore absolutely all strings from trd file: their NT flag and translation.

**Comment by fredvs** [comment]
> It's ok if you set NT=false at loading of the project for all strings, 

It is not for all strings,  only for those part  of a list.

> but need to restore absolutely all strings from trd file: their NT flag and translation.

Is it a problem if a string in a list in place have  NT flag to true, it has  NT flag to false but the original value is used (and dont translate it)?

**Comment by fredvs** [comment]
> Regress is too big.

Please do not say to fast t must be regressed, maybe that way we can fix item-order.
Otherwise, I do not see how to do.

**Comment by glixx** [comment]
trd file has full information about all strings. Needs to read this file fully and use all information from it. Otherwise bugs cannot be fixed.

> It is not for all strings, only for those part of a list.
I don't understand why you do it partially. All strings at loading must have default values. Values must be changed by according trd file.

> Is it a problem if a string in a list in place have NT flag to true, it has NT flag to false but the original value is used (and so it is like dont translate it)?

I don't understand you.

**Comment by fredvs** [comment]
>I don't understand why you do it partially. All strings at loading must have default values. Values must be changed by according trd file.

The problems comes because you have set some strings part of a list as `NT = true`
There is a bug in assigning the index if some  `NT = true` are set.

So at loading of the project, if some strings part of a list as `NT = true`, it will automatically be set as false to preserve the index of the list.

**Comment by fredvs** [comment]
> All strings at loading must have default values. Values must be changed by according trd file.

For the "en" or "ru" column? No, if you set to NT = true, the value will be set to "" (empty).
So the dea is to set  "en" or "ru" column with the default value and set t to NT = false,

**Comment by glixx** [comment]
1. Creating default project.
2. Merging with trd file.

Merging does not work correctly.
All strings from tstringcontainer are translatable, this component was created specially fot this task. So it's error if somebody set NT for string of tstringcontainer. But you can fix it by ignoring.

Merging alghorithm:
Read component name from trd. If this name is present in project, then read NT flag from trd and use it.
If this name is present, then read Value from trd. If this Value is present for same name in project, then read translated string (if translated string is missing then = Value) and use it.

**Comment by fredvs** [comment]
>  So it's error if somebody set NT for string of tstringcontainer.

I do no understand, mselang project, there are lot of strings from list that should be set as NT:
for example:
mainfo.tsyntaxpainter1.deftext.data.0:  'ABSOLUTE' 'ABSTRACT' 'AND' 'ARRAY' 'AS' 'ASM' 'ASSEMBLER' 'BEGIN'

But if you set some of that deftext.data as NT=true, you will break the order.

**Comment by fredvs** [comment]
Maybe both of us has to sleep on this and we will see better the things tomorrow.

**Comment by glixx** [comment]
> But if you set some of that deftext.data as NT=true, you will break the order.

No. Merging is the next step after creating default project.

**Comment by fredvs** [comment]
> Merging does not work correctly.

OK, tomorrow I will try with your files (because here it works perfetly now).

**Comment by glixx** [comment]
> (because here it works perfetly now).

No. You have exported NT strings. Other is not visible for en, cause Value=en Value.

**Comment by fredvs** [comment]
Yep, I get it, could you try with last commit  3d1e730  , tested with your Russian file and seems ok now.

**Comment by glixx** [comment]
Try to read NT from trd file better.

**Comment by fredvs** [comment]
> Try to read NT from trd file better.

Ha, it works not ok for you?

**Comment by glixx** [comment]
> Ha, it works not ok for you?

Not ok, but way looks ok. trd file has NT information, just merge it too.

**Comment by fredvs** [comment]
> Not ok, but way looks ok. trd file has NT information, just merge it too.

I do not understand, you want NT information for list of strings too (and so problems with index order)

**Comment by glixx** [comment]
Some translations were lost:
![Screenshot_20190318_031020](https://user-images.githubusercontent.com/2681872/54504466-d44e0f00-4944-11e9-97d0-50c9e2279e61.png)
![Screenshot_20190318_031130](https://user-images.githubusercontent.com/2681872/54504467-d44e0f00-4944-11e9-8e19-20800e2c61b2.png)

**Comment by glixx** [comment]
> I do not understand, you want NT information for list of strings too (and so problems with index order)?

Not for list, but items from this list.

**Comment by fredvs** [comment]
> Not for list, but items from this list.

Huh, that is what I try to explain, it will not work for items inside a list.

**Comment by fredvs** [comment]
> Some translations were lost:
> ![Screenshot_20190318_031020](https://user-images.githubusercontent.com/2681872/54504466-d44e0f00-4944-11e9-97d0-50c9e2279e61.png)
> ![Screenshot_20190318_031130](https://user-images.githubusercontent.com/2681872/54504467-d44e0f00-4944-11e9-8e19-20800e2c61b2.png)

OK, I will check that (but bizarre).

**Comment by fredvs** [comment]
Please say what file you are using.

**Comment by glixx** [comment]
mseide

**Comment by glixx** [comment]
> Huh, that is what I try to explain, it will not work for items inside a list.

It is possible. trd file has information, just to read it and use.

**Comment by fredvs** [comment]
Ha, ok, i never tested it.
O, I will check/test it tomorrow.

Good night.

**Comment by fredvs** [comment]
> > Huh, that is what I try to explain, it will not work for items inside a list.
> 
> It is possible. trd file has information, just to read it and use.

Maybe tomorrow..

**Comment by glixx** [comment]
And if Value='' then NT=true.

**Comment by glixx** [comment]
After "Make" NT were lost.

**Comment by glixx** [comment]
> Some translations were lost:
> ![Screenshot_20190318_031020](https://user-images.githubusercontent.com/2681872/54504466-d44e0f00-4944-11e9-97d0-50c9e2279e61.png)
> ![Screenshot_20190318_031130](https://user-images.githubusercontent.com/2681872/54504467-d44e0f00-4944-11e9-8e19-20800e2c61b2.png)

These strings were lost not now, but before like it was happen with "Total rows:". So never mind.

**Comment by glixx** [comment]
So needs to improve reading NT flag from trd file for lists.
Do not loose NT flag after Make.
And to set NT=true for all strings, what has Value='' (nothing to translate in this case, but it's hard job to mark them as NT espetially for mseide project).

**Comment by glixx** [comment]
This bug was fixed. Even some lost strings were found.
For other bugs I opened new issues.
Thanks.
