### ISSUE TITLE
Cannot change interface font and spacing

### ISSUE THREAD

**Issue by circular17** [mse-org/mseide-msegui#2]
For now the only way to make the font bigger is though the command line. On Windows:
`start mseide --FONTALIAS=stf_default,,24`

It would be better to have a setting in the application so that it would not be necessary to have console.

While this changes the font size, the spacing around the text stays the same. It would be great to make this space proportional the the font size or to provide a setting for it as well.

**Comment by rchastain** [comment]
I haven't tried, but I think that you can also add the parameter in the desktop shortcut properties.

**Comment by rchastain** [comment]
I confirm that you can add the parameter after the exe name, in the shortcut properties.

**Comment by circular17** [comment]
I tried to add in the shortcut and it works well. Thanks.

What remains to set the spacing.

**Comment by fredvs** [comment]
> What remains to set the spacing.

Maybe try with a other font, like stf_proportional, or stf_courier or stf_roman or stf_helvetica ?

`start mseide --FONTALIAS=stf_proportional,,24`

**Comment by fredvs** [comment]
> It would be better to have a setting in the application so that it would not be necessary to have console.
> 
> While this changes the font size, the spacing around the text stays the same. It would be great to make this space proportional the the font size or to provide a setting for it as well.


I fear that is not possible out-of-the-box, you should jump inside MSEide code to change that.
It was asked many times but Martin wanted a "compact look".

Once again, all that are implemented with ideU, but I absolutely dont want to convert you.

Fre;D

**Comment by fredvs** [comment]
I am absolutely not against to change behavior of MSEide, but not sure Martin would like that. 
On the other side, I am totally open for any positive change in ideU.

**Comment by circular17** [comment]
Using another font doesn't work at all. It ignores the size provided as parameter.

I compared with ideU and in this case, it seems the spacing between menus is bigger so that's better for this. Though there are other layout issues. I will add them in ideU project.

**Comment by fredvs** [comment]
> Using another font doesn't work at all. It ignores the size provided as parameter.

That is not normal, ok I will check this.

> Though there are other layout issues.

Did you try the menu "Layout" ?

**Comment by circular17** [comment]
I like the menu Layout, that's handy.

**Comment by fredvs** [comment]
> Using another font doesn't work at all. It ignores the size provided as parameter.

You are totally right!
Give me 10 minutes, I know where is the problem, only stf_default is initialized, I will add some more.

**Comment by circular17** [comment]
> You are totally right!
> Give me 10 minutes, I know where is the problem, only stf_default is initialized, I will add some more.

Haha I cannot be always wrong.

Thanks for looking at the problem.

I noticed that the layout I have applied in ideU now applies to MSEide as well.

**Comment by fredvs** [comment]
> I noticed that the layout I have applied in ideU now applies to MSEide as well.

Of course ideU is 100% compatible with MSEide.
But a ideU project save more extra infos, like copyright, author, etc, ... and has more compiler options.
So if you save a project with ideU and load it with MSEide + save, those extra-infos will be lost.

> Give me 10 minutes, I know where is the problem, only stf_default is initialized, I will add some more.

Hum, it will be more than 10 minutes, much more.
This because if you want to change font with command line parameter, there is a filter in code, that allows to use only the default font name.
I dont know why Martin did that restriction but I am afraid to touch to that.

Anyway, once again, ideU does it, go in menu "Settings-Extra config-Font name and size.
And there I can change all what you want, without using any command line.


Fre;D

**Comment by circular17** [comment]
I would not want you to get stressed out with changes that may have unforeseen consequences.

About the extra config, the font size is not there yet in version 2.0.0. But I am doing alright with the shortcut properties.

What remains is the spacing between menus. Is it easy or difficult to make it proportional to font?

**Comment by fredvs** [comment]
> About the extra config, the font size is not there yet in version 2.0.0. But I am doing alright with the > shortcut properties.

Oops, yes, not yet in the last release.
But now that you are a mse-guru, it will be easy to compile the last commit.
After compilation, just copy the result  /ideU/src/ideU.exe into the directory of the release.

This because in ideu/src/ are only source, not all the plugin provided by ideU release.

**Comment by circular17** [comment]
Nah I am just trying to make an onpaint event:
https://github.com/mse-org/mseide-msegui/issues/5

**Comment by rchastain** [comment]
Hello friends!
I have just noticed something about fonts in this wiki page.
https://wiki.freepascal.org/MSEide_%26_MSEgui

```
So if you start the mseide like this, you can get a larger menu font:
 mseide --FONTALIAS=stf_menu,sans,16
In order to increase the base font size for all stock fonts use
 mseide --FONTALIAS=stf_default,,16
```
By the way, I started to translate the page to french, which isn't easy for me because there are things that I don't understand. :)

**Comment by circular17** [comment]
Interesting.

Good luck for the translation! (no irony intended)

**Comment by fredvs** [comment]
>  because there are things that I don't understand. :)

If you want help, dont hesitate, I am ready.

**Comment by rchastain** [comment]
Thank you guys. I will do what I can and when it is finished I will ask you to take a look.

**Comment by fredvs** [comment]
May we close this?

**Comment by circular17** [comment]
I suppose we can. There is still the question of spacing of menus. Though I am not insisting on it just noting that it is a possible improvement.

**Comment by fredvs** [comment]
Sincerely, about spacing of menu, it is easy to fix.
But, sincerely again, it was asked many time to Martin, with the same answer: "No, MSEide is designed to be the most compact possible. If you want a other look, MSEide is open-source and change all what you want."

So it is not a bug and wanted by Martin.

**Comment by circular17** [comment]
Ok. That's fine, there is ideU :-)
