### ISSUE TITLE
Improve reading NT flag from trd file for lists

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#20]
trd file keeps NT info for lists too.
So for lists: item by item to compare them as Value and if this item is NT, then use NT.

**Comment by glixx** [comment]
An alternative: blacklist implementation.
Add in msei18n "Blacklist" in Menu. Strings that will be added in blacklist can be stored in trp file and will be ignored by export.
But I don't like it.

**Comment by fredvs** [comment]
Or maybe add a check-box "only Translated" that will show only the "green" strings.

**Comment by fredvs** [comment]
IMHO, the most important now is to fix the bugs.
Is it ok with last commit?

If yes maybe we may play with the grid options.

**Comment by glixx** [comment]
It will not work. Languages have original string=translated string often. And if you will use "only Translated"  then POT file will be empty.

I did not test yet.

But I guess only one way is the best: reading trd file for NT information for lists.

**Comment by fredvs** [comment]
> But I guess only one way is the best: reading trd file for NT information for lists.

Done in commit 8430f6f  
I hope the index order is still ok.

Could you try it?
Thanks

**Comment by glixx** [comment]
Looks ok
