### ISSUE TITLE
Wrong link to mse-org on freepascal website

### ISSUE THREAD

**Issue by mark-summerfield** [mse-org/mseide-msegui#21]
On this page: https://www.freepascal.org/fcl/fcl.html there is a link to MSEide+MSEgui which takes you to the old sourceforge website instead of this one. I can't report this on their bug tracker because I don't have (or want) a login for it, but presumably you do.

**Comment by fredvs** [comment]
Hello.

Many thanks for this.
I will sent a post to Lazarus forum.

**Comment by fredvs** [comment]
https://forum.lazarus.freepascal.org/index.php/topic,53080.0.html
