### ISSUE TITLE
Do not loose NT flag

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#21]
after Make (or possibly other actions) NT flag for lists loses.

**Comment by fredvs** [comment]
Could you try with commit 8430f6f ?

**Comment by glixx** [comment]
Partially fixed. Needs to refresh after closing Make window.

**Comment by fredvs** [comment]
> Partially fixed. Needs to refresh after closing Make window.

Could you give more infos please, I do not understand.

**Comment by fredvs** [comment]
OK,  I see, I will fix this tomorrow.

**Comment by glixx** [comment]
It does not lose NT flags now, but after Make needs to Refresh display. Pressing on Refresh helps.

**Comment by fredvs** [comment]
Done in last commit: e328a96

**Comment by glixx** [comment]
Fixed

**Comment by glixx** [comment]
Same problem after Edit->Cancel. Possibly other actions.

**Comment by fredvs** [comment]
Done in commit 21484bb
