### ISSUE TITLE
Install instructions are wrong

### ISSUE THREAD

**Issue by mark-summerfield** [mse-org/mseide-msegui#22]
On this page https://github.com/mse-org/mseide-msegui it says:

1. Download and install FPC, you can get it from http://www.freepascal.org/download.var
2. Download mseide_msegui from https://github.com/mse-org/mseide-msegui/archive/master.zip
3. Extract them to a directory of your choice ('yourdirectory') .
4. Run 'yourdirectory/bin/mseide' on Linux and FreeBSD or 'yourdirectory\bin\mseide.exe' on windows.

But when I did step 2. there was no `bin` dir. This is what `ls` says:
```
$ ls mseide-msegui-master/
apps         COPYING.GPL   COPYING.MSE  help   lib            msegui_32.png  msegui_64.png  readme.md   tools
contributed  COPYING.LGPL  DEBUG.TXT    icons  msegui_24.png  msegui_48.png  msegui.svg     README.TXT  VERSION.TXT
```

**Comment by fredvs** [comment]
Ooooops, you are right, the first line is missing!

This readme.md was the one provided in the release doc.

So, step one is:

-  Download and unzip **mseide** binary according your OS here:
   https://github.com/mse-org/mseide-msegui/releases/

Thanks to note it, I will fix this asap.

**Comment by fredvs** [comment]
Ok, done in commit 9b4bc84b3.

The step missing is number 4.

Thanks to note it.
