### ISSUE TITLE
Set NT=true if Value=''

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#22]
For strings: set NT=true for all strings automatically, what has Value='' (nothing to translate in this case, but it's hard job to mark them as NT espetially for mseide project).
And

msgid ""
msgstr ""

is wrong, `msgid ""` is reserved for header info of POT/PO file.

**Comment by fredvs** [comment]
Done on commit:  3d9c176  

Note that for strings of list (string-container, menu-items,...)  `NT=true` only if `value='' .`
For all other strings of list, if `value <> '' `.then it is automatically set to  `NT=false`.
This to preserve the index-order.

**Comment by glixx** [comment]
Fixed
