### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by mark-summerfield** [mse-org/mseide-msegui#23]
1. Is it possible to build apps using msegui without using the IDE? I prefer just using vim. I guess that means I'd need some kind of make file?
2. Is it possible to stop the text caret (cursor) from blinking in text fields? I can't work with blinking. (Microsoft offered the option to stop blinking across all apps with Windows 2000, but for Linux it is trickier. See https://jurta.org/en/prog/noblink .)

**Comment by fredvs** [comment]
Hello.

1. Yes of course but, imho, for the graphic things it is much easier to use the msegui-form-designer provided in **mseide**.

2. **mseide** has as goal to be the most compact and simple possible.
    I prefer to not touch to original mseide code (only to fix bug if it appears).

 3. If you want to use a IDE that is a fork of mseide, with msegui-designer included and with much more options you may try ideU:   https://github.com/fredvs/ideU/releases

**Comment by fredvs** [comment]
> I guess that means I'd need some kind of make file?

No, only the command line for fpc.
For example to compile mseide from command line, just do:

`$ cd /dir-of-mseide-msegui/   // go to directory of mseide-msegui`


Then for Linux:
`$ fpc -Fulib/common/* -Fulib/common/kernel/linux apps/ide/mseide.pas`

For Windows:
`$ fpc -Fulib\common* -Fulib\common\kernel\windows apps\ide\mseide.pas`

**Comment by fredvs** [comment]
Hello.

In last commit https://github.com/fredvs/ideU/commit/dfcede4244194ef6b2f03c2c871d00688690bf97 of _ideU_ there is option to stop blinking caret: 

![Capture d’écran_2021-01-28_19-08-53](https://user-images.githubusercontent.com/3421249/106182927-d4a1cd00-619f-11eb-81db-7801b14e4284.png)

**Comment by fredvs** [comment]
Re-hello.

If you want to stop the blinking-caret in mseide, you may do this in _/mseide-msegui/lib/common/kernel/msepointer.pas_

At line 489:

```
procedure tcaret.restart;
begin
 updatestate;
 //  ftimer.interval:= ftimer.interval;  // comment this
 // ftimer.enabled:= true;     // comment this
end;
```

And recompile mseide.

**Comment by mark-summerfield** [comment]
Thank you!
