### ISSUE TITLE
Add "not string" checkbox

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#23]
We have "only string" checkbox, but "not string" checkbox is missing.

**Comment by fredvs** [comment]
Is it really needed?

**Comment by glixx** [comment]
Having this checkbox is not bad.

**Comment by fredvs** [comment]
Done in commit: 79c29c9.

Note that exporting with "no string" = true is not allowed, a warning message will appear.
Note also that if you set "no string" = true and compare with "string only" = true, you will see that there is a difference of 1 row.
I loose all my hair for this so I need help now.
It would be great if you could find what is the row missing, sorry, I do not find it.

**Comment by fredvs** [comment]
> Note also that if you set "no string" = true and compare with "string only" = true, you will see that there is a difference of 1 row.

Yep, fixed (I hope) in commit 4b4ad80

**Comment by glixx** [comment]
Good to see you fixed other bug.

**Comment by glixx** [comment]
Many yelow warnings, saving NT in file does not work. They are always NT.

**Comment by fredvs** [comment]
OOOps, indeed, I will fix it.
Sorry, all code has changed, I must recheck this.

**Comment by fredvs** [comment]
Should be fixed in last commit.

**Comment by glixx** [comment]
Done
