### ISSUE TITLE
using macros for trp

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#24]
/home/fred is good to convert into macros ~

**Comment by fredvs** [comment]
Yes, I was thinking of this from the beginning but it will be very difficult,
This because msei18n uses `tfilenameedit` for the name of the files and macros will not work.
So everything should be re-written.

**Comment by glixx** [comment]
Yes it changes ~ on /home/user

**Comment by fredvs** [comment]
Maybe when all the bugs are fixed and all works perfectly, I will jump on it.

**Comment by glixx** [comment]
Yes. Later.

**Comment by fredvs** [comment]
If you are happy with 1 macro: "Directory of project files" is can be easy done.

But if you want more than one, it will be more complicated.

**Comment by fredvs** [comment]
For example this is ok and easy to do:
Macro1only = "Directory of project files"  = `'/home/fred/mseide-msegui/'`

But this will be much more complicated to make work:
Macro1 = "Directory 1 of project files"  = `'/home/fred/mseide-msegui/'`
Macro2 = "Directory 2 of project files"  = `'{Macro1} + tools/mseide'`

**Comment by glixx** [comment]
Problem is removing user fred from trp file to be usable by any user.

**Comment by fredvs** [comment]
> Problem is removing user fred from trp file to be usable by any user.

Yes, it is what I have done, it works perfectly.
Sadly I just done a bad key-press and all the modifs are gone.
;(
But I have still code in mind, so if you want, I can commit it.

**Comment by glixx** [comment]
I'm not sure macros is good. Needs to use ~ for home dir in trp file and it should work out of box.

**Comment by fredvs** [comment]
Please try last commit!

**Comment by glixx** [comment]
There are 2 ways:
* use ~ for home dir
* use relative paths

**Comment by glixx** [comment]
Language project always has fixed location, so using relative paths has sense. In this case do not need new macro, no changes in gui, just in code.

**Comment by fredvs** [comment]
Done in last commit.
