### ISSUE TITLE
Problems with Radeon (and maybe other graphic drivers) on Linux 64 bit

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#24]
Hello.
Could somebody that uses a Radeon driver (or has problem with msegui rendering) on Linux 64 bit bit try the binary of MSEide in attachment?

And see if it is better?

Many thanks.

[mseide.zip](https://github.com/mse-org/mseide-msegui/files/6175869/mseide.zip)

**Comment by fredvs** [comment]
Alexander who uses a Radeon graphic card and try the binary gives this video:

![mse_from_list](https://user-images.githubusercontent.com/3421249/111880292-e25b1e00-89aa-11eb-8b32-3f62b1b279c2.gif)


So it does not fix the problems.

Any idea is welcome.

**Comment by fredvs** [comment]
In case of rendering problems on Linux, could you please run the console-program binary in attachment?
It will show the name and number of your graphic card.

And give here the result of the program, with a short description of the problem?

There is a 64 and 32 bit version.

Many  thanks.
[ggd64_32.zip](https://github.com/mse-org/mseide-msegui/files/6224664/ggd64_32.zip)

**Comment by galaxysite** [comment]
> ggd64_32.zip

Currently:

I do not have this problem with computers:

1.
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV610 [Radeon HD 2400 PRO]
2.
00:02.0 VGA compatible controller: Intel Corporation 82945G/GZ Integrated Graphics Controller (rev 02)
3.
02:00.0 VGA compatible controller: NVIDIA Corporation GT218 [GeForce 210] (rev a2)

And have problem with 1 multivideocard computer:

01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV410 [Radeon X700 PRO]
01:00.1 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] RV410 [Radeon X700 PRO] (Secondary)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV620 LE [Radeon HD 3450]

Problem touch only grids content. Buttons, labels, menus working normally.

**Comment by fredvs** [comment]
Hello Alexander (?)
What kind of problem do you get with grids?
On what OS (unix or windows)?

**Comment by galaxysite** [comment]
> (?)

Yes.

OS GNU/Linux Debian Sid at all comps.

Problems similar as on upper video. When click to cell, grid lost form and not selection possible. But if before this problem touch all computers - currently only one.

https://github.com/user-attachments/assets/e721c8ea-f40a-4041-a7e7-b734b8bb0078

**Comment by fredvs** [comment]
Is it from your project: GALAXY ORGANIZER from http://soft.self-made-free.ru/  ?
The best would to try with a msegrids.pas with lot of debug to isolate the problem and know what cause it.
(Last time I did try your project all was ok but I dont have a Radeon X700)
Write you later with msegrids.pas with debug in attachment.

**Comment by galaxysite** [comment]
Yes, Galaxy Organizer.

> Write you later with msegrids.pas with debug in attachment.

Ok.

**Comment by fredvs** [comment]
Just before to jump, is the total length of the grid > the length of grid on screen?
I mean, does the grid should have scrollbars?
Because I had this problem and a workaround was needed.

**Comment by galaxysite** [comment]
In this case, yes. All 3 grids overfill and have scrollbars.

But I'm not sure that this is the case in all programs.

**Comment by fredvs** [comment]
OK, I dived, let's find the guilty, write you later.
 
![Screenshot_2024-10-25_17-14-14](https://github.com/user-attachments/assets/09a8358a-9454-4a69-9353-244e81705a54)

**Comment by fredvs** [comment]
Do you still have the same problem with last MSEide/ideU Object Inspector (it is a twidgetgrid) like in your first post with Radeon X700?
Or is it now only with the 3 tfilelistview in ee.pas ?
Is it ok with tstringgrid1 (tstringgrid) of yearlistfo ?

**Comment by galaxysite** [comment]
Oh ! Runned GORG. Good !
Then in last versions is worked draft use globalhotkey(s) and hook clipboard. Via extenal patch of MSE.

Not only in ee.pas and not only GORG. In all dependents from MSE programs.
I add video about it.


https://github.com/user-attachments/assets/e43dc11c-3ce8-4315-a983-d268983fb1a8

**Comment by fredvs** [comment]
>Then in last versions is worked draft use globalhotkey(s) and hook clipboard.

Yes, I have seen that so I commented all the new options in your code, to be able to test the rest.
Also commented this because it did not work on my system:
`// efd := open_evdev('/dev/input/by-path/platform-pcspkr-event-spkr');
`

> Not only in ee.pas and not only GORG. In all dependents from MSE programs.
> I add video about it.

Ha, ok, I see, not only tfilelistview widget but all with a grid
Then it is still the same problem like your first post.
;-(
OK, back in the jungle again.
PS: To everybody: any idea is welcome.

**Comment by fredvs** [comment]
Did you try compiling without any optimization?

**Comment by fredvs** [comment]
Did you try to load with the debugger, after compiling with **-gl** ?
`> gdb /home/fred/Downloads/GORG64/gorg64`

Because the problem you show on video with gdb should give info of what goes wrong when you click on a cell.

**Comment by galaxysite** [comment]
Working, working. Newest versions use evdev access to speaker. Need to add user to some groups to turn on access to it and reboot computer. 

I try without optimization - same.

gdb doesn't feel this bug:

`
first@silver:~/src/GORG64$ gdb /home/first/src/GORG64/gorg64
GNU gdb (Debian 13.2-1+b1) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/first/src/GORG64/gorg64...
(gdb) run
Starting program: /home/first/src/GORG64/gorg64 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6de16c0 (LWP 1949)]
[New Thread 0x7ffff69e06c0 (LWP 1950)]
[Thread 0x7ffff6de16c0 (LWP 1949) exited]
[Thread 0x7ffff69e06c0 (LWP 1950) exited]
[Inferior 1 (process 1946) exited normally]
(gdb) 


first@silver:~/src/GORG64$ gdb /home/first/src/GORG64/mseide
GNU gdb (Debian 13.2-1+b1) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/first/src/GORG64/mseide...
(gdb) run
Starting program: /home/first/src/GORG64/mseide 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff655c6c0 (LWP 1790)]
Syntaxdeffile: Unable to open file "/home/first/src/GORG64/apps/ide/syntaxdefs/pascal.sdef"
Нет такого файла или каталога

Thread 1 "mseide" received signal SIG44, Real-time event 44.
0x0000555555d9a56f in SYSTEM_$$_FPSYSCALL$INT64$INT64$INT64$INT64$$INT64 ()
`

**Comment by fredvs** [comment]
Hum, strange that gdb does not catch anything in gorg64.
For mseide, it is because the directory of mseide was not ok in mseide/config.

So at the moment it seems that the bug is mainly for twidgetgrid and tfilelistview.
Not for list of menu nor for list of history-edit nor combo-box nor tstringgrid (ok ?)

**Comment by galaxysite** [comment]
Yes, combobox working, but at the moment opening (very short time) see digital noise.
This seems suspicious to me.

Clean work only menu, buttons. Good working tstringgrid.

**Comment by fredvs** [comment]
>Yes, combobox working, but at the moment opening (very short time) see digital noise.
>This seems suspicious to me.

Indeed, not good, so something to do when the list is shown/hiden, like with the Object Inspector when select a item and it shows the list of sub-items.

But you said that for menu, selecting a item shows sub-items without problem ...
I will compare then how menu does vs combobox.

**Comment by fredvs** [comment]
I propose that we get focus only to tfilelistview widget and see the others after.

In the code ee.pas, at line 1009, could you comment this procedures:

```
procedure teefo.onshch(const sender: tcustomlistview);
begin
// gev.scripts := tfilelistview3.selectednames;
end;
procedure teefo.onmusch(const sender: tcustomlistview);
begin
// gev.musics := tfilelistview2.selectednames;
end;
procedure teefo.onsndch(const sender: tcustomlistview);
begin
// gev.sounds := tfilelistview1.selectednames;
end;
```

Does it have same problems of rendering when selecting?
If no, maybe re-uncomment the methods and try adding at end of each procedure:
`sleep(100);
application.processmessages;`

**Comment by fredvs** [comment]
Hello Alexander.
I still focus exploring on **tfilelistview**, searching some ways  ...
But totally blind because here no problem of rendering.
It seems that the problem comes from tfilelistview.**onselectionchanged()**.
Could you try to use instead tfilelistview.**onitemevent()** with this (here for tfilelistview3):

```
procedure teefo.onitemev(const sender: tcustomlistview; const index: Integer;
               var info: celleventinfoty);
begin
if info.eventkind = cek_buttonrelease then
 begin
   writeln('onitemev: Before gev.scripts := tfilelistview3.selectednames');
   gev.scripts := tfilelistview3.selectednames;
   writeln('onitemev: after gev.scripts := tfilelistview3.selectednames');
 end; 
end;

```

And remove the procedure for onselectionchanged() -> onshch.

Does it still have problem when selecting something?

**Comment by galaxysite** [comment]
I try
1. comment this lines. Not effect.
2. uncomment and add sleep(100); application.processmessages; Not effect.
3. remove onshch and add given code. Not "Before" and not "after" showed.

Also I see about not working my 1 patch about global hotkey "Scroll Lock". 2 patch (about clipboard hook) working.
Maybe this will help find the bug?

**Comment by fredvs** [comment]
Hello Alexander.

Sorry but I am not sure to understand what you mean about **Not effect**

> 1. comment this lines. Not effect.

I suppose you refer to this:
```
procedure teefo.onshch(const sender: tcustomlistview);
begin
// gev.scripts := tfilelistview3.selectednames;
end;
procedure teefo.onmusch(const sender: tcustomlistview);
begin
// gev.musics := tfilelistview2.selectednames;
end;
procedure teefo.onsndch(const sender: tcustomlistview);
begin
// gev.sounds := tfilelistview1.selectednames;
end;
```

What is _Not effect_ ?  Do you still have the problem of bad rendering, even with commenting all that lines?

> 3. remove onshch and add given code. Not "Before" and not "after" showed.

Do you still get bad rendering when using **onitemevent()** in place of **onselectionchanged()** ?

>Maybe this will help find the bug?

Not sure, first we must find what cause the bug, what procedure produces that bad rendering.

**Comment by galaxysite** [comment]
Apparently, the program execution does not reach this point and any changes to the code there do not have any effect.

> Do you still have the problem of bad rendering, even with commenting all that lines?

Yes. And in console not printed "Before" and "after".

> Do you still get bad rendering when using onitemevent() in place of onselectionchanged() ?

Yes.

> Not sure, first we must find what cause the bug, what procedure produces that bad rendering.

But for some reason it does. On those machines where there is no error in MSE and the patch works, but on this one the patch does not work. It is possible that it will be easier to find the error. The patch has very few functions and the problem can be easily found, faster than with graphics, simply by understanding why the global ScrollLock button does not work. Maybe, of course. Or maybe we will find it through graphics.

**Comment by fredvs** [comment]
OK, so if I understand ok, using **onitemevent()** or **onselectionchanged()** is not the cause of the bug.

Hum,....

Did you try to do a simple demo, using only one tfilelistview and nothing else ?
This to see if the number of widgetset in the app has influence or not on the bad rendering?

>But for some reason it does. On those machines where there is no error in MSE and the patch works, but on this one the patch does not work. It is possible that it will be easier to find the error. The patch has very few functions and the problem can be easily found, faster than with graphics, simply by understanding why the global ScrollLock button does not work. Maybe, of course. Or maybe we will find it through graphics.

Sure, if you see something that could help to unmask the guilty, it is more than welcome.

PS: Dont worry, we will find it, even if it could need some white nights... ;-)

**Comment by galaxysite** [comment]
Regarding evdev, there is another quick way to enable it.
The distribution usually has a "beep" utility, and if you install it,
the speaker will also become available.

**Comment by fredvs** [comment]
>Regarding evdev,

```
~$ beep
Command 'beep' not found, but can be installed with:
sudo apt install beep
```

```
$ sudo apt install beep
Unpacking beep (1.4.9-1build1) ...
Setting up beep (1.4.9-1build1) ...
```

```
$ beep
beep: Error: Could not open any device
```

Maybe I need to reboot.

**Comment by fredvs** [comment]
Is your Github site https://github.com/galaxysite/gorg64_spkplay ok for using last code?
I did use the last zip from http://soft.self-made-free.ru/

**Comment by fredvs** [comment]
>my 1 patch about global hotkey "Scroll Lock". 2 patch (about clipboard hook) 

Please do a pull-request to mseide-msegui with this patches.

**Comment by galaxysite** [comment]
I made separate project with only tfilelistview. See same bug.
On github currently only console player from GORG64. And in full organizer and player contain fresh code.

Try (as root) as minimum for evdev:

/sbin/adduser username input
/sbin/adduser username plugdev
/sbin/adduser username audio

And reboot

**Comment by fredvs** [comment]
> fred@fred-IdeaPad: $ sudo /sbin/adduser fred input
> The user `fred' is already a member of `input'.
> fred@fred-IdeaPad: $ sudo /sbin/adduser fred plugdev
> The user `fred' is already a member of `plugdev'.
> fred@fred-IdeaPad: $ sudo /sbin/adduser fred audio
> Adding user `fred' to group `audio' ...
> Adding user fred to group audio
> Done.

OK, I will reboot later and give more info.
Thanks.

**Comment by fredvs** [comment]
OK, reboot done.

With this:

```
procedure tmainfo.oncreate(Const Sender: TObject);
var f : Int64;
begin
efd := open_evdev('/dev/input/by-path/platform-pcspkr-event-spkr');
```

I get that:

`Fstat failed. Errno : 2`

But in my system /dev/input/by-path there are only those:

![Screenshot_2024-10-26_14-24-48](https://github.com/user-attachments/assets/2dc0316b-9941-49c9-aa01-0bc1955fa273)

Note also this:
```
$ beep
beep: Error: Could not open any device
```
PS: I have a laptop, maybe pcspkr cannot be installed.

**Comment by fredvs** [comment]
>I made separate project with only tfilelistview. See same bug.

Ha, that is good news then we can isolate the problem.
It would be nice if you could do a video with this simple demo, showing step by step when it occurs, is it at mouse down or mouse up, when selecting the same or other item, etc...
Sorry to ask this but maybe some light could be seen.

**Comment by galaxysite** [comment]
> PS: I have a laptop, maybe pcspkr cannot be installed.

I will take this case into account and return the old code in the next versions GORG.

Thank you for the invitation, I accepted it.
Regarding the patch: at the moment it is external (in relation to the MSE code). But I suppose in the future it will be possible to grow something like two components from them: a global hotkey component and a copy-to-clipboard interception component. Then it would be included in the MSE code. But we need to think about it together. I have shown only the current possibility of this (but already practically useful and applicable), and for full implementation there is still a lot needed. In fact, as far as I understand, no one has yet used, for example, a global hotkey with a modifier.

At the moment, the external patch is applied like this:

`wget http://soft.self-made-free.ru/GORG64_271.tar.xz`

`tar -xvJf GORG64_271.tar.xz`

`cd GORG64`

`make`

`make deb`

`su`

`./installdeb.sh`

`exit`

If troubles:

`make clean`

**Comment by fredvs** [comment]
>Regarding the patch: at the moment it is external (in relation to the MSE code). 

The most easy for users, if you are using modified units from MSE, is that you add those modified units into the root directory of the project.
In that case at compilation those units will be used vs the one from MSEide-Msegui.

**Comment by fredvs** [comment]
>At the moment, the external patch is appliedll like this:

I did try to install it.
All was ok till **make deb**
There was a error because mold was missing, so I installed it
`$ sudo apt  install mold`

I re-try **make deb** but there are those errors and many other similar:

> <artificial>:(.text+0x1d1): undefined reference to `gtk_window_get_type'
> /usr/bin/mold: <artificial>:(.text+0x1e0): undefined reference to `g_type_check_instance_cast'
> /usr/bin/mold: <artificial>:(.text+0x206): undefined reference to `gtk_dialog_new_with_buttons'
> /usr/bin/mold: <artificial>:(.text+0x20e): undefined reference to `gtk_dialog_get_type'
> /usr/bin/mold: <artificial>:(.text+0x21c): undefined reference to `g_type_check_instance_cast'
> /usr/bin/mold: <artificial>:(.text+0x229): undefined reference to `gtk_dialog_set_has_separator'
> /usr/bin/mold: <artificial>:(.text+0x253): undefined reference to `gtk_label_new'
> /usr/bin/mold: <artificial>:(.text+0x25b): undefined reference to `gtk_container_get_type'
> /usr/bin/mold: <artificial>:(.text+0x269): undefined reference to `g_type_check_instance_cast'
> /usr/bin/mold: <artificial>:(.text+0x278): undefined reference to `g_type_check_instance_cast'
> /usr/bin/mold: <artificial>:(.text+0x283): undefined reference to `gtk_container_add'
> ...
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:50: deb] Error 1


It seems to be gtk things.
Must I install gtk too?

**Comment by galaxysite** [comment]
After "make" external patch working and can run GORG from directory.

For full installation, yes, C and some headers needed.
GORG64 installation currently contains:
1. Editor "leafpad" with patch which allows close by escape key. Use as fast text viewer and editor.
2. Analog gtk clock.
3. quad archiver.
4. tta codec (use as audio compressor in GORG).
5. wavfix. After recording by arecord (ALSA), rec (SOX) and even in UOS SimpleRecorder wav-file some bad (error in common librarys ?). wavfix make this:

first@my:~/src/Fredvs/uos/examples$ wavfix rec_24_10_27_06_51_18.wav 

> Processing 'rec_24_10_27_06_51_18.wav' 
| Current file structure :
| ======================
|     <fmt > chunk [offset: 0000000012; size: 0000000018 + 4 + 4;] 
|     <data> chunk [offset: 0000000038; size: 0000000000 + 4 + 4;] 
|     [NULL] chunk [offset: 0000000046; size: 0000327680 + 0 + 0;] 
|
| [i] Checking <data> chunk.. 
|  |  Chunk size is 0 byte. That is very unlikely..
|  |  A block of 327680 unknown bytes comes after <data> chunk.
|  |  Assume those are audio data. Merging them with <data> chunk..
|  |  done.
|
| Recovered file structure :
| ========================
|     <fmt > chunk [offset: 0000000012; size: 0000000018 + 4 + 4;] 
|     <data> chunk [offset: 0000000038; size: 0000327680 + 4 + 4;] 
|
| [i] Saving repaired file to 'rec_24_10_27_06_51_18_REPAIRED.wav'
| File successfully recovered.

**Comment by fredvs** [comment]
Hello Alexander.
Wow, your GORG project is very complete, I like it.

>UOS SimpleRecorder wav-file some bad 

There was some fixes recently about recording in uos.

On my system, the default size of font for form of ee.pas is too big, I set his height to 26 and it is ok now.
Also, (but this is a question of taste), I prefer to set rounded corner for the buttons.

![gorg64](https://github.com/user-attachments/assets/39d2b901-e25b-4585-b268-f0c35f995a95)

**Comment by fredvs** [comment]
About the bug while rendering with Radeon.
If only tfilelistview and twidgetgrid (at the moment) have problems, it is maybe related with the icon that both have in the row.
Maybe.

**Comment by fredvs** [comment]
>I made separate project with only tfilelistview. See same bug.

Could you test this:
Copy msefiledialog.pas in attachment in the root directory of your demo project.
[msefiledialog.pas.zip](https://github.com/user-attachments/files/17534471/msefiledialog.pas.zip)
This msefiledialog.pas has icon rendering disabled.
If, by chance, you dont get bug anymore, I think that, maybe, it is because of the mse-mask set on the icon imagelist (same problem with NetBSD and MacOS).
If this, a fix is easy.
Re-maybe.

**Comment by galaxysite** [comment]
Very nice design.
Probably need to add the ability to customize the font size.

I tried to apply this file to the test example. The icons disappeared, but the bug remained. I also applied it to GORG - no icons - the bug is there.

I have not described another nuance of creating a DEB package. It uses upx (`sudo apt install upx`) and sstrip (more power than strip) from http://soft.self-made-free.ru/ELFkickers_004.txz (unpack and `make deb`) to reduce the size of the executable.

**Comment by fredvs** [comment]
> tried to apply this file to the test example. The icons disappeared, but the bug remained. I also applied it to GORG - no icons - the bug is there.

;-(

Strange. I want to find why tfilelistview has problem and tstringgrid not.

**Comment by fredvs** [comment]
>Very nice design.

Thanks!
If you like rounded corner, in attachment ee.pas with frames rounded.
There is a timagelist5 with the shape of the corners and a tframecomp2 that you may use as template for the frame of the components you want.
[GORG64_ee.zip](https://github.com/user-attachments/files/17534770/GORG64_ee.zip)

**Comment by galaxysite** [comment]
Thank You !

**Comment by fredvs** [comment]
With pleasure!
And here ee with scrollbars of tfilelistview rounded too (better in the design).
[GORG64_ee2.zip.zip](https://github.com/user-attachments/files/17534877/GORG64_ee2.zip.zip)

**Comment by galaxysite** [comment]
Excellent ! Thank You !
![gorg_2024-10-27_20-58-29](https://github.com/user-attachments/assets/a039ec30-c259-4ebb-8742-91b2a7c870d2)

**Comment by fredvs** [comment]
>tried to apply this file to the test example. The icons disappeared, but the bug remained.

Maybe it is because of focusselect  that gives problem?
Could you try again to copy msefiledialog.pas in attachment in the root directory of your demo project. 
[msefiledialog_nofocus.zip](https://github.com/user-attachments/files/17536118/msefiledialog_nofocus.zip)

This one also dont have icon and when selecting a cell, it should not set the focus on it (background of cell dont change color).
Maybe there is a conflict when focusing after selecting.
If, by big chance, it fix the bug, could you test if all still work (apart that the selected cell is no more colored).  Here it is still working.

Of, course, maybe.

**Comment by galaxysite** [comment]
I try it, but bug stay up.

I connect problem machine to Internet. May be remote access via https://github.com/rustdesk/rustdesk/releases/tag/1.3.1  ?

**Comment by fredvs** [comment]
Of course, try all what could help us.

**Comment by fredvs** [comment]
Some good news from the front.
Thanks to Alexander and rustdesk, the bug was finally isolated.
It appears when selecting a cell from a TWidgetgrid or a Tfilelistview.
One fix is to force to redraw the widget after selecting a cell.
I used this not elegant but working code in oncellselected :
 ```
filelistview.hide;
filelistview.show;
```
What is the msegui method to refresh or redraw completely a widget?

**Comment by fredvs** [comment]
>What is the msegui method to refresh or redraw completely a widget?

`Thewidget.invalidatewidget;`

**Comment by fredvs** [comment]
OK, this works Thewidget.invalidatewidget;
________________________________
De : Fred vS ***@***.***>
Envoyé : lundi 4 novembre 2024 01:32
À : mse-org/mseide-msegui ***@***.***>
Cc : Fred vS ***@***.***>; Your activity ***@***.***>
Objet : Re: [mse-org/mseide-msegui] Problems with Radeon (and maybe other graphic drivers) on Linux 64 bit (#24)


Some good news from the front.
Thanks to Alexander and rustdesk, the bug was finally isolated.
It appears when selecting a cell from a TWidgetgrid or a Tfilelistview.
One fix is to force to redraw the widget after selecting a cell.
I used this not elegant but working code in oncellselected :

filelistview.hide;
filelistview.show;


What is the msegui method to refresh or redraw completely a widget?

**Comment by fredvs** [comment]
To test on Radeon machine.
[ideu_projectoptionsform_radeon.zip](https://github.com/user-attachments/files/17625488/ideu_projectoptionsform_radeon.zip)
Here the same for MSEide.
[mseide_projectoptionsform_radeon.zip](https://github.com/user-attachments/files/17626262/mseide_projectoptionsform_radeon.zip)

**Comment by galaxysite** [comment]
Thank You Fred,

In common, yes. But I see probably backgrounds problem.

Firstly, yesterday we saw the speaker not playing with a white background of the main panel (when noaction turn on panel have color). I was guided only by "V" in the menu. Because of this, some confusion occurred. Today I also saw this problem, but only once and could not reproduce it again.

Secondly, the cells of filelistview, when they have focus, are colored gray on other machines, but on that machine they are not.

So there are two problems left: one is difficult to reproduce, and the other is constant, and both are related to the background.

**Comment by fredvs** [comment]
>So there are two problems left: one is difficult to reproduce, and the other is constant, and both are related to the background.

It would be great if I could do again a remote session to do last fix MSEide/ideU (Project Options) and see what is wrong with the background (I did not see that background problem yesterday).

**Comment by fredvs** [comment]
Re-hello Alexander.
About the problem of color of mainform when sound is disabled.
I suppose it is done in procedure **tmainfo.DisplayMuteNoact** and one thing to try is to add **invalidatewidget** at end:

```
procedure tmainfo.DisplayMuteNoact;
begin
if tun.p^.fmute then begin
  mainfo.tpopupmenu1.menu.items[0].caption := '[v] ' + str_mute;
  mainfo.tpaintbox1.color := cl_yellow;
   end else begin mainfo.tpopupmenu1.menu.items[0].caption := str_mute;
     mainfo.tpaintbox1.color := cl_white;
   end;
if tun.p^.fnoact then
  mainfo.tpopupmenu1.menu.items[1].caption := '[v] ' + str_noact
  else mainfo.tpopupmenu1.menu.items[1].caption := str_noact;   

invalidatewidget;  // Add this
end;
```

If by chance it fix the problem, then we could try to fix it directly on the paintbox widget.

And for the problem of cell color background of Tfilelistview when focused, strange that I did not see that yesterday, all seems normal and I remember that the background on selected cell was gray (but maybe I missed something).

**Comment by galaxysite** [comment]
I make new version of GORG: http://soft.self-made-free.ru/GORG64_292.tar.xz
with "invalidatewidget;". And make screenshots filelist selection on both machines.
After this I see both screenshots on my monitor and see that... all ok. This means that the monitor connected there has such a color rendering (old Compaq). Then the issue with the selection background is removed. It remains for some time to test the background of the main panel with the added invalidatewidget and if that rare failure does not appear, then the Radeon bug can be considered completely resolved.

**Comment by galaxysite** [comment]
I tested switching "noact" with "invalidatewidget;" several times and found no problems. The bug can be considered completely closed. This is a big victory.

**Comment by fredvs** [comment]
Yeeep, I am very happy that this nasty bug is gone.

Could you give here in attachment the msegui units that was changed (the zip files are in /home/first/src/mseide-msegui-main)?
There was also some fixes in /home/first/src/ideU-main.

Also did you try the fixes of my previous post for MSEide Project Options form and the one for ideU?
https://github.com/mse-org/mseide-msegui/issues/24#issuecomment-2456009933

Is it ok now?

Now that the battle has nearly ended, imho, the guily is not Radeon but Mint and his buggy window manager (Martin has already alerted about this).
Anyway, nice that we have found a workaround.

**Comment by galaxysite** [comment]
Yes, I try fixes, all ok.

This files ?
[mselistbrowser.pas.zip](https://github.com/user-attachments/files/17636489/mselistbrowser.pas.zip)
[mseide-mseguigridslistbrowser.zip](https://github.com/user-attachments/files/17636490/mseide-mseguigridslistbrowser.zip)
[msegrids.pas.zip](https://github.com/user-attachments/files/17636492/msegrids.pas.zip)
[ideUchanged.zip](https://github.com/user-attachments/files/17636493/ideUchanged.zip)

**Comment by fredvs** [comment]
Yes, perfect.

OK, I will commit it after last check here with my laptop.
[EDIT] Done: b7c25d141822c091ab7e8ddaf55d780a20d21a45

Thanks Alexander, it was a great fight with a bright victory.
And rust remote is really wow.

**Comment by fredvs** [comment]
Hello everybody.

Shouldn't we release a new MSEgui release?
There have been bugs fixed since the last release a year ago.

It would also be best to release new binaries for MSEide (but that obviously requires more work).

Have a perfect week end.

Fre;D
