### ISSUE TITLE
Console mode of msei18n

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#25]
To build package needs to implement console mode of msei18n:
--help (help message like mseide has)
--merge
--make

It should build library in console mode using trp and trd only.
This mode is important to have up to date pas and mfm files of library.

**Comment by glixx** [comment]
I guess good to have creating library from po file too. It works in GUI now.

**Comment by glixx** [comment]
And add console mode for constants generation. It will allow to update translations for old versions mse from transifex.

**Comment by fredvs** [comment]
Console mode for msei18n: maybe in a future other release.
