### ISSUE TITLE
Demo file 

### ISSUE THREAD

**Issue by medhome63** [mse-org/mseide-msegui#26]
https://github.com/user-attachments/assets/9116dd44-a3f6-4982-9a03-f93972cb0b47

[demo.zip](https://github.com/mse-org/mseide-msegui/files/6459528/demo.zip)

![msegui_palette](https://github.com/mse-org/mseide-msegui/assets/3421249/f5c1212c-093a-4d39-8dd1-7dbd51767edb)

![msegui-opengl](https://github.com/mse-org/mseide-msegui/assets/3421249/b169a56a-689d-4699-9c52-c1181519cafa)

![mseide_openbsd_i386](https://github.com/mse-org/mseide-msegui/assets/3421249/4f89e119-56a0-45da-b1d4-576221611e49)

![mseide_netbsd32](https://github.com/mse-org/mseide-msegui/assets/3421249/0e5dbaef-d3fb-4a8f-bff3-c80d562f7fd3)

![mseclock_error](https://github.com/mse-org/mseide-msegui/assets/3421249/639de68b-b360-4708-837e-8f549a8fd8e8)

![fontdialog](https://github.com/mse-org/mseide-msegui/assets/3421249/e4e03570-513b-436a-b74a-24b81b9ad120)

![mseclock_error2](https://github.com/mse-org/mseide-msegui/assets/3421249/a8f2b598-d306-480a-9d92-c549bc748bbc)

[lib_darwin.zip](https://github.com/mse-org/mseide-msegui/files/13933315/lib_darwin.zip)

[lib_darwin2.zip](https://github.com/mse-org/mseide-msegui/files/13952740/lib_darwin2.zip)

[lib_darwin3.zip](https://github.com/mse-org/mseide-msegui/files/13953102/lib_darwin3.zip)

[lib_darwin4.zip](https://github.com/mse-org/mseide-msegui/files/13953471/lib_darwin4.zip)

[lib_darwin5.zip.zip](https://github.com/mse-org/mseide-msegui/files/13955485/lib_darwin5.zip.zip)

[MSEide.app.zip](https://github.com/mse-org/mseide-msegui/files/13991813/MSEide.app.zip)

![mse_darwin](https://github.com/mse-org/mseide-msegui/assets/3421249/ebf9ab8e-51ba-444e-931d-20376ffb59e8)

![msegui_trans](https://github.com/mse-org/mseide-msegui/assets/3421249/0c36e651-fb3a-4be6-afae-c2943ea14798)

![msegui_trans2](https://github.com/mse-org/mseide-msegui/assets/3421249/be83b377-9957-4d12-8bae-56d5d6bb9381)

[mseide_openbsd.zip](https://github.com/user-attachments/files/15826982/mseide_openbsd.zip)

![stat_mse](https://github.com/user-attachments/assets/70c4f495-70dd-4b0c-b562-7f6e5c774c64)

![stat_mse2](https://github.com/user-attachments/assets/3d2119d2-131d-4cfc-91b5-e7096606ead8)

**Comment by fredvs** [comment]
https://user-images.githubusercontent.com/3421249/181095567-74942a28-fcf0-4620-adf1-6d344f2f392a.mp4
[consoleform-windows.zip](https://github.com/mse-org/mseide-msegui/files/9192967/consoleform-windows.zip)



![sumfield](https://user-images.githubusercontent.com/3421249/191151535-2ab77c18-fb74-41f1-924e-97d85e3bf74d.png)

![msedb2_3](https://user-images.githubusercontent.com/3421249/196789011-38ac7e69-ffab-43f7-aeb3-bae38af3988a.png)
![msedb2_4](https://user-images.githubusercontent.com/3421249/196789046-44540696-8de1-4633-ba9b-0df3e6e7b00e.png)


https://user-images.githubusercontent.com/3421249/196801630-a1f4dace-e431-4719-8f21-a95959aea7f4.mp4

![home-fred-msetools-lang](https://user-images.githubusercontent.com/3421249/198856195-d27a4ae3-55cc-4d7b-a1b8-f820f8a08356.png)


![podemo_mo4stock_lang](https://user-images.githubusercontent.com/3421249/198856197-71efed12-6054-4a1a-a357-d38d9f0ada07.png)

![podemo](https://user-images.githubusercontent.com/3421249/198856206-673d79de-f8f7-4ad7-aad8-e3bdbbd9c6b2.png)

![mseide_openbsd](https://github.com/mse-org/mseide-msegui/assets/3421249/cfd0edc9-6e1a-46a0-aeec-fc5a63eab82c)

![mseide_openbsd_compile](https://github.com/mse-org/mseide-msegui/assets/3421249/4750a48e-a861-4af4-b258-eb014c4a2a96)

![mseide_openbsd_run](https://github.com/mse-org/mseide-msegui/assets/3421249/3ff71e23-396a-472a-a34e-083a37284cab)

![ideu_compile_openbsd](https://github.com/mse-org/mseide-msegui/assets/3421249/813bd25c-5f93-4130-8bb2-9249f19e89da)

![ideu_filedialog_openbsd](https://github.com/mse-org/mseide-msegui/assets/3421249/a8180cc9-e65f-4a05-a2c1-e9de4b3e160a)

![mseide_openbsd_link2](https://github.com/mse-org/mseide-msegui/assets/3421249/3c84c256-6c85-4c59-8ea8-42750d11d929)


![mseide_openbsd_link](https://github.com/mse-org/mseide-msegui/assets/3421249/067c81f0-0625-4f27-93ff-d5ff9c728290)

![mseide_netbsd](https://github.com/mse-org/mseide-msegui/assets/3421249/cfd179e9-3098-4604-af6a-8d64b54fb22c)

![mseide_netbsd_image](https://github.com/mse-org/mseide-msegui/assets/3421249/ec05ff42-2058-4c2f-9c39-746d9ac4d462)

![mseide_netbsd_image](https://github.com/mse-org/mseide-msegui/assets/3421249/73bae81e-f28c-4790-b26c-5f408a9a2975)

![mseide_netbsd_image2](https://github.com/mse-org/mseide-msegui/assets/3421249/3452e988-1504-44df-a9e9-84ecdf65806a)


[mseide_netbsd.tar.gz](https://github.com/mse-org/mseide-msegui/files/11727396/mseide_netbsd.tar.gz)

**Comment by fredvs** [comment]
zip file from Sieghard 15/12/2022

[mseide-msegui-shadow.zip](https://github.com/mse-org/mseide-msegui/files/10237207/mseide-msegui-shadow.zip)


![error](https://user-images.githubusercontent.com/3421249/224190166-757b36da-6a91-47f2-9466-d52eaf63d92f.png)
