### ISSUE TITLE
Import from csv is wrong

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#26]
It is result of bug https://github.com/mse-org/mseide-msegui/issues/18

**Comment by fredvs** [comment]
Here it works.

**Comment by glixx** [comment]
mseide project, 2013:
![Screenshot_20190322_002353](https://user-images.githubusercontent.com/2681872/54793171-36af5400-4c52-11e9-91a4-c66c1f1636cd.png)
![Screenshot_20190322_002438](https://user-images.githubusercontent.com/2681872/54793172-3747ea80-4c52-11e9-99ff-629288037141.png)

**Comment by fredvs** [comment]
I did not check this yet.

I will try.

**Comment by fredvs** [comment]
Hello.

I did try this: export to csv and then import that csv.

Here same result as original trd.

[mseide_ru.csv.zip](https://github.com/mse-org/mseide-msegui/files/2997904/mseide_ru.csv.zip)

**Comment by fredvs** [comment]
![msei18nru5](https://user-images.githubusercontent.com/3421249/54847391-7de32680-4cde-11e9-96ab-a35ba41b68f4.png)

**Comment by glixx** [comment]
Did you try project of mseide 2013?

**Comment by fredvs** [comment]
I did test the last file you gives me.
I do not now the year of the prject.
mseide_i18n.tar.gz

**Comment by fredvs** [comment]
And, still problems?

**Comment by glixx** [comment]
Yes, Still 12 strings are problematic. Same for import from trd.

**Comment by fredvs** [comment]
> Still 12 strings are problematic

The not yet translated ?
Yes strange but importing the po, only one is missing.

**Comment by fredvs** [comment]
> For projects 2013 everything is broken.

What project, the one you give me is ok?

**Comment by glixx** [comment]
Your screenshot https://github.com/mse-org/mseide-msegui/issues/26#issuecomment-475745871 shows 12 strings too.

> What project, the one you give me is ok?

mseide, 2013, msei18n, 2013 have very bad results of tests.

**Comment by fredvs** [comment]
> mseide, 2013, msei18n, 2013 have very bad results of tests.

I think I get t, it s a problem of virgule `,`
Will look at this tomorrow.

**Comment by glixx** [comment]
Looks ok now

**Comment by fredvs** [comment]
Welcome in Github Med!

Thanks for the demo, I will eat it asap.

Fre;D

Video of MDI_MSE

https://user-images.githubusercontent.com/3421249/118732862-70347780-b83b-11eb-8b82-2198d070a73a.mp4

![project_option_inherited](https://github.com/mse-org/mseide-msegui/assets/3421249/c80f937a-7a57-45ae-8f96-2767f3a05810)
