### ISSUE TITLE
LC_ALL=C encoding

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#28]
There is LC_ALL=C encoding problem again.

**Comment by fredvs** [comment]
Aaargh, ok, I will check it.

**Comment by fredvs** [comment]
It is ok for `trd` files with last commit.

But when importing PO files, lot of `?????`
Sorry I am blocked, all seems ok.
I really need to do a break.

**Comment by fredvs** [comment]
OK, fixed for importing PO files too.
