### ISSUE TITLE
msei18n: Importation of PO files.

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#29]
There is a first shot of importation of `po` files in last commits.
Testers are welcome!
But, sorry, with `LC_ALL=C` encoding, translated files are = `?????????`
It is hard to fix, so maybe, you may forget to use `LC_ALL=C encoding` at the moment for testing.
Thanks

**Comment by fredvs** [comment]
OK, all fixed in last commit, including the unique wrong multi-line.
I did test your Russian PO files from `/mseide-msegui/languages/mseide/mseide_ru.po` and, imho, it is...perfect.

How to do: Load the mseide `i18n.trd` click on "`Import`", select `po` files in filter, choose a `po` file, click `Ok` and cross your fingers.

If all did not explode you should have only one not translated word (and all others ok).

**Comment by fredvs** [comment]
Tested with French PO file, perfect too (but needs to translate lot of words).

By the way, is it not possible with `transifex` to automatically translate all the words by Google translate for example and then do a check manually?

**Comment by glixx** [comment]
1 string was not imported from PO:
![Screenshot_20190326_001250](https://user-images.githubusercontent.com/2681872/54962348-7ee1b580-4f75-11e9-9806-1d10b80f12f1.png)

**Comment by glixx** [comment]
> By the way, is it not possible with transifex to automatically translate all the words by Google translate for example and then do a check control manually for each word translated?

Yes, but not for free plans, so no.

**Comment by fredvs** [comment]
> 1 string was not imported from PO:

Yes and it breaks my head.

**Comment by glixx** [comment]
This is the last string of PO file.

**Comment by fredvs** [comment]
> This is the last string of PO file.

Yes, you get it, last string but not last of list.
OK, it has something to do with eof.
Thanks for the tip.

**Comment by fredvs** [comment]
OK, fixed.

But now I see a other problem, in trd file, the data are delimited by ` ,` but when there are , inside the data, there are problems.

OK, I have to find a other algorithm to define the data.

Tomorrow.

**Comment by glixx** [comment]
> OK, fixed.

I cannot confirm.

**Comment by glixx** [comment]
I hope import PO files even by full component name (msgctxt) will not be problematic. While we using transifex it can fill all same strings from own translation memory.
So even with inserting new item in a list just to upload POT file there and to get ready corrected translations. There is button there to download ZIP file with all translations (we do not need only en.po from ZIP file).

**Comment by fredvs** [comment]
When bugs are fixed with `,` all will be very easy and perfect.

**Comment by glixx** [comment]
I commited in languages/testing POT and PO files with msgctxt. So needs importation support for them too.

**Comment by fredvs** [comment]
OK, you are in love with `msgctxt`.

Maybe to mae everybody happy, we could add project options:

-`Do search by component name` (for example when using  `PO` + `msgctxt` or `trd`)

and

-`Do search by text value` (for example when using `PO` -  `msgctxt` or custom file)

**Comment by fredvs** [comment]
With last commit and double-search, `trd` files should work for `context` (search by `name` + `value`).

Asap I will enable import of `PO` with `context` (but before could you try if it works for `trd` now?)

**Comment by glixx** [comment]
![Screenshot_20190328_105440](https://user-images.githubusercontent.com/2681872/55123040-1ed44600-5112-11e9-89c3-758171b6a441.png)
I even don't know why you need options. We don't need them.
Export into cvs file was made by Martin. It exports all visible fields.
Export into trd file was made by Martin. It exports all fields.
Export into POT file without context is export root values only.
Export into POT file with context is export component names and root values.
Export into POT file with/without context is export component names and root values.
Export into PO file without context is export root values and translated values only.
Export into PO file with context is export component names, root values and translated values.
Export into PO file with/without context is export component names, root values and translated values.

Export into TXT:
TXT with root values
TXT with translated values

**Comment by glixx** [comment]
And only to allow one column of lang. So to change Edit dialog do not allow one more language row there.

**Comment by glixx** [comment]
![Screenshot_20190328_114926](https://user-images.githubusercontent.com/2681872/55123770-e1bd8300-5114-11e9-80b4-493f4c87734d.png)
So just to do detailed items of list.

**Comment by glixx** [comment]
https://github.com/mse-org/mseide-msegui/issues/33
Let's go by simple way without context support. In this case just add "POT templates files (*.pot)" in list.
TXT text files (*.txt)
->
TXT text files with root values (*.txt)
TXT text files with translated values (*.txt)

**Comment by fredvs** [comment]
> I even don't know why you need options. We don't need them.

Because I like easy things and out-of-the-box.
I am not rich and cannot pay for translation of my projects, like transiflex.
Also I do not like to depend of the good-will of people to translate for me.

So what I do, for example for `ideU` that has - 1500 words.

I use "`Export all - translation`" and "`Export root text only`".

In Google translate a import the file "`Export root text only`".
Google translate does the translation and I merge that new file with "`Export all - translation`".

It takes me less than 1 minute, all the translations are ok and importing that new file works out-of-the-box.

**Comment by glixx** [comment]
We don't need new dialog of export options.
You should detalize list of file dialog instead.
For your task you need to add
TXT text files with root values (*.txt)
TXT text files with translated values (*.txt)
instead of simple txt file.

**Comment by glixx** [comment]
Transifex is free for open source projects. Translators are volontiers.

**Comment by fredvs** [comment]
> We don't need new dialog of export options.
> You should detalize list of file dialog instead.
> For your task you need to add
> TXT text files with root values (_.txt) TXT text files with translated values (_.txt)
> instead of simple txt file.

OK, it is details.

**Comment by glixx** [comment]
Mseide, import po file with context msei18n_context_ru.po:
![Screenshot_20190329_100034](https://user-images.githubusercontent.com/2681872/55200381-ea728f80-51ce-11e9-9147-69a10447a8f5.png)

**Comment by fredvs** [comment]
AAAAAAAAAAArgh.

The same problem that I explained for the "|" character.
Now it is with the ";" too, randomely.
fpc has a BIG problem with utf.

I perfectly see the problem.

**Comment by fredvs** [comment]
OK, I go back to war.

**Comment by fredvs** [comment]
Here I am very lost:
;(

**Comment by glixx** [comment]
Martin used own strings.

**Comment by fredvs** [comment]
The problem is that it appends random.
I cannot discern why some list are ok and other no.

When using `|` as separator, it was easy, all list has the problem.
Now I use `;` and it append random.

**Comment by glixx** [comment]
It's not random, but translated_string+component_name.

**Comment by fredvs** [comment]
Here the problem:

```
procedure tmainfo.doread();
var
var
str1, str2, str3,str4 : utf8String;
begin
  str1 := 'thebegin';
  str2 := 'themidle';
  str3 := 'theend';
  str4 := str1 + ';' + str2 + ';' + str3;
 writeln(str4);
 
```   

Gives as result:

`$themidle;theend;thebegin`

?¿

**Comment by fredvs** [comment]
> It's not random, but translated_string+component_name.

Yes I see the problem but why translated_string+component_name sometime?

**Comment by fredvs** [comment]
When you use | it is always !

**Comment by glixx** [comment]
This is bug of fpc. Needs to open bugreport there, but for us it is only looking for workaround.

**Comment by fredvs** [comment]
> This is bug of fpc. Needs to open bugreport there, but for us it is only looking for workaround.

Bug report to fpc? Yes to wait one year for answer and 10 more for maybe fixes.
No, we have to find a work around (like many times for fpc).

**Comment by fredvs** [comment]
By the way, did you test strings with MSElang?
Out-of-the-box!

**Comment by glixx** [comment]
MSElang is not x86_64.

**Comment by fredvs** [comment]
Not yet, but you may produce form the `bc` file of MSElang 32 bit a 64 bit executable with LLVM..

**Comment by fredvs** [comment]
So if you have a multi-arch system, it is not a problem.

**Comment by glixx** [comment]
I use x86_64 only.

**Comment by fredvs** [comment]
I work on both (32 bit mainly for rpi)

**Comment by fredvs** [comment]
About the problem, it seems to be a memory allocation, some time it is mixed.

**Comment by fredvs** [comment]
Test using `cmem`, some problem.

**Comment by glixx** [comment]
And it's only for PO files with context.

**Comment by fredvs** [comment]
> And it's only for PO files with context.

It is the same with PO simple, I tested, but with PO simple the component name = `''`

**Comment by fredvs** [comment]
The totally true is this:
`procedure tmainfo.doread();
var
str1, str2, str3,str4 : utf8String;
begin
  str1 := 'thebegin';
  str2 := 'themidle';
  str3 := 'theend';
  str4 := str1 + ';' + str2 + ';' + str3 + str1; // str1 is added sometime at end
 writeln(str4);`

**Comment by glixx** [comment]
```
procedure tmainfo.doread();
var
str1, str2, str3,str4 : utf8String;
begin
  str1 : = '';
  str1 := 'thebegin';
  str2 : = '';
  str2 := 'themidle';
  str3 : = '';
  str3 := 'theend';
  str4 : = '';
  str4 := str1 + ';' + str2 + ';' + str3;
 writeln(str4);
```

**Comment by fredvs** [comment]
Good new!
This solves all: 
changing this:
 `str3 := wideStringReplace(str3, '\n', '', [rfReplaceAll]);`

with this:

`str3 := utf8StringReplace(str3, '\n', '', [rfReplaceAll]);`

Give me 2 minuts for the commit:

**Comment by fredvs** [comment]
Done:

**Comment by fredvs** [comment]
> We don't need new dialog of export options.
> You should detalize list of file dialog instead.
> For your task you need to add
> TXT text files with root values (_.txt) TXT text files with translated values (_.txt)
> instead of simple txt file.

Deleted Form option in last commit.

**Comment by fredvs** [comment]
>   str4 : = '';

Of course I tested this!
Chance that `utf8StringReplace`() works.

Now I have to say _respect_ to the developers of the utf8**** packages.

**Comment by fredvs** [comment]
> #33
> Let's go by simple way without context support. In this case just add "`POT templates files (*.pot)`" in list.
> `TXT text files (*.txt)`
> ->
> 
> ```
> TXT text files with root values (*.txt)
> TXT text files with translated values (*.txt)
> ```

Done.

**Comment by glixx** [comment]
Import does not work. For msei18n only 2 strings were imported from msei18n_context_ru.po

**Comment by fredvs** [comment]
Ooooops, sorry, sorry and sorry.
Fixed in last commit.

**Comment by glixx** [comment]
Nothing was commited.

**Comment by fredvs** [comment]
OK, done, it is really time for me to sleep (forgot to push).
Twice again sorry.

**Comment by glixx** [comment]
Same issue with random strings.

**Comment by fredvs** [comment]
> Same issue with random strings for mseide_context_ru.po, but mseide_ru.po is ok.

What random strings, same as` thebegin;themidle;theendthebegin` ?

**Comment by fredvs** [comment]
Indeed.
So now I am totally lost, yesterday it was working.

**Comment by fredvs** [comment]
Hello.
Huh, will it say with lot of precaution but think that it is working now in last commit.
The trick was to add ";" at beginning variable, like this:

```
procedure tmainfo.doread();
var
str1, str2, str3,str4 : utf8String;
begin
  str1 := ';' + 'thebegin'; // added ";" 
  str2 := 'themidle';
  str3 := 'theend';
  str4 :=  str1 + ';' + str2 + ';' + str3 ; 
 writeln(str4);`

```
Gives as result:

`$;thebegin;themidle;theend`

That seems to work ok.
But please dont ask me why it works now, I dont know.

Once again, that workaround seems to work here but maybe you will find a other mystery.

**Comment by fredvs** [comment]
OOOps, forget it last commit does not work.
Go back to war.

**Comment by fredvs** [comment]
I do not find new idea, all tips are wecome.

**Comment by fredvs** [comment]
Also it is very strange that the string that is appended as end is also random.
Sometimes it is the same as beginning (name of component), sometime it s totally random (name of a different component.

**Comment by fredvs** [comment]
Ha I get something!

See one of the problem of `senvmanagereditorfo,grid,fixrows.items,0:,captions.items,1:,caption`
added at end of `watchpoint.caption = Kind.`

In your po-context_ru file :+1: 

```
msgctxt "" //// This is empty!
"msesysenvmanagereditorfo,grid,fixrows.items,0:,captions.items,1:,caption"
msgid "Name"
msgstr "Имя"
```

msgctxt ""  --> No context!

OK, I will do a break and then continue the combat, but I think the end is near.

**Comment by fredvs** [comment]
Hello.

Could it be that your po file is corrupted?

This is working and seems correct:

```
msgctxt "projectoptionsfo,tlayouter9,tabwidget,debuggerpage,debugoptions,hint"
msgid "\"--tty DEVICE\" to set target terminal"
msgstr "\"--tty DEVICE\" установить терминал вывода из собранной программы"

```

But thiis (who makes problems) is different and all the others like this give problems: 

```
msgctxt ""  /// This gives problem
"projectoptionsfo,tlayouter9,tabwidget,debuggerpage,ttabwidget1,ttabpage6,caption"
msgid "Source &directories"
msgstr "&Директории с файлами исходного кода"
```

Should it not be like this:?
```
msgctxt "projectoptionsfo,tlayouter9,tabwidget,debuggerpage,ttabwidget1,ttabpage6,caption"
msgid "Source &directories"
msgstr "&Директории с файлами исходного кода"
```

**Comment by glixx** [comment]
I will test on Monday. Thank you for fixing.

**Comment by glixx** [comment]
Needs to filter some items of list for import.
It does not have sense for import:
'Data exchange files without translated values' (? what to import? NT flags only?)
'POT templates files without context'
'POT templates files with context'
'POT templates files with/without context'
'TXT text files with root values only'

**Comment by fredvs** [comment]
> Needs to filter some items of list for import.
> It does not have sense for import:
> 'Data exchange files without translated values' (? what to import? NT flags only?)
> 'POT templates files without context'
> 'POT templates files with context'
> 'POT templates files with/without context'
> 'TXT text files with root values only'

OK, now complete list of filter items is:
'Data exchange files ' 
'POT templates files without context'
'POT templates files with context'
'POT templates files with/without context'
'PO translation files without context'
'PO translation files with context'
'PO translation files with/without context'
'TXT text files with context and word'  // for Google translate: It works!

Of course we have to do a filter for the filters: a lst for import and a list for export.

**Comment by fredvs** [comment]
In fact, for import, it should not have filters.
The type of input is set automatic when reading the header of the file imported.

**Comment by glixx** [comment]
Yes, but filters hide files in directory and show only that you need.

**Comment by glixx** [comment]
Importation PO files were implemented.
