### ISSUE TITLE
micsoft pinyin will trigger  2  key down 

### ISSUE THREAD

**Issue by liuzg2** [mse-org/mseide-msegui#3]
win  10  micsoft pinyin will trigger  2  key down 
if i press a  chinese  '/' 
in   mseguiintf.pas 
some time trigger   wm_keydown ,  wm_ime_char

may be  i fixed it

**Comment by fredvs** [comment]
Hello liuzg2.
Welcome to GitHub!

I see in original Martin's mseconsts_zh: 

> MSEgui Copyright (c) 1999-2009 by Martin Schreiber 
> Chinese translation by liuzg2. 

Is it you?

**Comment by liuzg2** [comment]
wm_keydown,wm_syskeydown: begin
   shiftstate:= winkeystatetoshiftstate(lparam);
   if lparam and $40000000 <> 0 then begin
    include(shiftstate,ss_repeat);
   end;
   key1:= winkeytokey(wparam,lparam,shiftstate);
   if key1 = key_escape then begin
    escapepressed:= true;
   end;
    kbuffer:='';

  if  eventlist.count>0
      then begin
      if  ((key1=key_unknown)

        and  (charbuffer<>'') and (tkeyevent( eventlist[eventlist.count-1]).fkey=key_none) )
        then
       begin

         for ki:= 0   to  eventlist.count-1
       do
       begin
         kbuffer:=kbuffer+tkeyevent( eventlist[ki]).fchars;
       end;
        //  WriteLog('wm_keydown'+kbuffer);
        //  WriteLog('wm_keydown'+charbuffer);
         // WriteLog('key nb'+inttostr(ord(key1)));
         end;

       end;
          if charbuffer<>kbuffer
           then
           begin   eventlist.add(tkeyevent.create(ahwnd,false,key1,key1,shiftstate,
                                    charbuffer,timestamp));

              end;
          charbuffer:= '';
    if (shiftstate = []) and (key1 = key_f10) then begin
    goto nodefwindowproclab; //no windows menu activation
   end;

**Comment by fredvs** [comment]
OK, I will study your code, many thanks.

Did you try it with different version of Windows, on different machines? 
Did you try it on Linux/Kylin/Deepin?

**Comment by liuzg2** [comment]
yes   it is me  
and sorry  for my  pool  english

**Comment by liuzg2** [comment]
not yet  
may be  tomarrow

**Comment by liuzg2** [comment]
linux  kylin  deepin  
sorry   ,  i  just have  windows   7    xp

**Comment by liuzg2** [comment]
var   ki :smallint;
 kbuffer:msestring;

**Comment by fredvs** [comment]
> yes it is me

Ha perfect, I sent you a invitation to become member of mse-org team.

> sorry , i just have windows 7 xp
OK.

Thanks.

**Comment by liuzg2** [comment]
oh,   thanks for you   believe!
and how   ?  where can i see

**Comment by liuzg2** [comment]
yes  got it

**Comment by fredvs** [comment]
Hello liuzg2.

> and how ? where can i see

You will receive a email (or go to https://github.com/liuzg2).
It will ask f you accept the invitation.

When you are ready with your fixes, please sent it here as attachment if it s different that the one you give n mes-org forum(must be zipped).

And if you want a other day I will show you how to do a pull-request.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

Here how to do:

First do a fork of mse-org:
https://guides.github.com/activities/forking/

To resume:

First install git for Windows:
https://git-scm.com/download/win

Then:
- Go to https://github.com/mse-org/mseide-msegui and click on button "Fork".

- In console, create a directory (for example "mygits" and go inside that diretory (with `cd c:\mygits`) 

- Clone mseide-msegui into your "mygits" directory with:
   `git.exe clone https://github.com/mse-org/mseide-msegui`

- Go in c:\mygits\mseide-msegui (with `cd c:\mygits\mseide-msegui`) and do:
   (This must be done only once).
   `git.exe init`
  
-  Do the modifs in code needed with your favorite editor.

- Apply your changes with git:
  `cd c:\mygits\mseide-msegui`
  `git.exe add --all`
  `git.exe commit --all`
  ` git.exe push  https://github.com/liuzg2/mseide-msegui`

- Do a pull request: go to https://github.com/liuzg2/mseide-msegui and click on "Pull-request"

I hope it helps.

Fre;D

**Comment by fredvs** [comment]
Hello liuzg2.

I did commit your change: d423520  
Many thanks for this.

Fre;D
