### ISSUE TITLE
Import from trd uses wrong NT flags

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#30]
![Screenshot_20190326_002057](https://user-images.githubusercontent.com/2681872/54962604-86ee2500-4f76-11e9-8df3-0171cee6a81b.png)

**Comment by fredvs** [comment]
Still problems with last commits?

**Comment by glixx** [comment]
Yes, not fixed

**Comment by fredvs** [comment]
Here result with last commit:

Importing from `trd`:

![import_trd](https://user-images.githubusercontent.com/3421249/55188605-1b859c80-519c-11e9-975a-86e18e6e3189.png)

Importing from `po`:

![import_po](https://user-images.githubusercontent.com/3421249/55188652-2fc99980-519c-11e9-9f3c-1549ca6f7f5c.png)

Importing from `po-context`:

![import_pocontext](https://user-images.githubusercontent.com/3421249/55188735-55ef3980-519c-11e9-8247-ceee11b15fb4.png)

And here re-loading a project to prove that context is working:

![trd_context](https://user-images.githubusercontent.com/3421249/55188822-833be780-519c-11e9-9f33-5cfae7a9d2c9.png)

**Comment by glixx** [comment]
Not fixed.
