### ISSUE TITLE
NT=true always

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#31]
They must not have NT flags:
![Screenshot_20190326_061253](https://user-images.githubusercontent.com/2681872/54975648-d3525880-4fa8-11e9-9eb9-034a9370c048.png)
These strings have NT flag always because same strings have NT flag.

**Comment by fredvs** [comment]
Huh, like explained before, now the search is done by value of the original word, not by name of component.
So, how to do it?

**Comment by fredvs** [comment]
Imho, to not make things impossible to fix and to avoid problems, here what I propose:

Each root-word to translate has a unique translation and cannot be assigned for different translation, like it was before, when the search was by component name and not by word to translate (like it is now).

So in your example, because the new search by word is case-sensitive, you should use for example:

`comment`
`Comment`
`comment:`
`Comment:`
....

And assign the translation you want for each "comment"

**Comment by fredvs** [comment]
Also I would propose to avoid the most possible the use of that characters  `"`  `;` `;` 
There is now a workaround if those character are used, but better not use it.
The same for `<` `>` if you want use `transifex`.

**Comment by glixx** [comment]
Search should work by root value and component name if we have component name. So always except msgid of po/pot files without context. In other cases we have component name.

**Comment by fredvs** [comment]
> Search should work by root value and component name if we have component name. So always except msgid of po/pot files without context. In other cases we have component name.

Yes but there are some bemol.
Do you remember the menu-item bug when inserting a item?
If you persist to want search by component name it will never work because the component name in list is a number.

**Comment by glixx** [comment]
This part is total for all items of list:
![Screenshot_20190326_232122](https://user-images.githubusercontent.com/2681872/55039990-8bc6dd80-5037-11e9-96f0-b02d176a754a.png)

**Comment by fredvs** [comment]
Imagine:
 `mainfo.c.strings.data.5:.value = data5`
`mainfo.c.strings.data.6:.value = data6`
`mainfo.c.strings.data.7:.value = data7`

Now insert a item after `data.5`

The new value will be:
`mainfo.c.strings.data.5:.value = data5`
`mainfo.c.strings.data.6:.value = newdata`
`mainfo.c.strings.data.7:.value = data6`

`data7:value` has changed!

**Comment by glixx** [comment]
Yes. But root value was changed, not in trd file. Reading trd file by part of component name and value will restore saved translations.

**Comment by fredvs** [comment]
> Reading trd file by part of component name and value will restore saved translations.

Sorry but I am lost, if you have changed the order in the list, even without adding a new item, how can you do if you read only part of the component name.

Maybe you want to explain that for each list-component the search must be by value-text and for all the others by components-name? 
If yes, it will not change a lot from actual code (but will make all more complicated)

Could you show me the algorithm that you want to use, for example if the order of menu-items has changed (without adding a new item) ?

**Comment by fredvs** [comment]
Is your `NT=true always` problem fixed with last commits?

**Comment by fredvs** [comment]
OK, chief, you win.
In last commit it works like that for search:

Each value-txt of the mfm is compared with value-txt of trd.



```
while not node.eof do begin
  valuetrans := '';
   while not trd.eof do begin
     If (node.value = trd.value) then begin
        valuetrans := trd.valuetrans;
        if (node.name = trd.name) then exit;
      end;
   end;

 if  valuetrans <> '' then grid.value := valuetrans
    else grid.value := node.value;
```

**Comment by glixx** [comment]
> Sorry but I am lost, if you have changed the order in the list, even without adding a new item, how can you do if you read only part of the component name.

All items of list are unique.
For lists only needs to read part of component name like mainfo.c.strings and if trd file has  same mainfo.c.strings then check them value by value and take translations from trd file.

> Maybe you want to explain that for each list-component the search must be by value-text and for all the others by components-name?

For all others by components-name, but for lists by part of components-name.

> Could you show me the algorithm that you want to use, for example if the order of menu-items has changed (without adding a new item) ?

Find in trd file by part of component name same value and if it was translated use it.

> Each value-txt of the mfm is compared with value-txt of trd.

All strings are context depended. All search must be by context. Contex is component name or for lists part of component name.

Your alghorith uses random translated string, do not use context.

**Comment by glixx** [comment]
https://github.com/mse-org/mseide-msegui/issues/33
trd file must be parced by component name for NT restoration.

**Comment by glixx** [comment]
https://github.com/mse-org/mseide-msegui/issues/31#issuecomment-477275896
is ok if we go by way do not use context.

**Comment by glixx** [comment]
Still not fixed.
