### ISSUE TITLE
iactivatorclient vs. isqlpropertyeditor - different opinions about setactive method

### ISSUE THREAD

**Issue by marsupilami79** [mse-org/mseide-msegui#31]
While making Zeos 7.2 compile with MSEIDE + MSEGUI again, I had to make a small modification to msezeos.pas because iactivatorclient and isqlpropertyeditor have different opinions about the signature of the setactive procedure. Maybe it is possible to make them have the same opinion - I didn't dive in there.

**Comment by marsupilami79** [comment]
Added a pull request that shows my modifications: #32

**Comment by fredvs** [comment]
Hello.

Personally I never used Zeos so I dont have any idea.
I will study your pull request deeply.

**Comment by fredvs** [comment]
> because iactivatorclient and isqlpropertyeditor have different opinions about the signature of the setactive procedure.

Please, could you give more detail about the problem, are you using a MSE widget and witch one?

**Comment by fredvs** [comment]
OK, your pull request is merged.
Many thanks.

Fre;D

**Comment by fredvs** [comment]
Hello.

Maybe this has nothing to do with the problem but there is this in the _readme.md_:

> ZeosLib
> 
> In order to install the Zeos components add the path to the Zeos source to 'Project'-'Options'-'Make'-'Directories' and compile the IDE with -dmse_with_zeoslib -dMSEgui. There is a predefined IDE project apps/ide/mseide_zeos.prj, update 'Project'- 'Options'-'Macros' according to your installation.

**Comment by marsupilami79** [comment]
Hello :)

I think, this is what I did. I opened mseide_zeos.prj, added the Zeos source path and tried to compile it. Then I fixed compilation errors in [Subversion r7617](https://sourceforge.net/p/zeoslib/code-0/7617/) / GIT commit [8714b3b](https://github.com/marsupilami79/zeoslib/commit/8714b3bdedb00a9cc575d0887e09aad9a76ddcd0).
But I also had to change msezeos.pas, which isn't part of the Zeos project. Hence this issue. Maybe it is possible to have both interfaces (iactivatorclient and isqlpropertyeditor) use the same signature for the setactive method. Either `procedure setactive(avalue: Boolean)` or `procedure setactive(const avalue: Boolean)`. Currently one of the interfaces uses the version including a `const` for `avalue` whereas the other interface does not use `const` for `avalue`.
Since I don't use MSEIDE at all, I don't know what these interfaces do and how to unify these interfaces.

Best regards,

Jan

**Comment by fredvs** [comment]
Hello.

> Maybe it is possible to have both interfaces (iactivatorclient and isqlpropertyeditor) use the same signature for the setactive method. 

OK, I have to jump into this because _Zeos_ is totally new for me.
I will do it asap and write you later.

Many thanks for this.

Fre;D

**Comment by fredvs** [comment]
Hello.

I did follow the _msegui-readme.md_ and have success to build _mseide_ with _Zeos_ components.
But I needed to import your github-source of _Zeos_ with your last commit to make it work.

Maybe it would be easier to add a _zeos_ directory in _msegui_ project with all the needed files and add by default the _zeos_ msegui-components in _mseide_.

What do you think?

Fre,D

**Comment by fredvs** [comment]
Hello.

The Zeos demo in mseuniverse works like charm!

![mse_zeos](https://user-images.githubusercontent.com/3421249/126917523-54923b19-d2ee-4038-b6ca-e03757ef09db.png)

I will ask in mse mailing list if they agree to have zeos components in mse-components-palette by default.

Thanks again for your work.

Fre;D

**Comment by fredvs** [comment]
![mse_zeos2](https://user-images.githubusercontent.com/3421249/126918053-d6e7a8d4-0b86-4d43-87b8-55602d65d6a3.png)

**Comment by fredvs** [comment]
Added Zeos (working) demo in mseuniverse:
https://github.com/mse-org/mseuniverse/commit/f67c2357026625748c5e8f873750ad0c70933b09

**Comment by fredvs** [comment]
Added ZeosLib components by default  in MSEide and ZeosLib source in last commit https://github.com/mse-org/mseide-msegui/commit/ab9ee152ef8537004b22bf48734c7c24c264cbd1

**Comment by marsupilami79** [comment]
Hello Fre;D

> Maybe it would be easier to add a _zeos_ directory in _msegui_ project with all the needed files and add by default the _zeos_ msegui-components in _mseide_.
> 
> What do you think?

The question is, how will new versions of Zeos get to mseide? Should I create an issue at these times? Also we plan to release a new version of Zeos which will have some new components. I assume that msezeos.pas would have to be extended then?

Best regards,

Jan

**Comment by fredvs** [comment]
Hello Jan.

> The question is, how will new versions of Zeos get to mseide?

At the moment, the _readme.md_ was updated with this:

> ZeosLib
> 
> Since msegui commit fbbaa979b, ZeosLib components are included in mseide by default. Also last stable source are included in /mseide-msegui/lib/common/mzeoslib/.
> 
> If you want to use other ZeosLib source, you need to delete directory /mseide-msegui/lib/common/mzeoslib/. Then add the path to the ZeosLib source to 'Project'-'Options'-'Make'-'Directories' and compile your applicatio with '-dMSEgui'.
> 
> If you want to recompile the IDE with new ZeosLib source, add parameter '-dmse_with_zeoslib -dMSEgui'. >There is a predefined IDE project apps/ide/mseide_zeos.prj, update 'Project'- 'Options'-'Macros' according to your installation.

There was only one thing added in _Zeos.inc_ :
`{$DEFINE MSEgui}`

So people dont have to add anything to compile a _ZeosLib_ application.
I agree it is not perfect, but there in _msegui_ mailing list people prefer to have something "out-of-the-box".

> Also we plan to release a new version of Zeos which will have some new components. I assume that msezeos.pas would have to be extended then?

Yes, certainly.
But then maybe it could have conflict if people uses a older version of _ZeosLib_.

You see it is not evident what solution will be the best.
But I am totally open to find the most reasonable.

Fre;D

**Comment by fredvs** [comment]
Re-hello Jan.

> I assume that _msezeos.pas_ would have to be extended then?

It seems also that Martin added custom _Zeos_ component.
I dont see the equivalent of _tmseZgraphicfield_ in the Zeos-Lazarus palette.

![mse_zeos3](https://user-images.githubusercontent.com/3421249/127145488-d781ac5c-ef97-429a-a73a-9fac56902292.png)

**Comment by marsupilami79** [comment]
Hello Fre;D

> Yes, certainly.
> But then maybe it could have conflict if people uses a older version of _ZeosLib_.

We prepared some things so people can prepare their applications for compilation with Zeos 7.2 and the upcoming Zeos 8.0. We can use the same mechanisms to have msezeos.pas be ready for both versions of Zeos.

> You see it is not evident what solution will be the best.
> But I am totally open to find the most reasonable.

I suggest, I open a new issue here, whenever we do a new release. You could integrate the new releases into mseide then?

> It seems also that Martin added custom _Zeos_ component.
> I dont see the equivalent of _tmseZgraphicfield_ in the Zeos-Lazarus palette.

I am not sure what tmsezgraphicfield does. We do have some limited support for TGraphicField on Delphi and Lazarus. Not sure if it relates to tmsezgraphicfield.

Best regards,

Jan

**Comment by fredvs** [comment]
Hello Jan.

> We prepared some things so people can prepare their applications for compilation with Zeos 7.2 and the upcoming Zeos 8.0. We can use the same mechanisms to have msezeos.pas be ready for both versions of Zeos.

Perfect.

> I suggest, I open a new issue here, whenever we do a new release. 

Excellent.

> You could integrate the new releases into mseide then?

Yes, with pleasure.

> I am not sure what tmsezgraphicfield does. We do have some limited support for TGraphicField on Delphi and Lazarus. Not sure if it relates to tmsezgraphicfield.

It gives the possibility to assign a field of mse-dbgrid as graphical. 

Thanks so much Jan to take care about MSEgui.

Fre;D
