### ISSUE TITLE
Use of  " and ,  and ; characters is bad.

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#32]
Hello.

I think that I have found the guilty of all the problems.
Take a look at original code:

```
stream.readln(str1); 
splitstringquoted(str1,ar1,'"',','); // It is the problem
```
 
Each line from the `trd` is split according the `"` and `,` found.
But if you have some `"` or `,` inside the word-data, the split is wrong.

There is a workaround (not perfect) for the `" ` but for `, ` it is quasi impossible.

So now, what are we doing, or change all `"` and `,` for something else, revert all my work to come back to initial code, add a option "Search by object or by word" ?...

I need your advices before to go deeper.

**Comment by fredvs** [comment]
In last release if word to translate or translated has `,` (virgule) inside, it will become yellow.

You will see that most of the problematics words are words with `, `(virgule).

![msei18nru7](https://user-images.githubusercontent.com/3421249/55014314-09183100-4feb-11e9-9888-d3963e6ed28c.png)

**Comment by fredvs** [comment]
I wait for your advice before to anything more.

**Comment by glixx** [comment]
Needs to parce csv, trd files better. If string starts from " it means this string contains , " or multiline. All " inside string have "" format. So just follow specification of csv.
Other way is to deprecate csv format, no one uses it for translations and use other separator for trd file like |
But I guess the first way is possible just add procedure to change string if the first symbol of string is "

**Comment by fredvs** [comment]
OK (maybe) for " but for , ?
I did test replacing all , (virgule) in value text and value translated and now all works lie charm.

The problem with the trd files of Martin is that it uses , as separator.
Really, it solves all.

**Comment by fredvs** [comment]
> Needs to parce csv, trd files better. If string starts from " it means this string contains , " or multiline. All " inside string have "" format. So just follow specification of csv.

Of course, it is done automatically at export, but I speak about " inside the value.
And it is just that the problem;

**Comment by fredvs** [comment]
> Other way is to deprecate csv format, no one uses it for translations and use other separator for trd file like

I do not see any difference in the format of the exported `csv` and the `trd`.

**Comment by fredvs** [comment]
>  use other separator for trd file like |

I vote for `|` but it will be problem for compatibilities of old `trd`.

**Comment by glixx** [comment]
If string starts from `"` it means this string can contain `,`
`"` inside string is written twice `""`

> I do not see any difference in the format of the exported csv and the trd.

trd file contains all strings, but csv only displayed strings in msei18n.

**Comment by glixx** [comment]
> I vote for | in place of , but it will be problem for compatibilities of old trd.

And it does not follow csv format.

**Comment by fredvs** [comment]
> trd file contains all strings, but csv only displayed strings in msei18n.

I was talking about the format used for delimiters.

**Comment by fredvs** [comment]
> And it does not follow csv format.

Does csv format use` ,` ?

**Comment by fredvs** [comment]
With the version of msei18n of test that I have here (replacing all `,` ) I did add option at export:
"Export only root value" as txt files.

Then with Google translate, imported that file for translation and save that translation in a new file.
After that I imported in msei8n the rootvalue.txt merged with translated.txt.

Boom, out of the box, here in French I have quasi nothing to correct.
It takes +- 45 seconds.

**Comment by glixx** [comment]
> Does csv format use , ?

Yes. It is default.

Where is problem of reading trd file? Does it read only part of string before `,` ?

**Comment by fredvs** [comment]
Where is problem of reading trd file? Does it read only part of string before , ?

Yes, you get it, it does the separation of the fields according with the` ,`
If it find a  , in a text, it takes it as sepàrator,

**Comment by fredvs** [comment]
Ooops, in previous post about Google translate I was talking about `mseide` of course (+- 1400 words)

**Comment by fredvs** [comment]
> Yes. It is default.

One reason more to not use it inside data.

**Comment by glixx** [comment]
I checked trd files, we never use `;`
So let's change separator on `;` instead of `,`

**Comment by fredvs** [comment]
> I checked trd and csv files, we never use `;`
> So let's change separator on `;` instead of `,`

OK, chief but it will break compatibility with old `trd`.

**Comment by fredvs** [comment]
(For me it is not really a problem, I never used msei18n before)

**Comment by glixx** [comment]
Yes, but msei18n is too buggy, needs to rewrite it.

**Comment by fredvs** [comment]
OK, lets do it.

**Comment by fredvs** [comment]
Huh, I am not sure it will be the best solution.
Because it uses the same separator as the separator of mse nodes.
All msegui should be rewrite.

I will try to find a work around to still use the` ,` as separator.

**Comment by glixx** [comment]
> I will try to find a work around to still use the , as separator.

OK

**Comment by glixx** [comment]
Workaround:
Space follows after `,` in text, but no space after separator.

1) Some strings to fix: add space after `,`
`COMPILER, DEBUGGER, EXEEXT,TARGET,TARGETOSDIR`
->
`COMPILER, DEBUGGER, EXEEXT, TARGET, TARGETOSDIR`
etc.

2) change combination `,` and space on other never usable combination.

3) change our combination back on `,` + space.

**Comment by glixx** [comment]
> Some strings to fix: add space after ,
COMPILER, DEBUGGER, EXEEXT,TARGET,TARGETOSDIR
->
COMPILER, DEBUGGER, EXEEXT, TARGET, TARGETOSDIR
etc.

Done

**Comment by fredvs** [comment]
Fixed missing translated text (I hope).
Now the row become yellow if some `<` `>` are used.
Added too export options.

Included the Russian `trd` that I use (all found).
[i18n_mseide_ru.trd.zip](https://github.com/mse-org/mseide-msegui/files/3011880/i18n_mseide_ru.trd.zip)

**Comment by glixx** [comment]
I don't understand why you changed all > on =. Tag problem with transifex was fixed already before. All other > are ok and do not need to yellow them.

**Comment by fredvs** [comment]
> I don't understand why you changed all > on =. Tag problem with transifex was fixed already before. All other > are ok and do not need to yellow them.

Now it is yellow if you use `<` as first character and  `>` as last.
Sorry for the `< >` I did not catch that it was only for begin and end.

**Comment by glixx** [comment]
And even <n> is ok, cause it do not need to be translated.
The main issue looks fixed.
