### ISSUE TITLE
Context or without context

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#33]
I see that using context is big problem. So I do preffer to forget about context and to implement all without context. Better to have workable msei18n without context. Context is future for developers who have skills.
So
PO/POT files are always without context.
Your alghorith of searching by random translated value is ok cause in this simple case all msgid are unique.
You need to search by context only trd file for NT restoration.

**Comment by fredvs** [comment]
Last commit has importation of PO files with context.
Test is welcome.
Good night.

**Comment by glixx** [comment]
We cannot support context. We have no developers and skills like Martin had.

**Comment by glixx** [comment]
> Last commit has importation of PO files with context.

Works ok even for the latest msgid. But this bug is still present for PO files without context.

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/7#issuecomment-477594191

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/30#issuecomment-477749412

**Comment by glixx** [comment]
I guess you would like to support both ways: context and without context. It will more difficult and you need more time.
But in this case search must be by component name or part of component name for lists.

**Comment by fredvs** [comment]
> I guess you would like to support both ways: context and without context. It will more difficult and you need more time.
> But in this case search must be by component name 

It is like it works now.

> or part of component name for lists.

Hum, maybe.

**Comment by glixx** [comment]
Ok. We go by both ways.
