### ISSUE TITLE
 Commit ee10850a of fpc 3.3.1 breaks msegui compatibility. 

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#34]
Hello.
Commit ee10850a of 17 Oct, 2021 breaks msegui compatibility.

It introduces in 64 bit OS  for **TAnsiRec** and **TUnicodeRec** new size of the reference counter ( was a **SizeInt** now it is **LongInt** ) and removed the **Dummy** var.
https://gitlab.com/freepascal.org/fpc/source/-/commit/ee10850a5793b69b19dc82b9c28342bdd0018f2e

After that commit msegui is not able to connect correctly to **ansistrings** or **widestrings** or **msestrings**.
I did spent some time to fix it but without luck.

Did try to have some light from Lazarus forum but did not help too much:
https://forum.lazarus.freepascal.org/index.php/topic,56909.msg422970.html#msg422970

Does somebody have a idea what could affect in msestring or other string that difference in the reference counter ?
What method will have impact on that change and what must be changed?

Thanks.

Fre;D

**Comment by rchastain** [comment]
Thank you for the information Fred. Interesting discussion. I will try to dive in it. It's an occasion to study the different string types of MSEgui.

**Comment by fredvs** [comment]
Hello  Roland!
Nice that you will take a look at this.

You may try, on Linux 64 bit, to compile **mseide** with last trunk of fpc 3.3.1. and run it.
Here at running, it crash before to load.

Doing the same with fpc 3.2.0 or fpc 3.2.2 is ok, **mseide** compiles and run ok.
All OK too if you use fpc 3.3.1 before that commit **ee10850a**.


Fred

**Comment by fredvs** [comment]
Hello!

EXCELLENT news: in Lazarus forum, Jonas fixed the problems.
https://forum.lazarus.freepascal.org/index.php/topic,56909.msg422970.html#msg422970

So it was committed: https://github.com/mse-org/mseide-msegui/commit/a069f4a1d9dc6a75a0f140b42ac7dca0adc8ac68

Yep, msegui is still on the road.

Fre;D

**Comment by fredvs** [comment]
Hello!

@rchastain : concerning your post on Lazarus forum:
https://forum.lazarus.freepascal.org/index.php/topic,56909.msg423450.html#msg423450

Now that all is enabled in msegui to welcome, in Linux 64 bit, string type without Dummy element, it seems to me that the mutation should be done for **stringheaderty** too.

Here is the code that I tested without any problems, compatible with fpc < 3.3.1 and fpc >= 3.3.1:

```
stringheaderty = packed record
{$ifdef hascodepage}
  CodePage: TSystemCodePage;
  ElementSize: Word;
 {$if fpc_fullversion >= 030300}  // here changed
  {$ifdef CPU64}	
    Ref         : Longint;
  {$else}
    Ref         : SizeInt;
  {$endif}
{$else}
  {$ifdef CPU64}	
    { align fields  }
	Dummy       : DWord;
  {$endif CPU64}
    Ref         : SizeInt;
{$endif}
{$endif}
   len: sizeint;
 end;
```

And also a little change here:

```
procedure tmemorystringstream.destroyasstring(out data: string);
var
 ch1: char;
begin
 data:= ''; //decref
 if size > 0 then begin
  with pstringheaderty(fmemory)^ do begin
 {$ifdef hascodepage}
   codepage:= cp_acp;
   elementsize:= 1;
  {$if fpc_fullversion < 030300} // here changed
  {$ifdef cpu64}
   dummy:= 0;
  {$endif}
  {$endif}
 {$endif}
   ref:= 1;
   len:= size;
  end;
  ch1:= #0;
  position:= size;
  writebuffer(ch1,sizeof(ch1));
  pointer(data):= memory; //pointer(ptruint(memory) + sizeof(stringheaderty));
  setpointer(nil,0);
 end
 free();
end;
```
What do you think ?
OK to commit it ?

Fre;D

**Comment by rchastain** [comment]
Hello Fred. It seems logical, but honestly I don't know.
It seems that **stringheaderty** is only used in _msestrings.pas_, and that **tmemorystringstream** class is only used in two db-related units. I am not sure that these two units are used somewhere.
On the other hand I wonder why Martin declared this type (**stringheaderty**) instead of using the types declared in FPC.
So many questions...
Have a nice day Fred.

**Comment by fredvs** [comment]
Hello Roland.

Ok commited here: https://github.com/mse-org/mseide-msegui/commit/61a1cdfb687e8c1f71b12dd38684b5035eeee296

About db related units, there is also **cwstrings.pas** that is used only by db units.
I renamed **cwstrings.pas** into **msecwstrings.pas** and changed code that used it to avoid possible conflict with the fpc **cwstrings.pas**. See commit https://github.com/mse-org/mseide-msegui/commit/e7f986dc7a0830ffbc5decc47b32ccf571728922

The one from msegui (now called **msecwstrings.pas**) has variable that fpc **cwstrings.pas** dont have.
I did light test with the db demos from mseunivere and all seems ok.

But for a true test we need verdict from Mohamed who is the king in msegui db things.

Have a perfect day Roland.
