### ISSUE TITLE
Comment field has random values

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#34]
`options"`
![Screenshot_20190328_130411](https://user-images.githubusercontent.com/2681872/55126848-52699d00-511f-11e9-8868-d461801f71f9.png)

**Comment by fredvs** [comment]
OK, I will check it.
But I am not sure the code of Martin was wrong.
I have serious doubt about `fpc`.

For example, in msei18n, main.pas,  procedure tmainfo.doread(...)
If I do (you may test)

```
var
 str1, str2, str3 :utf8String;
begin
str1 := 'somethingfirst';
str2 := 'somethingsecond';
str3 := 'somethinglast';
writeln(str1 + '|' + str2 + ';' + str3);
...
```

You will get:

`$ |sometingsecond;somethinglastsomethingfirst`

!!!!???¿¿¿

**Comment by fredvs** [comment]
Please, explain better, is it by importing, at loading, form PO, cvs, trd?

**Comment by glixx** [comment]
Mseide, loading po file with context.

**Comment by fredvs** [comment]
Should be fixed in last commit.
