### ISSUE TITLE
Wrong translation restoration

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#35]
If uses not translated string instead of translated for "&64 Bit":
"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,F,,&64 Bit,&64 Бит
"watchfo,gripopup,menu.submenu.items,18:,name",vaString,T,,&64 Bit,&64 Bit

If uses not translated string instead of translated for "ignore":
"breakpointsfo,grid,datacols.items,ignore,widgetname",vaString,T,,ignore,ignore
"projectoptionsfo,tlayouter9,tabwidget,debuggerpage,ttabwidget1,ttabpage8,exceptionsgrid,fixrows.items,0:,captions.items,0:,caption",vaString,F,,ignore,Игнор.

If uses not translated string instead of translated for "fieldname":
"mseififieldeditorfo,fields,fixrows.items,0:,captions.items,2:,caption",vaString,F,,fieldname,имя_поля
"mseififieldeditorfo,fields,datacols.items,fieldname,widgetname",vaString,T,,fieldname,fieldname

If uses not translated string instead of translated for "sourcefieldname":
"mseififieldeditorfo,fields,fixrows.items,0:,captions.items,3:,caption",vaString,F,,sourcefieldname,имя_поля_исходника
"mseififieldeditorfo,fields,datacols.items,sourcefieldname,widgetname",vaString,T,,sourcefieldname,sourcefieldname

If uses not translated string instead of translated for "datatype":
"mseififieldeditorfo,fields,fixrows.items,0:,captions.items,4:,caption",vaString,F,,datatype,тип_данных
"mseififieldeditorfo,fields,datacols.items,datatype,widgetname",vaString,T,,datatype,datatype

**Comment by glixx** [comment]
```
while not node.eof do begin
  valuetrans := '';
   while not trd.eof do begin
     If (node.value = trd.value) then begin
        valuetrans := trd.valuetrans;
        if (node.name = trd.name) then exit;
      end;
   end;

 if  valuetrans <> '' then grid.value := valuetrans
    else grid.value := node.value;
```
->
```
while not node.eof do begin
  valuetrans := '';
   while not trd.eof do begin
     If (node.value = trd.value) then begin
        if not (node.value = trd.valuetrans) then valuetrans := trd.valuetrans;
        if (node.name = trd.name) then exit;
      end;
   end;

 if  valuetrans <> '' then grid.value := valuetrans
    else grid.value := node.value;
```

**Comment by fredvs** [comment]
> if not (node.value = trd.valuetrans) then valuetrans := trd.valuetrans;

Hum ?
Ok, if you prefer.

**Comment by fredvs** [comment]
> If uses not translated string instead of translated for "fieldname":

Yes I see, but my code is more permissive than your:
```
If (node.value = trd.value) then begin
        valuetrans := trd.valuetrans;
```

This should give more chance to find a translated word than this:

```
If (node.value = trd.value) then begin
        if not (node.value = trd.valuetrans) then valuetrans := trd.valuetrans;
```

I will investigate (asap) but it is not normal, it should have the same result than po without context. 
IMHO, fpc + strings (utf and friends) is not ok.

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/30#issuecomment-477749412

**Comment by fredvs** [comment]
> If uses not translated string instead of translated for "&64 Bit":
> "watchfo,gripopup,menu.submenu.items,18:,caption",vaString,F,,&64 Bit,&64 Бит
> "watchfo,gripopup,menu.submenu.items,18:,name",vaString,T,,&64 Bit,&64 Bit

Ok, I see, it will search.

**Comment by glixx** [comment]
Needs to exclude from search if node.value = trd.valuetrans. Otherwise you found not translated value. And it's ok also to exclude of translated word = root word for some languages. You can be sure you found translated string only if it string is not equaled with root string.

**Comment by fredvs** [comment]
Aaaargh, I get it.
The name of the component is not enough

component name of first:
`watchfo,gripopup,menu.submenu.items,18:`

component name of second:
`watchfo,gripopup,menu.submenu.items,18:`

The are equal!. A other search must be done with '`caption`' and with '`name`'....

**Comment by glixx** [comment]
If you want to support of context you should implement search by component name. Component name + caption .etc.
Code above in only for files with unique msgid, they are files without context.

**Comment by fredvs** [comment]
> Needs to exclude from search if node.value = trd.valuetrans. Otherwise you found not translated value. 
OK, understood.

> And it's ok also to exclude of translated word = root word for some languages.
Not understood.

**Comment by glixx** [comment]
Some languages have translated value = root value. Even if you exclude from search `if node.value = trd.valuetrans` it will do nothing for this case.

**Comment by fredvs** [comment]
Should be fixed in last commit.

**Comment by glixx** [comment]
While you do not implement search by component name nothing can be fixed. In this case search by value is wrong way.

**Comment by fredvs** [comment]
> While you do not implement search by component name nothing can be fixed. In this case search by value is wrong way.

Are you joking?
The search search by component name is implemented sinse one week now.
How do you think po-contest works in msei18n ?

**Comment by glixx** [comment]
Seach by part of component name for lists is not implemented yet.

**Comment by fredvs** [comment]
How do you think there is 2 different names for Watchdog?
![trd_context](https://user-images.githubusercontent.com/3421249/55198562-c1de9b80-51b6-11e9-8e45-568f3862fa40.png)

**Comment by fredvs** [comment]
> Seach by part of component name for lists is not implemented yet.

Yes it is.
But the problem is in list component name is a number (as explained lot of time)..

**Comment by fredvs** [comment]
Try with last commit the "64 bit" NT problem you will see it works now.

**Comment by glixx** [comment]
Yes, they are different.

**Comment by fredvs** [comment]
> Yes, they are different.

Is it not working with a different NT than the good one?

**Comment by glixx** [comment]
> But the problem is in list component name is a number (as explained lot of time)..

But I showed you picture where part of component name for lists is ok for usage.

**Comment by fredvs** [comment]
> But I showed you picture where part of component name for lists is ok for usage.

Sorry but I work on many projects, I do not remember, is it not ok like it is now?

**Comment by glixx** [comment]
Poperntially no. All strings are context depended. So even for lists a search must be done by context. So you need to differentiate list and use part of component name. No other way to have context depended search.

**Comment by fredvs** [comment]
> No other way to have context depended search.

Yes in best world.
But in real world, if you do first a search by component name, (also if the component name is a number) and by value and if nothing has found, you do a other serach by value only, it is already very good.

Like explained, if no new item in list was inserted, all the components will be search by name + value.
But in the case of adding item, to correct the initial bug of Martin, we use now a search by value only if the number of items has changed.

**Comment by glixx** [comment]
> we use now a search by value only if the number of items has changed.

but needs to search not everywhere, but inside list only, that have changed number of items.

**Comment by fredvs** [comment]
OK, done in last commit f4ee7a2.
I

**Comment by fredvs** [comment]
No, reverted to previous commit, it did not work ok.

I fear that it will stay like it is now.

**Comment by fredvs** [comment]
By the way, I would like to see where in big project like `mseide` that gives problems.
And maybe some words could loose their translation but never give a false translation (like it was before).

**Comment by glixx** [comment]
> No, reverted to previous commit, it did not work ok.

Looks like partial revert.

**Comment by fredvs** [comment]
Yes because the filter  translated <> original is at end.

**Comment by fredvs** [comment]
> but needs to search not everywhere, but inside list only, that have changed number of items.

Done in last commit.

**Comment by glixx** [comment]
When you added "&Tools" inside list it was without regress correctly.
