### ISSUE TITLE
Use with alternative compilers/Compatible with other Pascal compilers?

### ISSUE THREAD

**Issue by 3oheicrw** [mse-org/mseide-msegui#35]
Is it possible to use with Vector Pascal Compiler?

https://sourceforge.net/projects/vectorpascalcom/

Please add support for VPC if it's possible. I don't want to have to stick with Free Pascal. Thanks.

**Comment by fredvs** [comment]
Hello 3oheicrw.

If you are talking about compile mseide and msegui source with VPC, maybe it is possible, I never try this.
I will try asap.

If you already try, please give us the result.

Thanks.

Fre;D

**Comment by 3oheicrw** [comment]
The manual.html shipped with the VPC distribution is incomplete. You should find more details in this page:

http://www.dcs.gla.ac.uk/~wpc/reports/compilers/compilerindex/manual.html

On Windows, you have to open the .bat files and replace all forward slashes with backward slashes in order for it to run. This package of MinGW included all of the tools needed apart from the JRE you have to download separately:

https://github.com/brechtsanders/winlibs_mingw/releases/download/7.5.0-7.0.0-r1/winlibs-i686-posix-dwarf-gcc-7.5.0-mingw-w64-7.0.0-r1.7z

Put the everything to PATH then you should ready to invoke vpc.bat.

As the development of VPC nowadays is mostly done on Ubuntu Linux I think it's easier to use VPC on Linux. The compiler is largely compatible with Delphi but some features are missing. It's not almost 100% Delphi compatible like Free Pascal.

**Comment by 3oheicrw** [comment]
VPC is a pretty good compiler but due to it's mostly about academic it's not widely known and used for practical and commercial purposes like Free Pascal. It has almost no libraries other than the standard libraries shipped with the compiler. Being written in Java and thus requiring a JRE to run is another drawback. But overal I think it's good compiler after I discovered it and hope it could see more widely adoption to use in practical projects.

Please note that you need at least Java 11, Java 8 will not work as he increased the Java source level compatibility to Java 11 recently.

**Comment by 3oheicrw** [comment]
If units are missing (Windows API and X11 libraries) you could try using Free Pascal's unit with VPC. I don't know if it will works or not but I think with a little of modifications most will work or even work as is without any modifications.
