### ISSUE TITLE
Skipping last string of PO file

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#36]
If PO file is without context, them after import last string of PO file was skipped.

**Comment by fredvs** [comment]
> If PO file is without context, them after import last string of PO file was skipped.

Do you mean a `po-context` file with  `context value = ''`  or a simple po (not context)?

**Comment by glixx** [comment]
simple po (not context)

**Comment by fredvs** [comment]
OK.
Huh, only to be sure, are you using last commit?

**Comment by fredvs** [comment]
Ooops, well seen.
Fixed in last commit.

**Comment by glixx** [comment]
Only the latest string was imported, nothing more.

**Comment by fredvs** [comment]
> Only the latest string was imported, nothing more.

?

**Comment by fredvs** [comment]
I will check this tomorrow.
Good night.

**Comment by fredvs** [comment]
Should be fixed with last commit.
Sorry for inconvenient

**Comment by glixx** [comment]
This bug is again.

**Comment by fredvs** [comment]
I think it is fixed now.
