### ISSUE TITLE
Update status bar after Reset

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#37]
After pressing Reset status bar does not update.

**Comment by fredvs** [comment]
Cannot reproduce.
Here it works ok.

**Comment by glixx** [comment]
Status bas changes after Refresh only.

**Comment by fredvs** [comment]
> Status bas changes after Refresh only.

When do you want it change?

**Comment by glixx** [comment]
After pressing on Reset status bar should be updated.

**Comment by fredvs** [comment]
> After pressing on Reset status bar should be updated.

But it works here!

**Comment by glixx** [comment]
I cannot confirm.

**Comment by fredvs** [comment]
It should work now.

**Comment by glixx** [comment]
No. Same bug.

**Comment by fredvs** [comment]
Please explain better, here it works.

**Comment by fredvs** [comment]
Ooops, ok, it is after "`Reset`" (and not "`Refresh`", I need new glasses).
Fixed.
