### ISSUE TITLE
msei18n: Exportation of POT/PO files.

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#38]
In last commit: exportation of different flavors of `po/pot` files.
The `po/pot` headers are in Project Option Form (`Edit` button).

You may test it by importing it after created it.

**Comment by fredvs** [comment]
Exportation of po files does not work yet for multi-lines.
It is on the way.

**Comment by fredvs** [comment]
OK, exportation of po/pot with multi-lines fixed.

Note than now `po/pot-context` the `NT` flag is added at export.
So importing a `po/pot-context` with `NT` flags -->  the `NT` state will be restored.

If `po/pot-context` has no `NT` flags, it will be ignored and no change will be done to `NT` state .

**Comment by fredvs** [comment]
Now there no more restrictions for export, you may export strings, no strings, or both, with NT or without, or all what you want.

**Comment by fredvs** [comment]
Here how to do with Google translate, easy:

To associate the translate value with the root value, export the object name deleting all `.` `,` `: ` a
It will produce a long word tat Google translate will not translate.
Then you can import that translated file comparing the object name of the node.

Example: doing this for msei18n: the exported file:

```
translation
mainfotgroupbox1nostringframecaptionvastring|no string

mainfogridfixrowsitems0captionsitems0captionvastring|Name

mainfogridfixrowsitems0captionsitems1captionvastring|Type

mainfogridfixrowsitems0captionsitems3captionvastring|Comment

mainfogridfixrowsitems0captionsitems4captionvastring|Value

mainfoflatframecaptionvastring|flat

mainfostringonlyframecaptionvastring|string only
```

Translated with Google-translate, import text file is:

```
перевод
mainfotgroupbox1nostringframecaptionvastring | без строки

mainfogridfixrowsitems0captionsitems0captionvastring | Имя

mainfogridfixrowsitems0captionsitems1captionvastring | Тип

mainfogridfixrowsitems0captionsitems3captionvastring | Комментарий

mainfogridfixrowsitems0captionsitems4captionvastring | Значение

mainfoflatframecaptionvastring | плоские

mainfostringonlyframecaptionvastring | только строка

```

This file could easy be used for importation in msei18n.

**Comment by glixx** [comment]
Will you open resulted PO/POT files by poedit to see errors of syntax?
Export into POT file without context is export of unique strings only.
For msei18n project: You exported header twice with wrong syntax.

It should be:

msgid "POT header"
msgstr ""

msgid ""
"# SOME DESCRIPTIVE TITLE.\n"
"# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER\n"
"# This file is distributed under the same license as the PACKAGE "
"package.\n"
"# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.\n"
"#\n"
"#, fuzzy\n"
"msgid \"\"\n"
"msgstr \"\"\n"
"\"Project-Id-Version: msei18n\n"
"\"\n"
"\"Report-Msgid-Bugs-To: \n"
"\"\n"
"\"POT-Creation-Date: 2019-03-04 23:54+0300\n"
"\"\n"
"\"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"\"\n"
"\"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"\"\n"
"\"Language-Team: LANGUAGE <LL@li.org>\n"
"\"\n"
"\"Language: \n"
"\"\n"
"\"MIME-Version: 1.0\n"
"\"\n"
"\"Content-Type: text/plain; charset=UTF-8\n"
"\"\n"
"\"Content-Transfer-Encoding: 8bit\n"
"\""
msgstr ""

msgid "PO header"
msgstr ""

**Comment by glixx** [comment]
It does not have sense "|F". All strings in POT/PO files are translatable and all of them are "|F".

**Comment by glixx** [comment]
Kwrite will show syntax errors even if poedit will not (poedit fixes syntax errors automatically, so if to save opened file and to open you can see difference between files):
![Screenshot_20190401_090725](https://user-images.githubusercontent.com/2681872/55296509-243bd400-5423-11e9-8c90-6e89d0fa8c26.png)

**Comment by glixx** [comment]
POT and PO header do not save in trp file.

**Comment by fredvs** [comment]
> It does not have sense "|F". All strings in POT/PO files are translatable and all of them are "|F".

Ok, removed.

**Comment by fredvs** [comment]
About not perfect export of `po`, I will study it better.

**Comment by glixx** [comment]
Needs to change all " on \" for all strings.

**Comment by glixx** [comment]
Export into PO/POT file without context is export of unique strings only. In this case if you wrote msgid once, you must not add new one.

**Comment by fredvs** [comment]
> You exported header twice.

It is normal, 1 for the header, 2 for the memo of msei18n that contains the header.
The memo should be set as 'NT'.

**Comment by fredvs** [comment]
What is the good?
In your pot file the header is this:

```

# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: mseide\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-03-27 01:03+0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.0.9\n"
```

**Comment by fredvs** [comment]
> It should be:

```
msgid "POT header"
msgstr ""

msgid ""
"# SOME DESCRIPTIVE TITLE.\n"
"# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER\n"
"# This file is distributed under the same license as the PACKAGE "
"package.\n"
"# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.\n"
"#\n"
"#, fuzzy\n"
"msgid \"\"\n"
"msgstr \"\"\n"
"\"Project-Id-Version: msei18n\n"
"\"\n"
"\"Report-Msgid-Bugs-To: \n"
"\"\n"
```

**Comment by glixx** [comment]
> 2 for the memo of msei18n that contains the header

must be "1 for the memo of msei18n that contains the header", not 2

> The memo should be set as 'NT'.

Yes. It's for testing.

**Comment by fredvs** [comment]
That is mie, what is the problem vs your po file?

```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: msei18n\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-03-04 23:54+0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
```

**Comment by fredvs** [comment]
> must be "1 for the memo of msei18n that contains the header", not 2

But there are 2 memos, 1 for the po and 1 for the pot!
Please click on the "edit" button.

**Comment by glixx** [comment]
> But there are 2 memos, 1 for the po and 1 for the pot!

Yes. But they are same. So export into POT without context is only one memo.

> That is mine, what is the problem vs your po file?

Problem is only with `"`. It should be https://github.com/mse-org/mseide-msegui/issues/38#issuecomment-478393412

**Comment by fredvs** [comment]
> But there are 2 memos, 1 for the po and 1 for the pot!

Oooops, did you see that they have the same name!
And no error at creation?
Very strange.
Ok, I will give a other name for header 2.

![doublename](https://user-images.githubusercontent.com/3421249/55368978-d8595f80-54f4-11e9-9ef1-8bff4e4636ce.png)

**Comment by fredvs** [comment]
Ooops, no, one is memopoheader and the other memopo`t`header.

So, all is normal. (imho)

**Comment by fredvs** [comment]
When you decide for the good header, I will fix it.

**Comment by glixx** [comment]
I am about values of memos. They are same but same values must not be exported into file without context.

**Comment by fredvs** [comment]
> I am about values of memos. They are same but same values must not be exported into file without context.

So, you want that for po files only 1 unique value is exported, not the same?

And for the header, please give me the one you like.

**Comment by fredvs** [comment]
> So, you want that for po files only 1 unique value is exported, not the same?

So double array ?

**Comment by fredvs** [comment]
> So double array ?

So in fact you want context for po too!

**Comment by fredvs** [comment]
Please, lets go step by step.
First, fix the header.

**Comment by glixx** [comment]
You do not understand me.
header is ok.
Format of PO/POT files without context does not allow to have same msgid! If you wrote root value once, you cannot write same again!

> So, you want that for po files only 1 unique value is exported, not the same?

It's for PO file without context. Only one root value is ok.

> So in fact you want context for po-without-context too!

No.

**Comment by fredvs** [comment]
OK.

**Comment by glixx** [comment]
For POT/PO files with context you export all root values, it works. But for POT/PO files without context only one root value is allowed.

It's wrong:

```
msgid "OK"
msgstr ""

msgid "OK"
msgstr ""
```
It's correct:
```
msgid "OK"
msgstr ""
```

**Comment by fredvs** [comment]
OK, I jump.

**Comment by fredvs** [comment]
OK, done in last commit.

**Comment by glixx** [comment]
Needs to change `"` on `\"` on export and back on import.
