### ISSUE TITLE
Cannot run program on Windows without GDB

### ISSUE THREAD

**Issue by circular17** [mse-org/mseide-msegui#4]
When trying to run the project, I get the following error on Windows:
![mse_gdb_error](https://user-images.githubusercontent.com/9092455/79064272-d26d9100-7ca7-11ea-8ddc-f5424d5554ee.png)

**Comment by rchastain** [comment]
Thank you for your interest in MSEide. Yes, it's a common issue. If I remember well, I solved it by putting the whole path to gdb.exe in MSEide settings (in the **${DEBUGGER}** field). For me, the current value is:

`/C:/FPC/3.0.4/bin/i386-win32/gdb.exe`

Hope this helps.

**Comment by fredvs** [comment]
> Yes, it's a common issue.

Hum not here on Linux, I will investigate that for Windows.
Thanks to note it.

**Comment by fredvs** [comment]
And to run application without debugger I fear that is not possible with MSEide (not sure but I did not find how to do).

Anyway if this is missing for you (like it was for me), maybe you may use ideU, it has that option.

**Comment by rchastain** [comment]
> > Yes, it's a common issue.
> 
> Hum not here on Linux, I will investigate that for Windows.
> Thanks to note it.

See this discussion for example:
https://sourceforge.net/p/mseide-msegui/mailman/message/35239549/

**Comment by fredvs** [comment]
> > > Yes, it's a common issue.
> > 
> > 
> > Hum not here on Linux, I will investigate that for Windows.
> > Thanks to note it.
> 
> See this discussion for example:
> https://sourceforge.net/p/mseide-msegui/mailman/message/35239549/

Wow, good catch!
Maybe we have to note that somewhere but nobody read the readme.txt.
Fre;D

**Comment by circular17** [comment]
Ok indeed Lazarus does not set the path. I guess I fixed it by setting the full path manually. Now when I try to run, I get another error:
`demo.pas(4,52) Fatal: Can't find unit msegui used by demo`

Maybe related to the other issue about not being able to browse the code.
