### ISSUE TITLE
Split 'tag' strings

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#4]
Some strings have format `<string>` (see POT files for full list of them), but transifex determine them like tags.
Solution: split them on several strings and concatenate them.

'<' + string + '>'

**Comment by fredvs** [comment]
Sorry, I do not understand, are you talking about importing PO files?

**Comment by glixx** [comment]
No. I'm about strings `<string>`. Transifex shows them like tags and translators do not translate tags usually.

**Comment by fredvs** [comment]
I am totally new with transiflex and po files.

**Comment by fredvs** [comment]
You mean that  `<something> `may not be in the `po` file?

Strange, and how does the others if they need to use `<something> as translated?

But maybe it would be simpler and more logical to remove all that `<>`  and in code do like you proposed:
'<' + `stringtotranslate` + '>'

**Comment by glixx** [comment]
![Screenshot_20190325_235337](https://user-images.githubusercontent.com/2681872/54961597-7176fc00-4f72-11e9-93b7-5db5afb29fda.png)
Even you translated `<disabled>` as 1, but it should be <désactivé>
So if remove from POT file < and >, then tranlator understands, that disabled is désactivé

**Comment by fredvs** [comment]
> <disabled> as 1, 

Huh, I did not catch this sorry.

**Comment by fredvs** [comment]
What do you think to change all `<something>` in mseide and msei18n code by `[something]`.

That should not generate problems any more.

**Comment by glixx** [comment]
> What do you think to change all <something> in mseide and msei18n code for strings by [something]?

Ok

**Comment by fredvs** [comment]
OK.

**Comment by fredvs** [comment]
Ok done in last commit.

Note that all `<>` used inside macros where not replaced, it should be set as `NT=true`.

**Comment by glixx** [comment]
These strings can be done by concatenation:
<filepath>
<name>,<value>{,<name>,<value>}

**Comment by fredvs** [comment]
> These strings can be done by concatenation:

Yes have seen this but not really sure that is safe to translate (maybe part of a macro).

**Comment by glixx** [comment]
No. They are console messages on --help option.

**Comment by fredvs** [comment]
OK, I will set it as []

**Comment by fredvs** [comment]
Ok, done
