### ISSUE TITLE
Different filters for export and import

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#40]
Needs to filter some items of list for import.
It does not have sense for import:
'Data exchange files without translated values' (? what to import? NT flags only?)
'POT templates files without context'
'POT templates files with context'
'POT templates files with/without context'
'TXT text files with root values only'

**Comment by fredvs** [comment]
OK but do you know how to change item list of filters by code?
I did not catch it.

**Comment by fredvs** [comment]
> It does not have sense for import:
> 'Data exchange files without translated values' (? what to import? NT flags only?)

OK, I will remove it.  Now it is not more needed for Google translate, all can be done with: 
`"TXT text files with context and word"`

**Comment by fredvs** [comment]
Done in last commit.

**Comment by glixx** [comment]
Ask in mailing list.
For import string "PO files" will be good instead of detailed string, you read them automatically.

**Comment by fredvs** [comment]
> Ask in mailing list.
> For import string "PO files" will be good instead of detailed string, you read them automatically.

Did you test the commit?
Finally I found how to do.

**Comment by fredvs** [comment]
> Done in last commit.

**Comment by glixx** [comment]
> Did you see?

Not yet. So you know how to simplify all PO files items on one "PO files" for import?

**Comment by fredvs** [comment]
> > Did you see?
> 
> Not yet. So you know how to simplify all PO files items on one item "PO files" for import?

Yes

**Comment by glixx** [comment]
Export dialog should be:
Data exchange files
Templates files without context
Templates files with context
Translation files without context
Translation files with context
Text files with context and word

Import dialog should be:
Data exchange files
Translation files
Text files with context and word
