### ISSUE TITLE
Problematic " for export PO/POT file

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#42]
Needs to change `"` on `\"` on export and back on import.

**Comment by fredvs** [comment]
I dont understand.
Are you talking abut the po header?

**Comment by glixx** [comment]
I'm about all strings. " is reserved character by po/pot.

**Comment by fredvs** [comment]
Please show me a problematic string.

**Comment by glixx** [comment]
All strings that have " must be exported with \ and ".

**Comment by glixx** [comment]
https://github.com/mse-org/mseide-msegui/issues/38#issuecomment-478394422

**Comment by glixx** [comment]
Do you want to delete "
must be exported
Do you want to delete ```\"```

**Comment by fredvs** [comment]
> Do you want to delete "
> must be exported
> Do you want to delete `\"`

Hum, strange, also for " inside the string?

**Comment by glixx** [comment]
Yes, for all " in any place of strings. This character is reserved by file format.

**Comment by fredvs** [comment]
Ok, done in last commit.

**Comment by fredvs** [comment]
I did both way: export `"` --->  `/"`, import `/"` ---> `"`
