### ISSUE TITLE
Use default header of PO/POT

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#44]
I updated mfm file, but header is still old.

**Comment by glixx** [comment]
If to open new project it uses old headers from prev. project, but not default.

**Comment by fredvs** [comment]
OK, fixed.
But for that a new window was needed: `Default header` and 2 `default memos` (po/pot).
Also was added in menu `Settings` --> `Default header.`

**Comment by glixx** [comment]
Looks wrong. If trp file has no header, then just do not use header from prev. opened project. It was reading header from wrong file.

**Comment by fredvs** [comment]
I think you do not get the problem.
What you ask is possible only if you assign a text for a memo at creation of the memo.
Once you change it, you loose the original.

It is why you need a "default".

**Comment by fredvs** [comment]
Or you want to empty the memos for new project?
Why dont you  like default demo?

**Comment by glixx** [comment]
Just to save texts in variables on creation and to use them on opening new project.
Because there is simple way, do not need to do options in gui that really are not needed.

**Comment by fredvs** [comment]
> Just to save texts in variables on creation

What text, the hard coded in memo?
Then you may never change it.

**Comment by fredvs** [comment]
The data of memo are saved in `sta` file of project, so different for each project.
The data of default demo are saved in `sta` file of the application, so te same for all projects.

**Comment by fredvs** [comment]
> do not need to do options in gui that really are not needed.

Ok, but this one is really needed.

**Comment by glixx** [comment]
Just to use global variables.

**Comment by fredvs** [comment]
Of the hard-coded text in memo?

**Comment by glixx** [comment]
Other way is to write default header in code directly.

**Comment by fredvs** [comment]
> Other way is to write default header in code directly.

My friend, it is like this now and I prefer a editable default  memo.
