### ISSUE TITLE
msei18n: New mseconst.

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#45]
Maybe now, this can be changed:

```
{$ifdef mse_i18n}
 Gettext.GetLanguageIDs(MSELang,MSEFallbackLang);// setlangconsts(MSEFallbackLang);
 If loadlangunit('i18n_'+MSEFallbackLang,true) then
   setlangconsts(MSEFallbackLang);
{$endif}   
```

into:

```
Gettext.GetLanguageIDs(MSELang,MSEFallbackLang);
setlangconsts(MSEFallbackLang);
{$ifdef mse_i18n}
loadlangunit('i18n_'+MSEFallbackLang,true);
{$endif} .
```
And maybe add a new menu for `mseide` and `msei18n`  "`Languages`" with list of all languages +
option "`Use default (en) language`"?

**Comment by fredvs** [comment]
But yes, if you do not call `loadlangunit`, all will not be translated but in that case you do not need any library.

Hum, maybe give the opportunity to use the "mseconst_xx" way in `mse` will be interesting to provide too.
But the code of `mseconst.pas`  is, for me, very complicated to understand.

Any way, msei18n is working and very good.
It gives the opportunity to not only change the language but also properties of each component, like size, color, etc...

That said, there is, imho, a big constrain: the library needed. 
And if the only change is the language, the `mseconst.pas` way (that uses compiled-units)  is enough.
The big advantage is that the language-data are inside the exe and do not need external dependencies.

A other tip would be to use  `mseconst.pas` way but take the data from a external PO file.

**Comment by fredvs** [comment]
Sorry, code of mseconst.pas is too complicated for me (and dont allow context).

There is a easier way to do.
After `form.create,` 

,use the code to convert `po` into array in msi18n and assign all object.caption using context.

The big advantage of that way is that, the code is already done for all conversion po<>form.objectname.caption

**Comment by glixx** [comment]
> Maybe now, this can be changed:

No.

> And maybe add a new menu for mseide and msei18n "Languages" with list of all languages +
option "Use default (en) language"?

Many programs do not have it. English:
`LC_ALL=C mseide`

**Comment by glixx** [comment]
We will keep localization by library (we have compiller option). But it can read PO files directly (other compiller option). By default no localization to respect Martin wishes.
But I would like to drop pas files with constants. loadlangunit will load library of PO file instead.

**Comment by glixx** [comment]
We decided to save `mseconst_*.pas`. Just to convert from PO files into `mseconst_*.pas`.

**Comment by glixx** [comment]
We have many PO files with constants now.
