### ISSUE TITLE
PO files for mseconst_xx.pas

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#46]
Maybe you may use `msgctxt` to define from what array came the word.
In `mseconst_xx.pas` there are 4 arrays of words:
`modalresulttext`, `modalresulttextnoshortcut`, `stockcaption` and the new `extendedconst`.

**Comment by fredvs** [comment]
```
#: mseconsts.pas:273  -----> complicated and depend of code
msgid "Area"
msgstr "Aire"
```

vs

```
msgctxt  "stockcaption" -----> simple and will always work
msgid "Area"
msgstr "Aire"
```

**Comment by glixx** [comment]
Needs POT file generation script. xgettext cannot.

**Comment by fredvs** [comment]
> Needs POT file generation script. xgettext cannot.

It will be done by the export tool.

and if msgctxt must be unique "stockcaption0" , "stockcaption1", "stockcaption2"

Please dont focalize too much on your needs.
People will not use a command line for their program.

Also all the mseconst_xx.pas are part of msegui and only the one complete or nearly complete should be given by mse developers.

**Comment by fredvs** [comment]
You are welcome to jump into code too.

**Comment by glixx** [comment]
> It will be done by the export tool.

ok

> Please dont focalize too much on your needs.
> People will not use a command line for their program.

I need nothing. I support mse for people.

> Also all the mseconst_xx.pas are part of msegui and only the one complete or nearly complete should be given by mse developers.

I preffer to use all of them. They never will be finished. I alway provide translations even if it has only 1 translated strings. For people important to have native language.

**Comment by glixx** [comment]
> You are welcome to jump into code too.

I do not use Pascal many years and forgot a lot.

**Comment by glixx** [comment]
> But that po must be translated into mseconst_xx.pas by mse commits only

You did not get idea. Just add all languages into langnames array (mseconsts.pas). Run script `msei18n --constants` and all `mseconsts_*.pas` will be updated or created.

**Comment by glixx** [comment]
All and Cancel are only 2 constants from different arrays. So even without msgctxt no differences to localize them.

**Comment by fredvs** [comment]
OK for no context (even I would prefer) but then update please all po files with something like:

not this:

```
#: mseconsts_en.pas:24
msgid "Delete selected row?"
msgstr ""
```

but something like:

```
msgid "Delete selected row?"
msgstr ""

```
But I would prefer:

```
msgctxt "extendedconst,1"
msgid "Delete selected row?"
msgstr ""
```

And if your favorite Gettext cannot do it, just wait that msei18n-tools do it for you.

**Comment by glixx** [comment]
Format of PO files allow comments. Just skip strings, that start from ```#``§

**Comment by glixx** [comment]
Format of PO files allows comments. Just skip strings, that start from ```#```

**Comment by fredvs** [comment]
Ok, for importing your po but for export, do you agree with?:

```
msgctxt "extendedconst,1"
msgid "Delete selected row?"
msgstr "Delete selected row?"
```

**Comment by fredvs** [comment]
Added in "Tools" --> Import from po file and export into new mseconst_xx.pas.
Note that importing extended char like `&Готово` and use it in mseconst_xx.pas is working.

Here result of importation of your Russian po file:
[mseconsts_ru.pas.zip](https://github.com/mse-org/mseide-msegui/files/3050675/mseconsts_ru.pas.zip)

Of course when you are ok with the result using "Tools", we can do console parameter too for this and for automatic multi-conversion.

**Comment by fredvs** [comment]
Added in `Tools`: Import from `mseconst_xx` and convert to `po` file.
This does not export context because not needed.

**Comment by glixx** [comment]
> Ok, for importing your po but for export, do you agree with?:

Yes

**Comment by glixx** [comment]
> This does not export context because not needed.

Will you try both with context and without context?

**Comment by fredvs** [comment]
Added "All files of directory" to convert po or mseconstxx.pas in one shot.

> Will you try both with context and without context?

Maybe first try if all is ok like now, without context.

**Comment by fredvs** [comment]
Last commit is ready to test.

**Comment by glixx** [comment]
I'll test on Monday tomorrow.

**Comment by glixx** [comment]
The latest string 'Cancel speech' was not converted.
Is it ok to use human language instead of DEC?

**Comment by fredvs** [comment]
> The latest string 'Cancel speech' was not converted.

Ok, fixed in last commit.

> Is it ok to use human language instead of DEC?

Yes, it seems ok here on Linux 64 bit.
I did not try for Windows yet.

**Comment by fredvs** [comment]
> Will you try both with context and without context?

It is possible to do it with `context` but more complicated and seems not compatible to create context files with `Gettext`, so only conversion using msei12n-tools will work..
Also there is already a kind of "context" done: at searching it looks only inside the array concerned`extendedconst`, `defmodalresulttext`, `modalresultsnoshort` or `stockcaption`, not all.

So, imho, apart to give problems, it is not really needed.

**Comment by fredvs** [comment]
Tested with Russian '`ru`' and it is ok here.

`LC_ALL=C msei18n`

**Comment by glixx** [comment]
file uzcyr is not good, it has many '' instead of English strings, but uz is ok.
Let's switch on uz instead of uzcyr.

**Comment by glixx** [comment]
Not "All directory", but "All files from directory".

**Comment by glixx** [comment]
Do not export `msgid "en"`.

**Comment by glixx** [comment]
At the moment you have no mseconsts_en to create POT file.

**Comment by glixx** [comment]
I'm not sure @ is ok for pas filename. So export mseide_sr@latin.po into mseide_srlatin.pas ?

**Comment by glixx** [comment]
> For Arabic and others right-to-left languages all translated words are on the right side of page, but I not sure it is the right way to save it.

Needs to ask in mailinglist if msegui has right-to-left support or not.

**Comment by glixx** [comment]
Do you have plans to return mseconsts_en or not?
If not I'll write script to generate POT file from mseconsts.pas

**Comment by fredvs** [comment]
> Do you have plans to return mseconsts_en or not?
> If not I'll write script to generate POT file from mseconsts.pas

Like you prefer.

**Comment by glixx** [comment]
Script is easier.
