### ISSUE TITLE
Add mseide.prj or all *.prj to .gitignore

### ISSUE THREAD

**Issue by rchastain** [mse-org/mseide-msegui#47]
Hello Fred!

The modifications of _mseide.prj_ are visible in each commit and hide the interesting parts of the commit.

We could create a _.gitignore_ in _apps/ide_ with this line: `*.prj`

or even add that line in the main _.gitignore,_ in the root directory.

What would you think about that?

Best regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

> The modifications of mseide.prj are visible in each commit and hide the interesting parts of the commit.

Yes, indeed it is boring.

> We could create a .gitignore in apps/ide with this line: *.prj

I am not expert in git at all but if you do this, would the "original" .prj not be removed after a commit + push ?

**Comment by rchastain** [comment]
No, it won't be removed, but modifications will be ignored.

**Comment by fredvs** [comment]
Ha, ok, so let's do it.

**Comment by fredvs** [comment]
And  before this, maybe take the occasion to do a clean prj, removing history of search, units edited, etc... and commit this last clean prj and after this do the git ignore.

**Comment by rchastain** [comment]
Good idea.
