### ISSUE TITLE
How to have more readable commits

### ISSUE THREAD

**Issue by rchastain** [mse-org/mseide-msegui#48]
Hello Fred (and other)!

For your information, I started to work on a new branch derived from (unfinished) version 4.6.3. I called the branch 'maint', for _maintenance_ (idea borrowed to Graeme).

https://gitlab.com/rchastain/mseide-msegui/-/commits/maint

The purpose is 1° to change only what is strictly needed to make MSEide+MSEgui compile and work with the current FPC and 2° try to keep a clean commit history.

I already made an attempt last year. This was the branch 'compat_fpc_320':

https://gitlab.com/rchastain/mseide-msegui/-/commits/compat_fpc_320

But I prefer to restart from zero.

Best regards.

Roland

**Comment by rchastain** [comment]
> 2° try to keep a clean commit history.

Which is not easy! Sometimes you don't understand why _git_ marks a whole file as changed. Maybe an issue related to line endings (Linux vs. Windows)? I believe that there is an option for that. Another point to investigate...

**Comment by rchastain** [comment]
An interesting thing in fpGUI _.gitattributes:_

```
# Set default behaviour, in case users don't have core.autocrlf set.
* text=auto
```

**Comment by graemeg** [comment]
The reason Git might mark all lines as changed could very well be related to the line endings issue (Linux vs Windows)

- https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
  Helper docs from Github
- https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration
  Official docs on that setting - see the section "Formatting and whitespace".

The Github link shows you how you can "normalize" all the files, so you have one "noizy" commit (fixing all whitespace in all files), and then after that it should work fine. I hope that helps.

Out of interest, what OS are you working on?

**Comment by rchastain** [comment]
Glad to see you here Graeme. Thank you for the very useful answer. I am working on Linux, but sometimes it can happen that I retouch a file while I am at the office, on Windows.

**Comment by fredvs** [comment]
Hello Graeme.
What a wonderful present for end of year to read you.
Hope all is ok 4 you.

Fre;D

**Comment by graemeg** [comment]
Hey Fred. :wave: - I spotted the email notification so thought I'd drop in. I've been away from Free Pascal for so long, yet I still miss it. :-)

**Comment by graemeg** [comment]
> Glad to see you here Graeme. Thank you for the very useful answer. I am working on Linux, but sometimes it can happen that I retouch a file while I am at the office, on Windows.

For when you work under Windows, make sure you have the following Git config set, before you clone your repo. That will make the files CRLF for Windows, but when you push back to Git, they will automatically be converted to LF (unix) line endings.

`$ git config --global core.autocrlf true`

The Github link I posted earlier explains it well.
