### ISSUE TITLE
Create output dir

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#49]
If directory "output" does not exist, then needs to create it.
tools/i18n/output is wrong. msei18n uses dir from which it was ran or ~ dir if to run from /usr/bin by linux_extra/msei18n
And the second: this dir can be read only.

**Comment by glixx** [comment]
But it's more correct to write output files in ~/msei18n directory and create it if does not exist.

**Comment by glixx** [comment]
Other way is choosing output dir by directorychooser dialog.

**Comment by fredvs** [comment]
In last commit "output" directory is this:
`ExtractFilePath(ParamStr(0)) + directoryseparator +'output'`

So it is the "output" sub-directory in same directory as "msei18n" executable.
Sorry but I **really do not like** to create directories by code.
This should be done by the user.

And imho, `ExtractFilePath(ParamStr(0)) + directoryseparator +'output'`
is the most easy and safe way: always the same output directory, no problems, aways work.

**Comment by glixx** [comment]
Gui is developing do not do manually job. Output directory should be exist.
The best way to have dialog to choose dir.

**Comment by fredvs** [comment]
> The best way to have dialog to choose dir.

Are you ok for have dialog to choose dir and set the default dir of the dialog as?:

`ExtractFilePath(ParamStr(0)) + directoryseparator +'output'`

**Comment by fredvs** [comment]
Added output directory widget in last commit.

**Comment by glixx** [comment]
This is not good:
```"headerfo,outputdir,controller.lastdir",vaString,F,,/home/fred/mseide-msegui/tools/i18n/output/,/home/fred/mseide-msegui/tools/i18n/output/```

Will you update strings of buttons? I changed them.
![Screenshot_20190409_012305](https://user-images.githubusercontent.com/2681872/55766910-64ccca80-5a7f-11e9-946e-f403d8eb74a7.png)

**Comment by glixx** [comment]
Better to have 777 permissions on `output` dir. But git ignores it.

**Comment by fredvs** [comment]
If you absolutely want it, I can set it by code.

**Comment by glixx** [comment]
Will you try?

**Comment by glixx** [comment]
It will not work. User has no permissions to change chmod on root owner directory for installed package.

**Comment by fredvs** [comment]
Ha yes, If you want to install msegui in /usr/share or inside /usr/.

**Comment by glixx** [comment]
If no way to change chmod on dir in sources, then only home dir is good for export.

**Comment by fredvs** [comment]
> If no way to change chmod on dir in sources, then only home dir is good for export.

OK.
Do you now the syntax to get home dir ?

**Comment by glixx** [comment]
Other way is showing error message if to try to export into read only dir.

**Comment by glixx** [comment]
> Other way is showing error message if to try to export into read only dir.

Less changes in code, just add error message.

**Comment by glixx** [comment]
```chmod 444 output``
Result:
error message is present, but paneldone has always "Working..." state.

**Comment by glixx** [comment]
Continued https://github.com/mse-org/mseide-msegui/issues/65
