### ISSUE TITLE
MSEi18n tool does not show all rows

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#5]
![screenshot_20190306_231418](https://user-images.githubusercontent.com/2681872/53920628-d67bb800-407e-11e9-9177-15dc16459f8a.png)
It cannot be scrolled below and it has not usable rigth part.

**Comment by fredvs** [comment]
OK, I will take a look,

**Comment by glixx** [comment]
It's only in localized mode.

**Comment by fredvs** [comment]
Sorry for one again a question:
What is `localized mode` and how to set it?

**Comment by glixx** [comment]
Russian library was used.

**Comment by fredvs** [comment]
Is it fixed, may I close the issue?

**Comment by glixx** [comment]
Could not reproduce.
