### ISSUE TITLE
Adding an event handler

### ISSUE THREAD

**Issue by circular17** [mse-org/mseide-msegui#5]
I tried double-clicking on OnPaint to create a handler but that does not react. So I browsed the code to find the event definition.

In tmseformwidget, Ctrl-Click on the published property did not work. That would be handy here.
```
  published
   property onpaint;
```
Anyway I found the definition and typed it in the form and it appeared in the combobox of the event in the object inspector.

So I suppose all is fine, though maybe is it supposed to be easier?

**Comment by circular17** [comment]
In fact I get stuck a bit further.

I've added the onpaint event but it cannot compile:
`main.pas(14,73) Error: Identifier not found "tcanvas"`

**Comment by fredvs** [comment]
Did you see that video from previous issue?
At the end, it shows how to do with the designer:
https://github.com/mse-org/mseide-msegui/issues/3#issuecomment-612613631

**Comment by fredvs** [comment]
With the MSEdesigner, click on a object, for example a button.
Then in the object inspector, go en bas, to find "OnPaint" event.

On the right column, write something as name then press Enter.
MSE will autocratically generate the code in your source, just add all what you need inside "begin and "end".

![Capture d’écran_2020-04-13_01-26-28](https://user-images.githubusercontent.com/3421249/79082439-4babc900-7d26-11ea-9916-1c06377347e1.png)

**Comment by circular17** [comment]
Yep thanks. I also saw how you did in the video. Ok so that's fine. I just need to learn a bit.

Though afterwards, I still get the error:
`main.pas(14,73) Error: Identifier not found "tcanvas"`

**Comment by circular17** [comment]
Ok I've fixed it by adding msegraphics in uses clause.

Though I don't have code completion for it.

**Comment by fredvs** [comment]
OK, I just arrive to say it:
Add msegraphics in uses clause.

**Comment by fredvs** [comment]
> Though I don't have code completion for it.

For example if you have

```
var
cnavas : Tcanvas;
```

If you Ctrl+Click on Tcanvas, it should jump into declaration of Tcanvas in msegraphics.pas.

Does it not work for you?
Here it works.

**Comment by circular17** [comment]
Ok I finally got something:
![mse_canvas_line](https://user-images.githubusercontent.com/9092455/79082668-25872880-7d28-11ea-8c8d-e9acb853e21c.png)
```
uses ..., msegraphics, msegraphutils;
procedure tmainfo.handleonpaint(const sender: twidget; const acanvas: tcanvas);
begin
  acanvas.drawline(makepoint(0,0), makepoint(clientwidth,clientheight),cl_black);
end;
```

**Comment by fredvs** [comment]
> Though I don't have code completion for it.

If you use IdeU (sorry) there is.
Click on the lamp icon, write some code and after a ".", a list will appear.

**Comment by fredvs** [comment]
> Ok I finally got something:
> ![mse_canvas_line](https://user-images.githubusercontent.com/9092455/79082668-25872880-7d28-11ea-8c8d-e9acb853e21c.png)
> 
> ```
> uses ..., msegraphics, msegraphutils;
> procedure tmainfo.handleonpaint(const sender: twidget; const acanvas: tcanvas);
> begin
>   acanvas.drawline(makepoint(0,0), makepoint(clientwidth,clientheight),cl_black);
> end;
> ```

Ho, you are very fast, yes, you are inside it.
Congratulation.

**Comment by circular17** [comment]
> If you Ctrl+Click on Tcanvas, it should jump into declaration of Tcanvas in msegraphics.pas.
> 
> Does it not work for you?
> Here it works.
Yes, after adding msegraphics to the uses clause, this works.

But Ctrl-Space after `acanvas.` does not propose method names.

**Comment by circular17** [comment]
> If you use IdeU (sorry) there is.
> Click on the lamp icon, write some code and after a ".", a list will appear.

I am using it.

**Comment by circular17** [comment]
That completion thing is a new topic.

For this topic, adding the event works, but it would be better if it would add unit in uses clause.

**Comment by fredvs** [comment]
> if it would add unit in uses clause.

Hum, how did you do?
With the MSEdesigner it should add the needed units.
Could you explain how you did so I may try?

**Comment by circular17** [comment]
Well as you explained: I went to the `onpaint` event in the object inspector and typed in a name for the method.

**Comment by fredvs** [comment]
Ha, maybe I see, did you use a simple widget, not a graphic one?
It is possible that when you add a simple widget, it only add the needed unit for the widget.

And if you jump inside Tcanvas of the widget, you need to manually add some units.
It is totally possible because the policy of Martin was to load only what is needed.

I will check that.

PS: I did not note that because nearly all my app use msegraphics.

**Comment by circular17** [comment]
Indeed, I was trying to access the form canvas.

I am going to sleep now. See you soon.

**Comment by fredvs** [comment]
Yes, indeed, if you create project with a empty form, it will be that:

```
uses
 mseclasses,main;
```

But it you add a button, then it will be this:

```
uses
 msetypes,mseglob,mseguiglob,mseguiintf,mseapplication,msestat,msemenus,msegui,
 msegraphics,msegraphutils,mseevent,mseclasses,msewidgets,mseforms,
  msesimplewidgets;
```

Good night my ami.

Fre;D

**Comment by fredvs** [comment]
May we close this?

**Comment by circular17** [comment]
Regarding the method how to create an event, I had my answer. Maybe if we double click in the field, to show a message saying to type in the name of the method we want and Press Enter?

There is still the thing about msegraphics not being added when adding an onpaint event.

**Comment by fredvs** [comment]
> Maybe if we double click in the field, to show a message saying to type in the name of the method we want and Press Enter?

If you double click in the field and if the field is already filled, you will jump into the method assigned.

Maybe a hint panel with some explanation?

![Sans titre](https://user-images.githubusercontent.com/3421249/81184346-98469500-8fb0-11ea-9bb3-3b74287498b1.png)

> There is still the thing about msegraphics not being added when adding an onpaint event.

Hum, ok, I will check this asap.

**Comment by circular17** [comment]
Yeah a hint will do.

**Comment by fredvs** [comment]
> Yeah a hint will do.

OK, done in commit 0b5a6a0.

**Comment by fredvs** [comment]
> There is still the thing about msegraphics not being added when adding an onpaint event.


Added in commit 220114e msegraphics and msegraphutils when creating a new project.

**Comment by circular17** [comment]
Ok that's a way to fix the problem.
