### ISSUE TITLE
Multiline import from txt

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#50]
As you can see it added empty string in wrong place:
![Screenshot_20190408_033400](https://user-images.githubusercontent.com/2681872/55697094-80c16500-59c8-11e9-9a73-7ae4f6e3c2e9.png)

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/47#issuecomment-480785023

**Comment by glixx** [comment]
This bug if to import even not translated txt file.

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/47#issuecomment-480785023
