### ISSUE TITLE
Loosing end of string

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#52]
I just opened apps/ide/lang_en/
![Screenshot_20190408_035324](https://user-images.githubusercontent.com/2681872/55697671-0fcf7c80-59cb-11e9-8714-f660ec69d51b.png)

**Comment by fredvs** [comment]
I do not understand.
What about to create a new lang_en that is working, like for other language?

**Comment by glixx** [comment]
> What about to create a new lang_en that is working, like for other language?

Yes. Move constants from mseconsts.pas into mseconsts_en.pas.

**Comment by glixx** [comment]
This bug is about loosing end parts of strings.
It should be "Console" for example, but on screenshot you can see "Conso".

**Comment by fredvs** [comment]
> This bug is about loosing end parts of strings.
> It should be "Console" for example, but on screenshot you can see "Conso".

Yes, that I understand.
But is it also with new created mseconsts_en.pas?

**Comment by fredvs** [comment]
> This bug is about loosing end parts of strings.
> It should be "Console" for example, but on screenshot you can see "Conso".

OK, understand and have found the problem.
Should be fixed in last commit:  c906daf .
