### ISSUE TITLE
Loosing NT flag

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#53]
csv:
```diff
 "watchfo,gripopup,menu.submenu.items,17:,caption",vaString,F,,&32 Bit,&32 Bit
-"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,F,,&64 Bit,&64 Bit
 "watchfo,gripopup,menu.submenu.items,20:,caption",vaString,F,,&Reset Formats,&Reset Formats
```
trd:
```diff
 "watchfo,gripopup,menu.submenu.items,18:",vaList,F,,,
-"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,F,,&64 Bit,&64 Bit
+"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,T,,&64 Bit,&64 Bit
 "watchfo,gripopup,menu.submenu.items,18:,name",vaString,T,,&64 Bit,
```

**Comment by fredvs** [comment]
Seems a error in your `trd`: there is twice `items,18:,caption"`

Here from the "official" `/mseide-msegui/apps/ide/lang_en/i18n.trd`:

`"watchfo,gripopup,menu.submenu.items,18:",vaList,F,,,
"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,F,,&64 Bit,&64 Bit
"watchfo,gripopup,menu.submenu.items,18:,name",vaString,T,,&64 Bit,&64 Bit
"watchfo,gripopup,menu.submenu.items,18:,state",vaSet,F,,"[as_localcaption,as_localtag,as_localgroup,as_localonexecute]",
"watchfo,gripopup,menu.submenu.items,18:,options",vaSet,F,,"[mao_radiobutton,mao_shortcutcaption]",
"watchfo,gripopup,menu.submenu.items,18:,tag",vaInt8,F,,4,
`

**Comment by glixx** [comment]
They are different ```items,18:,caption``` and ```items,18:,name```

**Comment by fredvs** [comment]
Sorry but I just re-test here and NT flag is saved and at re-load it is ok, lie when saved.

**Comment by fredvs** [comment]
I did test with csv too, I do not see the problem.

**Comment by fredvs** [comment]
Could t be possible to do the tests with msei18n project?

Because I ave only a slow netbook and it takes time to load + refresh a big project like mseide.

**Comment by glixx** [comment]
This problem is for mseide only.

**Comment by fredvs** [comment]
> They are different `items,18:,caption` and `items,18:,name`

Sorry bt one more time I do not understand, in your trp:

```
`"watchfo,gripopup,menu.submenu.items,18:,caption",`vaString,F,,&64 Bit,&64 Bit
"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,T,,&64 Bit,&64 Bit

```

The node: `"watchfo,gripopup,menu.submenu.items,18:,caption" ` may not be 2 times the same.

**Comment by fredvs** [comment]
Here the `trd`  of `mseide` with import of Russian `po` file with context:

[i18n.trd_ru.zip](https://github.com/mse-org/mseide-msegui/files/3056475/i18n.trd_ru.zip)

**Comment by glixx** [comment]
trd file has only one line:
`"watchfo,gripopup,menu.submenu.items,18:,caption",vaString,F,,&64 Bit,&64 Bit`
it has NT flag = F

it takes NT flag = T from
`"watchfo,gripopup,menu.submenu.items,18:,name",vaString,T,,&64 Bit,&64 Bit`

**Comment by fredvs** [comment]
![msei18nnose](https://user-images.githubusercontent.com/3421249/55762742-6c32aa80-5a64-11e9-846e-91ee928b398c.png)

**Comment by glixx** [comment]
Did you try English default ?:
apps/ide/lang_en/

**Comment by fredvs** [comment]
Ooops, `&8 Bit` has disappear !

;(

**Comment by fredvs** [comment]
Yes but after correct it, save it, and reload it I get this:

![msei18nnose](https://user-images.githubusercontent.com/3421249/55763364-e6642e80-5a66-11e9-94f4-3dc5e4dba519.png)

Then, ok, the original en was not ok.
But I do not see other problems

**Comment by glixx** [comment]
Why original en is not ok if it was created by msei18n yesterday?
It was NT restoration by Value, but if some strings has same Values but different NT, then restoration NT flag does not work.

**Comment by fredvs** [comment]
> then restoration NT flag does not work correctly.

Maybe.
What I know is that I played a lot to test with the `en` `trp` before to commit it.
So maybe also it was me that set it to NT=true without to reset to false.

**Comment by glixx** [comment]
Current en trd is correct, but if to open it, then string "&64 Bit" for "watchfo,gripopup,menu.submenu.items,18:,caption" moves into "NT only".

**Comment by glixx** [comment]
> What I know is that I played a lot to test with the en trp before to commit it.
So maybe also it was me that set it to NT=true without to reset to false.

Yes.
`git gui` helps to see regressions.

**Comment by fredvs** [comment]
Ha, ok.
Sorry for this.
Maybe you may commit the good one.
I will not do new commits before yours.

**Comment by glixx** [comment]
Nothing to commit. File is actual.

**Comment by fredvs** [comment]
Not the trd of mseide.

**Comment by glixx** [comment]
git gui shows no differences after export into csv for csv, trd.

**Comment by fredvs** [comment]
OK, I commit the not load project at init and  go to sleep.

Good night (or day?).
