### ISSUE TITLE
msei18n: Do not load last project at init ?

### ISSUE THREAD

**Issue by fredvs** [mse-org/mseide-msegui#54]
What do you think to not load the last project at init of program?

If my last project was big, like mseide, it takes ages to load.
I would be happy with a empty screen and choose or a project or a tool.

**Comment by glixx** [comment]
I'm agree absolutely.
When project was moved or deleted it shows error message.

**Comment by fredvs** [comment]
Ha ok, I wait for your `trd` commit, it is ready (and much more comfortable, imho)
