### ISSUE TITLE
Wrong place for default headers in Tools

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#55]
Default POT header of Tools is unused. Deprecated?

**Comment by glixx** [comment]
I don't know your plans.
I wrote tools/consts2pot.sh script.
But you can generate POT files with and without context by Tools. Of not, then it's unused.

**Comment by fredvs** [comment]
> Default POT header of Tools is unused. Deprecated?

It is used by export as POT file for projects.
In fact, imho, there must be a menu "Default text" with all the default-editables variables.

**Comment by glixx** [comment]
I'm about your new Tools.

**Comment by fredvs** [comment]
> Of not, then it's unused.

Yes, It is used by export as POT file for projects, not by tools, and it is there because not other place..

**Comment by glixx** [comment]
Your tool do not export into pot

**Comment by fredvs** [comment]
NO, it is what I try to explain.

But the widget-POT-header is used by export project into POT.

Please, read better my answers.

**Comment by glixx** [comment]
I'm about deleting:
![Screenshot_20190409_233330](https://user-images.githubusercontent.com/2681872/55841725-124fe480-5b39-11e9-8b67-206bf899c79d.png)

**Comment by fredvs** [comment]
DO NOT DELETE IT; IT IS USED BY EXPORT to PO FOR PROJECT.

And please, read my posts.

**Comment by fredvs** [comment]
OK, I go to sleep.
Goodnight.

**Comment by glixx** [comment]
But you have PO header already. POT header is not in use.

**Comment by fredvs** [comment]
It is incredible that you persist to not read my posts.
Also you reverted all my commits.

I am very, very tired.

**Comment by glixx** [comment]
I read your posts, but you have no import/export POT.

I reverted because of regression. Nothing works. msei18n is unstable today.

**Comment by fredvs** [comment]
> I read your posts, but you have no import/export POT.
> 
> I reverted because of regression. Nothing works. msei18n is unstable today.

Because you break everything.

**Comment by fredvs** [comment]
> but you have no import/export POT.

```
 if (filind = 2) then // pot + context / mix
  begin
   datastream.writeln('msgctxt "' + str1 +'"');
   
     mstr3 :=  
   utf8StringReplace(mstr3, '"', '\"', [rfReplaceAll]);
 
   if system.pos(sLineBreak,mstr3) > 0 then
   begin
    mstr3 :=  
   utf8StringReplace(mstr3, sLineBreak, '\n"' + sLineBreak + '"', [rfReplaceAll]);
     mstr3 :=  '""'+ #10#13 +  '"' +  mstr3;
     
     Delete((mstr3),system.pos(sLineBreak,mstr3),1);
     
      datastream.writeln('msgid ' + mstr3 + '"');
    end else
    begin
    datastream.writeln('msgid "' + mstr3 + '"');
    end;
    
    datastream.writeln( 'msgstr ""');
    datastream.writeln('');
   end;
```

**Comment by glixx** [comment]
You do not need header for POT file. Tool works with PO files only. So you have PO header already.
You can hide it from gui. No sense to show it.

**Comment by glixx** [comment]
I got it!
You placed default POT/PO/constants headers in wrong place of Tools.
They must be Settings->Default headers
![Screenshot_20190412_134736](https://user-images.githubusercontent.com/2681872/56011229-4a992380-5cef-11e9-8810-b4d3ddef2fda.png)

**Comment by fredvs** [comment]
That just prove that you did not read my posts.
It was explained ***many*** times, already when I did the first commit of this.
You already refused that I create a "Default header form", now I understand why: because you never read my posts!

**Comment by glixx** [comment]
No. They were in Settings before. I did not see you moved into Tools. I was sure Tools are independent and if something presents in Tools then It's for Tools. When I checked Settings today I did not see them there, they were in Tools. But I fixed location already.

**Comment by fredvs** [comment]
> No. They were in Settings before.


They was **never** in Settings.

https://github.com/mse-org/mseide-msegui/issues/44#issuecomment-479039853
