### ISSUE TITLE
Do not enable menu items if project was not loaded

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#59]
msei18n:
Disable Refresh and Reset if project was not loaded.
Do not delete or hide them, just to do not active.

**Comment by glixx** [comment]
GUI looks different if project was not loaded:
~/.mseide exists:
![Screenshot_20190410_025333](https://user-images.githubusercontent.com/2681872/55848364-4fc26b00-5b55-11e9-804c-73837b1e2007.png)

~/.mseide does not exist:
![Screenshot_20190410_025415](https://user-images.githubusercontent.com/2681872/55848377-5b159680-5b55-11e9-956b-4d1bf70a66c6.png)

**Comment by glixx** [comment]
```
procedure tmainfo.ontimerup(const sender: TObject);
begin
 workpan.visible := false;
 isloaded := true;
 importtype := -1;
end;
```
```isloaded := true``` even if nothing was loaded

**Comment by glixx** [comment]
~/.mseide does not exist now (after commit https://github.com/mse-org/mseide-msegui/commit/2852c4108450b04980369f620182e65b8caee7e9):
![Screenshot_20190411_134816](https://user-images.githubusercontent.com/2681872/55929553-e6f6f380-5c25-11e9-82b9-4277d188842e.png)

**Comment by fredvs** [comment]
Mama mia, you are in fact a terrorist, you will destroy all.
Of course it is wanted, if no project loaded, no save, no edit, etc

**Comment by glixx** [comment]
No. You hided items, but needs to disable only, do not hide.

**Comment by fredvs** [comment]
I prefer hide, too much buttons, we are lost, much better to hide.
