### ISSUE TITLE
NT flags do msei18n unstable

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#6]
"no NT" checkbox of msei18n tool does not work.

**Comment by glixx** [comment]
I catched a lot of bugs with msei18n trying to localize mselang.
It does not save some strings marked "no_NT" into file.
I just created project with all mfm files as rfk_module for all.

**Comment by fredvs** [comment]
Huh, I was waiting for the good moment to ask it.
I think it is now:

What for are `no NT` and `NT only` checkboxes? 

>  catched a lot of bugs with msei18n trying to localize mselang.

What bugs, in mselang code?

**Comment by glixx** [comment]
Free Pascal Compiler version 3.0.4 [2018/08/09] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling pot_blank.pas
pot_blank.pas(4,68) Error: Duplicate identifier "MAIN_MFM"
pot_blank.pas(4,68) Error: Duplicate identifier "main_mfm"
pot_blank.pas(4,77) Error: Duplicate identifier "MAIN_MFM"
pot_blank.pas(4,77) Error: Duplicate identifier "main_mfm"
pot_blank.pas(4,122) Error: Duplicate identifier "MAINMODULE_MFM"
pot_blank.pas(4,122) Error: Duplicate identifier "mainmodule_mfm"
pot_blank.pas(4,131) Error: Duplicate identifier "MAIN_MFM"
pot_blank.pas(4,131) Error: Duplicate identifier "main_mfm"
Compiling /usr/share/mseide-msegui/lib/common/i18n/mselanglink.pas
Compiling /usr/share/mseide-msegui/lib/common/i18n/msei18nglob.pas
msei18nglob.pas(25,1) Fatal: There were 8 errors compiling module, stopping
Fatal: Compilation aborted

**Comment by fredvs** [comment]
Sorry to ask this but what are you trying to compile, mslang.prj or  the language file with msei18n?

**Comment by glixx** [comment]
I created project using msei18n for mselang. If to check some strings to be "no NT", press make, then after closing make window some marked strings were lost. Access violation and other bugs.
Just try to create project and play with strings.

**Comment by fredvs** [comment]
Hello.

Here picture compiling mselang_i18n language file with msei18n:
![i18n_mselang](https://user-images.githubusercontent.com/3421249/53922452-ac24fd00-4074-11e9-870e-9af1974de210.png)

And here compiling mselang.prj
![prj_mselang](https://user-images.githubusercontent.com/3421249/53922467-bcd57300-4074-11e9-902c-2ed2f7d54b9a.png)

**Comment by fredvs** [comment]
> Just try to create project and play with strings.

OK, I will try this (asap).

**Comment by fredvs** [comment]
What is the signification of NT ?

**Comment by fredvs** [comment]
Not sure if important but mselang is only 32 bit (needs fpc 32 bit).
Logically, the language file must be compiled using msei18n with fpc 32 bit too.

**Comment by glixx** [comment]
I changed you commit, cause we need only en language to generate POT file.

**Comment by fredvs** [comment]
OK.

**Comment by glixx** [comment]
"NT" is flag to mark strings not translatable. Strings, that was marked as NT must not be exported into csv (and POT/PO too).

**Comment by fredvs** [comment]
Ha, ok.
Do you have still problem at compilation?

**Comment by glixx** [comment]
Yes. It creates pas file not in en dir and cannot find it.

So task is:
- create project that includes all mfm files for en only
- mark strings by NT
- export into CSV
- export into POT.

While msei18n tool has no export into POT, then I will create POT file from CSV.
Make is not mandatory for this task, but msei18n must generate CSV correctly.

**Comment by fredvs** [comment]
> Just try to create project and play with strings.

I do not find problems.
Please look at video:

[msei18n_save.mp4.zip](https://github.com/mse-org/mseide-msegui/files/2938965/msei18n_save.mp4.zip)

> Yes. It creates pas file not in en dir and cannot find it.

Sorry dont understand, what pas file?

**Comment by fredvs** [comment]
```
So task is:

create project that includes all mfm files for en only
mark strings by NT
export into CSV
export into POT.
```

Seems ok.

**Comment by fredvs** [comment]
> but msei18n must generate CSV correctly.

Is not ok?

**Comment by glixx** [comment]
Will you try the latest commit? Will you try to export into CSV, but NT first?

**Comment by fredvs** [comment]
> create project that includes all mfm files for en only

Maybe I am wrong but it seems to me that the original en is not needed.
IMHO only the extra languages and extra directory for those languages (like ru, fr,...)

**Comment by glixx** [comment]
en directory is only for resources to generate POT file and template if somebody will want to create your language by library way.

**Comment by fredvs** [comment]
Hello.

IMHO you added unused files, that are not use by mselang.
/home/fred/mselang/src/bcwriter/main.mfm
/home/fred/mselang/src/bcwriter/createabbrev/main.mfm
etc...

Only
/home/fred/mselang/src/compmoduledebug.mfm
/home/fred/mselang/src/main.mfm
/home/fred/mselang/src/patheditform.mfm

All other files that you added are demos or extra-tools

**Comment by glixx** [comment]
OK. Delete extra files. You know mselang better.

**Comment by fredvs** [comment]
Huh, maybe I have to re-order the files.
All are mselang-gui files are stored in `/src `together with files needed by the compiler that is in `/src/compiler`.
(This is the originally order of Martin).

> OK. Delete extra files. You know mselang better.

You may try, just keep the 3 first fles with menu-button "edit":
/home/fred/mselang/src/compmoduledebug.mfm
/home/fred/mselang/src/main.mfm
/home/fred/mselang/src/patheditform.mfm

**Comment by fredvs** [comment]
Hello.
Could you try with last mselang commit?
Just change in msei18n with menu-button "edit" the directories with yours (there are only 3 files).

Mabe we may use a macro for /`home/fred/mselang/src/` directory .

PS: Indeed, clicking on NT checkboxes has strange reaction.

**Comment by glixx** [comment]
I do not agree with your directory structure. I created en dir to put all templates files for en there. You do not think about installation of application and put files everythere. How to clean up for maintainer files that do not need to be installed?

**Comment by glixx** [comment]
I commited. Needs to fix msei18n tool.
I marked all strings using NT flag. Needs to press "no NT" and to export into CSV.
Right now pressing on "no NT" shows empty rows and CSV is empty too.

Your way was wrong. Your CSV file had trash and was not full. It's hard, but needs to work with each string.

**Comment by fredvs** [comment]
Hello glixx.
Sorry for my mistakes.
I need to study more msei18n.

**Comment by glixx** [comment]
Localization of mselang depends on msei18n bug, that does not allow to export resulted project into csv. Bug is wrong behavior with NT flag.

**Comment by glixx** [comment]
> Huh, maybe I have to re-order the files.
All mselang-gui files are stored in /src together with files needed by the compiler that is in /src/compiler.

src/gui has sense.

**Comment by glixx** [comment]
> I need to study more msei18n.

It's big problem. Just some people know how to use msei18n. Noone maintainer know how to support package localized by library. If somebody touches my package, then it doesn't work, segfault and needs me to fix. Needs to switch on MO files as soon as possible.

**Comment by fredvs** [comment]
Hello.

OK, the no NT and only NT problems are fixed.

But, mystery of computer, I was able to fix it changing NT with T.
Now you need to check "T" to translate (before it was reverse).

![msei18n_onlytrans](https://user-images.githubusercontent.com/3421249/53980508-c6141d80-4110-11e9-83f0-1af53ebe51e6.png)

![msei18n_notrans](https://user-images.githubusercontent.com/3421249/53980531-d3c9a300-4110-11e9-8a5d-ad8e2300aafb.png)

There is a bug somewhere if using NT (not translate) and I cannot find how to solve it. 
Is it a crime for you to use T instead of NT?

I wait for your advice before to commit anything.

Now I will attak conversion to csv (that is buggy too).

Fre;D

**Comment by glixx** [comment]
I'm ok with TR, no TR, TR only. But it will break mseide and msei18n translation projects and all project of another developers, who use NT notation. Better to debug more, but to keep NT.

**Comment by fredvs** [comment]
> Better to debug more, but to keep NT

Sorry but I did try a lot.

>  But it will break mseide and msei18n

Huh, why, only the gui interface will be different, all the rest will be the same.

**Comment by fredvs** [comment]
Of course it must not break translation projects, it was not the plan.

Only when you load  project, in place of checking the "not to translate" it checks the one "to translate".

**Comment by fredvs** [comment]
OK, you are right, I will keep NT and try to find the bug.

**Comment by fredvs** [comment]
Hello.

Did you try to enable "`string only`" ?
After test here, all seems ok when "`string only`" is enabled,

Could you confirm this?
(And is it really needed to see the no-strings?)

**Comment by fredvs** [comment]
Re-hello.

I think I get it.
There is problems with "string only"  = false and "flat" = true.

It is a problem of node.
The most easy workaround is to set "string only"  always true (and hide it).

**Comment by fredvs** [comment]
Aaaargh, no.

After deeper checks, it appears that for some projects with "no NT" = true and "string only" = true there are 0 rows.
So much more difficult to resolve if some projects are ok and others no.

OK, I will do break.

**Comment by glixx** [comment]
> Did you try to enable "string only" ?
After test here, all seems ok when "string only" is enabled,

Yes, except export into csv, cause it does not read NT flag.

> And is it really needed to see the no-strings?

Good to see.

> There is problem with "string only" = false and "flat" = true.

Maybe.

> The most easy workaround is to set "string only" always true (and hide it).

No. You will loose some translatable resources.

**Comment by glixx** [comment]
Potential problems to debug:
* empty strings
* one value string has difference with en string, so there is shift somewhere
* shifting of strings is known msei18n bug

**Comment by fredvs** [comment]
Yep, nice to read you.

Are you sure that the *.mfm files must be set as `rfk_module`?
Because settings forms .*.mfm as `rfk_resstrings` works perfectly here.
Only compmodule.mfm (is it needed for translate?) needs to be set to `rfk_module`.

That way "no NT" = true works for the (not working before)  project.

**Comment by glixx** [comment]
When we worked on localization of mseide with ivankob we found, that other modes loose some translatable strings. So we switched on rfk_module always.

**Comment by fredvs** [comment]
OK.

**Comment by fredvs** [comment]
Very strange but here the project mselang, settings forms .mfm as rfk_resstrings works perfectly (without loosing words).

**Comment by glixx** [comment]
> Very strange but here the project mselang, setting forms .mfm as rfk_resstrings, works perfectly.

No. Access violation on switching "no NT" after marking strings as NT.

**Comment by glixx** [comment]
I generated csv by workaround:

I exported all strings into mselang_i18n.csv, but with NT markers first
`cat mselang_i18n.csv |grep ",F," > new.csv`

Needs to have same result using msei18n only.

**Comment by glixx** [comment]
Just try to debug file by file and 3 together. Mselang has 3 mfm files.

**Comment by glixx** [comment]
> Huh, maybe I have to re-order the files.
All mselang-gui files are stored in /src together with files needed by the compiler that is in /src/compiler.

I started. Please finish.

**Comment by fredvs** [comment]
> Just try to debug file by file and 3 together. Mselang has 3 mfm files.

Only 2 because the last one is a datamodule: `compdebugmo` and has noting to translate.

**Comment by fredvs** [comment]
> I started.

Nice! Plese read my first commits, I am not sure for one fix.

**Comment by glixx** [comment]
> Only 2 because the last one is a datamodule: compdebugmo and has nothing to translate.

Yes. But it presents in translation project just because of future strings. Today it does not have translatable strings, but sutuation can change in future.

**Comment by fredvs** [comment]
> But it presents in translation project just because of future strings. 
Ha, ok, I will add it then.

**Comment by glixx** [comment]
> Nice! Plese read my 3 first commits, I am not sure for one fix.

I don't understand you.

**Comment by fredvs** [comment]
> Nice! Plese read my 3 first commits, I am not sure for one fix.

It is about `mselang` (if you are buzzy in it).

About `msei18n`, I am very disappointed.
I re-created a project from scratch of `mselang`, using `fk_module` and setting the NT needed and now all works perfectly.

Even with click on "no NT".

See pictures:

![msei18n_oknont](https://user-images.githubusercontent.com/3421249/54000874-6f770580-4149-11e9-8246-f17732ba6dc7.png)

![msei18n_okntonly](https://user-images.githubusercontent.com/3421249/54000881-7867d700-4149-11e9-93e2-c0dc5fa36ab1.png)

**Comment by glixx** [comment]
Commit your version, I'll test. But move into src/gui all files of mselang first.

**Comment by fredvs** [comment]
Yes, done.

Trick: if you big change, for example adding a new mfm file or new language, in "edit" --> datafile, change for a other name.
Clik on close. It will be a message that your new file do not exist.
Ignore it and click on "save".

**Comment by fredvs** [comment]
The commit was for `mesi18n`, I did not do it for `clang` yet.

**Comment by fredvs** [comment]
> But move into src/gui all files of mselang first.

Not so easy because path in code must be changed then.

**Comment by glixx** [comment]
"NT only" works correctly, but "no NT" better, but still empty.

**Comment by fredvs** [comment]
> but "no NT" better, but still empty.

Aaaaargh.
Could you, please, sent a demo with that problem.
Now i cannot reproduce it.
Thanks.

**Comment by fredvs** [comment]
With your `mselang_i18n.trp` (that has no NT-row checked) if I check some needed NT, no problem, "`no NT`" works.
So if you can sent me a demo with the problem I will (try to) debug it.
Re-thanks.

**Comment by fredvs** [comment]
Re-hello.
OK, I was able to re-have the problem.
Could you try this:
When you have the problem, ("no NT" not works), click on menu-button "edit" and choose a other name for `Datafile` field.
Example: /home/fred/mselang/src/gui/languages/en/mselang_i18n2.trd

There will be a message "File does not exist" ---> ignore it and click on "Ok".
Click on "save".
Then define the NT rows that must be enable.
It should work now.

Maybe it can give idea where s the problem and how to fix it.

**Comment by fredvs** [comment]
Hello.
Could you try with the file mselang_i18n2.trd (in attachment) with your original `mselang_i18n.trd` ?
[mselang_i18n2.trd.zip](https://github.com/mse-org/mseide-msegui/files/2946080/mselang_i18n2.trd.zip)

Thanks.

(But there are still problem when resizing a column)

**Comment by fredvs** [comment]
Hello.
I did compare your `mselang_i18n.trd` with mine `mselang_i18n2.trd`
You may see on the picture that both files are the same but in yours `notranslate` field is set to "**T**" and on mine it is set to "**F**".  
Maybe something to look around there....

![diff_trd](https://user-images.githubusercontent.com/3421249/54039927-6d9e5800-41c4-11e9-894c-fb8816239770.png)

**Comment by fredvs** [comment]
Re-hello.
I did play with resize column and "no NT".
With `mselang_i18n2.trd` no problems.
With `mselang_i18n.trd` ---> crash.

**Comment by glixx** [comment]
I reported to you about crash msei18n after resizing. It's good you reproduced.
I'll look on Monday.

**Comment by fredvs** [comment]
OK, I will try to have the crash with my `mselang_i18n2.trd`, till now no problem.
Indeed with your `mselang_i18n.trd` many crash.

**Comment by glixx** [comment]
New topic: https://github.com/mse-org/mseide-msegui/issues/12
