### ISSUE TITLE
mseide 5.10 get freezed after a second compilation 

### ISSUE THREAD

**Issue by codz01** [mse-org/mseide-msegui#69]
Hi Fred 
to reproduce :
create a console app , build it for the first time goes ok but for the second time the ide will freeze

btw i am using fpc 3.2.2 32bits

**Comment by fredvs** [comment]
Hello Codz.

What OS are you using?

**Comment by fredvs** [comment]
Re-hello Codz.

I have try with MSEide  5.10.0 for Windows 32 bit and Linux 32 bit, with "Project" "New" "From template" "console.prj" but I cannot reproduce the problem.

Can you please give more infos how you did to get the problem?

Thanks.

**Comment by fredvs** [comment]
Re-hello.

Note that the test I did for Windows was via wine on a Linux host.
I dont have a real Windows machine to test it now.
If your problems are on a Windows machine, what Windows version are you using?

**Comment by codz01** [comment]
i am using windows 7 32bits as a primary OS , and FPC 3.2.2 32bits .
i remember facing this issue while a go and i post it on msegui mailing list , i'll search for this post

**Comment by fredvs** [comment]
I remember there is a problem when not using the **-B**  (build all) fpc parameter.
But this was not freezing the app, only fpc ignoring some **{$ ifdef something}.**

**Comment by codz01** [comment]
ok i remembered  , this problem occurs only when building mseide using -O3 switch , with O2 and O1 all seems fine  
so its fpc optimizer problem , i have to check fpc trunk to see if this bug has been solved !

**Comment by fredvs** [comment]
Ha ok.

You may take a look at this: https://github.com/mse-org/mseide-msegui/discussions/60
