### ISSUE TITLE
Opening trp file on the second time

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#69]
trp file does not open on the first time, but opens on the second time.

**Comment by fredvs** [comment]
Yes and the fix was in the last commit that I could not commit because you destroyed all.
And how to fix that, it is easy, just read my posts, it is explained how to do.

**Comment by glixx** [comment]
I always read all your posts. No explaination.

**Comment by fredvs** [comment]
Fixed in last commit.
