### ISSUE TITLE
Export/import POT/PO for msei18n

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#7]
Missing export/import POT/PO for msei18n.
It can be based on CSV algorithm, that is already implemented.

**Comment by fredvs** [comment]
Yes, I will (try to) fix msei18n this week-end and then attack that.

**Comment by glixx** [comment]
And do not have duplicate msgid in POT file. Each string should be exported only once.

**Comment by glixx** [comment]
Needs to support 2 formats of POT/PO files: with and without context.

Without context:

```
# mainfo,ntonly,frame.caption
msgid "NT only"
msgstr ""
```

With context:

```
# mainfo,ntonly,frame.caption
msgctxt "mainfo,ntonly,frame.caption"
msgid "NT only"
msgstr ""
```

**Comment by fredvs** [comment]
> with and without context.

Sorry for my big ignorance but what is "context" ?

**Comment by glixx** [comment]
msgctxt is context.
For example if application has several same str0 for translation then there are 2 ways. If you need less work for translators and str0 is always same in all contexts, then you do not need msgctxt, you write str0 in POT file only once. But if you need different translations for str0, then you should use msgctxt and str0 can be present on POT file many times.
I did not use context for mseide, msei18n, mselang. Fpgui do not use context too. But developers need both formats.

**Comment by fredvs** [comment]
Ha. ok, I will study that deeper.
Write you later.

**Comment by glixx** [comment]
File dialog of export/import is list of:
* csv
* pot with context
* pot without context
* po with context
* po without context

**Comment by fredvs** [comment]
> File dialog of export/import is list of:

It would be wow + excellent.

**Comment by glixx** [comment]
This bug https://github.com/mse-org/mseide-msegui/issues/1 does not effect an export into POT file. "Value" are always ok.

**Comment by glixx** [comment]
There is 3rd type of POT/PO file: mix of msgctxt and without msgctxt

**Comment by glixx** [comment]
> File dialog of export/import is list of:
* csv
* pot with context
* pot without context
* pot with/without context
* po with context
* po with/without context
* po without context

pot with context: all strings that you have in CSV should be `msgstr "string"` in POT with msgctxt "component_name" added.
pot without context: all msgstr "string" are unique. So you should sort strings first to exclude same strings.
pot with/without context: in this case all not unique strings should be with msgctxt "component_name" added, but all other strings without msgctxt. This format is mix of 2 foregoing formats.

**Comment by fredvs** [comment]
On last commit : first shot of importation of `PO` files.
I did test with your `PO` Russian file for `mseide`.

Huh, on the 1354 rows to translate only 1 is not translated!

But there is one translation that makes me crazy:

watchfo.grid.fixrows.items.0:.captions.items.3:.hint ---> Display format.

It is a multi-lines but `D = Decimal signed` is added with `B = Binary`.

I do not understand why, all other multi-lines seems ok.

If you have a idea why, it is welcome.

**Comment by fredvs** [comment]
OK, fixed in last commits.

**Comment by glixx** [comment]
> PO translation files (*.po)

It is not enought. Full list:

* PO translation files without context (*.po)
* PO translation files with context (*.po)
* PO translation files with/without context (*.po)

And for Export only (no import from POT):

* POT translation templates files without context (*.pot)
* POT translation templates files with context (*.pot)
* POT translation templates files with/without context (*.pot)

**Comment by fredvs** [comment]
What is context?

**Comment by glixx** [comment]
msgctxt "any_string", where any_string is context, it shows that this string from this place, but not from other. Any string to understand place of string.

For example:
```
"projectoptionsfo,tlayouter9,tabwidget,ttabpage20,tlayouter6,savebu,caption",vaString,F,,Save,Сохр-ть
"actionsmo,shortcuts,actions.items,2:,dispname",vaString,F,,Save,Сохранить
```

In this case `Save` has 2 different translations, that depends on context.

So `PO translation files with context (*.po)`:

msgctxt "projectoptionsfo,tlayouter9,tabwidget,ttabpage20,tlayouter6,savebu,caption"
msgid "Save"
msgstr "Сохр-ть"

msgctxt "actionsmo,shortcuts,actions.items,2:,dispname"
msgid "Save"
msgstr "Сохранить"

**Comment by fredvs** [comment]
Ha, it exist other values than `msgid` and `msgstr` !
OK, I get it.

Now the big question, do you really think it would be better to deal with `msgctxt` (the name of object)?

**Comment by glixx** [comment]
We should support all formats. At the moment I created PO and POT files without context. Less work for translators and it was possible to merge ready translations from simular programs. It was more important. But in future better to switch on context dependenced strings when we will have good translations. Usually it takes some years to have translations. When it will be time to switch on context it will be easy to write po/pot converter from current format into context format or this task can be done by transifex just upload pot files with msgctxt and to configure transifex to fill all strings from translation memory.

**Comment by glixx** [comment]
I want to try easier way to support only:

* PO translation files with context (*.po)
* POT translation files with context (*.pot)

I need export into POT file (if you will do this task in priority):
msgctxt ""
msgid ""
msgstr ""

I hope transifex will do merging job automatically. So I need only POT files do not write them manually.
Minuses: using only translation memory of mse, not from other projects.

**Comment by glixx** [comment]
I'm not sure MSE will be ok with MO files with context.

**Comment by fredvs** [comment]
> I'm not sure MSE will be ok with MO files with context.

It will be the same problem when seeking for text in list-items.

**Comment by fredvs** [comment]
IMHO, if you want support of context for MSE, you should use different root-value like:

`mycontext`
`Mycontext`
`mycontext:`
`Mycontext:`

The only big problem I see for context is mse-string-list (like menu-list-item).
(but maybe you have a solution that I did not catch for list)

**Comment by glixx** [comment]
Transifex configured to fill strings from translation memory. So PO files should be always up to date by msgctxt. Even if msgctxt was changed, but string is present in translation memory It will be used for new msgctxt.

**Comment by glixx** [comment]
https://github.com/mse-org/mseide-msegui/issues/33
We go by way without context now. So I'll switch transifex settings back.

**Comment by fredvs** [comment]
Hello.
I do not agree.  Context will work.
And I propose a option "Use context to earch", so you may import like you want.

**Comment by glixx** [comment]
We don't need options. The first of all you must analyse po file and to determine format of file automatically.

**Comment by fredvs** [comment]
> We don't need options. The first of all you must analyse po file and to determine format of file automatically.

It is automatic now.

**Comment by glixx** [comment]
I'm about to delete:
![Screenshot_20190329_095046](https://user-images.githubusercontent.com/2681872/55200092-a5019280-51cd-11e9-9694-e7b7390c1a9f.png)

**Comment by fredvs** [comment]
Why?

I find it very useful and use.

**Comment by fredvs** [comment]
Dont delete it, I will add a menu utilities.

**Comment by glixx** [comment]
I explained before that exportation should be automatically, only select what kind of exportation you need from file dialog by selection "TXT file with root values" or "TXT file with translated values".

**Comment by glixx** [comment]
> And I propose a option "Use context to search", so you may import like you want.

Do not need options.

**Comment by fredvs** [comment]
OK, you are right, I will do it.

**Comment by fredvs** [comment]
Exportation of po/pot with and without context done.

**Comment by glixx** [comment]
There is 3rd format: with/without context.

For example for msei18n: string "&Cancel" is not unique, so it must be with context:

```
msgctxt "msememodialogfo,tlayouter1,tbutton2,caption"
msgid "&Cancel"
msgstr ""

msgctxt "settingsfo,tsplitter1,tbutton2,caption"
msgid "&Cancel"
msgstr ""
```
But string "Make command" is unique. It must be without context:

```
msgid "Make command"
msgstr ""
```

**Comment by fredvs** [comment]
> There is 3rd format: with/without context.

Yes, I k seen it but I do not know what it is, please explain.

**Comment by fredvs** [comment]
> There is 3rd format: with/without context.
> 
> For example for msei18n: string "&Cancel" is not unique, so it must be with context:
> 
> ```
> msgctxt "msememodialogfo,tlayouter1,tbutton2,caption"
> msgid "&Cancel"
> msgstr ""
> 
> msgctxt "settingsfo,tsplitter1,tbutton2,caption"
> msgid "&Cancel"
> msgstr ""
> ```
> But string "Make command" is unique. It must be without context:
> 
> ```
> msgid "Make command"
> msgstr ""
> ```

And this, is it not good?

```
msgctxt "msememodialogfo,tlayouter1,tbutton2,caption"
msgid "&Cancel"
msgstr ""

msgctxt "settingsfo,tsplitter1,tbutton2,caption"
msgid "&Cancel"
msgstr ""

msgctxt ""
msgid "Make command"
msgstr ""
```

**Comment by fredvs** [comment]
But for this, imho, msei18n should have one column more `NC` (no context).
Hum, ok, after all that battle, a little fight more.

Ok, I jump.

**Comment by fredvs** [comment]
Huh, that will take lot of work because all is indexed.

**Comment by fredvs** [comment]
Note that importing po if  msgctxt "" or msgctxt "nameofcomponent" works.
The problem is to store the context into the trd.

The easeier way would to use the "comment" column.

**Comment by glixx** [comment]
> The context serves to disambiguate messages with the same untranslated-string. It is possible to have several entries with the same untranslated-string in a PO file, provided that they each have a different context. Note that an empty context string and an absent msgctxt line do not mean the same thing. 
> https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

I guess do not support with/without context files. Just fix export of unique strings into POT file without context and problem with `"`.

**Comment by fredvs** [comment]
> I guess do not support with/without context files.

As it is now works at importation, if no `msgctxt` was found in a `po` file with context.
A easy way to store that info in `trd` is to use "Comment" column.

>  Just fix export of unique strings into POT file without context and problem with `"`.

Please, explain more, there are tons of issues,  I am lost.

**Comment by fredvs** [comment]
The rest is it working?

**Comment by glixx** [comment]
POT/PO files without context cannot have same msgid twice or more.

This is wrong:
```
msgid "&Cancel"
msgstr ""

msgid "&Cancel"
msgstr ""
```

It must be only once:
```
msgid "&Cancel"
msgstr ""

```

**Comment by glixx** [comment]
Character `"` is reserved by POT/PO files. So if your string has `"` you must change it on `\"`.

**Comment by glixx** [comment]
I guess it's enougth to have with context and without context, but not mix of them with/without context.
But if you would like to support with/without context too, then the first of all needs to sort rows on 2 arrays. 1st array is unique values, 2nd array is not unique values.

**Comment by fredvs** [comment]
> I guess it's enougth to have with context and without context, but not mix of them with/without context.
> But if you would like to support with/without context too, then the first of all needs to sort rows on 2 arrays. 1st array is unique values, 2nd array is not unique values.

Huh, after all that work, I did not resist and have done a msei18n with context.
May I do the commit of it?

**Comment by fredvs** [comment]
> But if you would like to support with/without context too, then the first of all needs to sort rows on 2 arrays. 1st array is unique values, 2nd array is not unique values.

You mean that it must have 2 columns more (I did only one).

**Comment by fredvs** [comment]
![context](https://user-images.githubusercontent.com/3421249/55366681-0be2bc80-54ea-11e9-9f5a-ae064f463cf0.png)

**Comment by glixx** [comment]
No. You do not need new NC field.
Before export sort all rows on 2 arrays by value. And after sorting export array1 into POT file and the next - array2. Order does not have matter.

**Comment by fredvs** [comment]
> No. You do not need new NC field.

Huh, are you sure ?

**Comment by fredvs** [comment]
> Before export sort all rows on 2 arrays by value. And after sorting export array1 into POT file and the next - array2. Order does not have matter.

But how to store the the info that it is mix context in the trd?

**Comment by glixx** [comment]
Needs to sort all rows by value. Unique values is array1, not unique values is array2.

> But how to store the the info that it is mix context in the trd?

We do not need it. Format is unique values do not have context, other values are going with msgctxt.

**Comment by fredvs** [comment]
> Needs to sort all rows by value. Unique values is array1, not unique values is array2.
> 
> > But how to store the the info that it is mix context in the trd?
> 
> We do not need it. Format is unique values do not have context, other values are going with msgctxt.

OK, this one I will do for next release!

**Comment by fredvs** [comment]
I still dont know if the rest is working for you.
;(

**Comment by glixx** [comment]
But implementation is too hard, because before import needs to sort on 2 arrays or 2 files again.

**Comment by fredvs** [comment]
> But implementation is too hard, because before import needs to sort on 2 arrays or 2 files again.

Not too hard but I have to finish this first and did spent lot of time yet.

**Comment by glixx** [comment]
> I still dont know if the rest is working for you.

Still not fixed issues to write POT/PO files correctly. 2 problems: with `"` and do not write msgid twice if format of file has no context.

**Comment by fredvs** [comment]
> But implementation is too hard, because before import needs to sort on 2 arrays or 2 files again.

But if you use a column "NC" all will be much more easy for export.

**Comment by fredvs** [comment]
> > I still dont know if the rest is working for you.
> 
> Still not fixed issues to write POT/PO files correctly. 2 problems: with `"` and do not write msgid twice if format of file has no context.

Only that?
Then I am happy.

**Comment by glixx** [comment]
>But if you use a column "NC" all will be much more easy for export.

We do not go easy way. GUI of msei18n must be easy, but code smart.

> Only that s bad?

I'll test after fixes.

**Comment by glixx** [comment]
Continued https://github.com/mse-org/mseide-msegui/issues/43
