### ISSUE TITLE
mse18n does not support same filenames

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#8]
Mseide has mfm files with same names, but msei18n does not accept them.
Workaround: renaming.

**Comment by fredvs** [comment]
what file in mseide has same mfm name?
IMHO, this should be fixed in mseide, not in msei18n.

**Comment by glixx** [comment]
2 files have same names:

lib/common/designutils/panelform.mfm
apps/ide/panelform.mfm

needs to rename one of them and to test if msei18n will work with them after renaming.

**Comment by fredvs** [comment]
> needs to rename one of them

IMHO it would be better to rename apps/ide/panelform.mfm because the other can be used for other application.

**Comment by glixx** [comment]
Yes. You're right.

**Comment by glixx** [comment]
@fredvs will you rename?

**Comment by fredvs** [comment]
Ok renamed ---> `panelform2`.
