### ISSUE TITLE
Extension of EXE file not consistent with ideU

### ISSUE THREAD

**Issue by circular17** [mse-org/mseide-msegui#9]
When I open a project in MSEide, if I compile I get a filename without extension, unless I add it in the "target file" field of the Make tab. But if I do that, then when I compile in ideU I get double extensions.

**Comment by fredvs** [comment]
Did you set default extension here:

![Capture d’écran_2020-04-18_19-07-56](https://user-images.githubusercontent.com/3421249/79644255-fc431e00-81a7-11ea-85d5-a4f1df307375.png)

**Comment by fredvs** [comment]
You may set target file as `mytargetfile${EXEEXT}` 

In MSEide, set default extension `${EXEEXT} = .exe`

and in ideU in Global Settings - Other- Set  `${EXEEXT} as empty`.
And in ideU project option - make - extension, set for one number for extension:

![Capture d’écran_2020-04-18_19-21-34](https://user-images.githubusercontent.com/3421249/79644547-f2bab580-81a9-11ea-96cf-9dac04207766.png)

**Comment by circular17** [comment]
Ok I understand the trick, though that's kind of complicated.

**Comment by fredvs** [comment]
> Ok I understand the trick, though that's kind of complicated.

Yes, maybe but if you use Linux, you will see how nice and easy it is to compile your project for Windows, using a true Windows FPC Windows compiler that you run using Wine emulator.

The bémol, I agree, is to be obliged to use the "Exe extension" ideU trick to do poly-compilation (not cross-compilation).

(If you want to test it with fpc-ootb,  just download the Windows version, unzip it somewhere on your Linux system, assign the fpc-ootb.exe compiler for one ideU Pascal compiler and enable Wine checkbox.)

So you may choose to compile your project for Linux or Windows, without any cross-compilation, only true native compilation.

**Comment by circular17** [comment]
I like the idea of cross-compiling that's definitely valuable.

It is just that it is confusing. Wouldn't it be possible that if you load a project from MSEide, you get the same filename by default? Or at least check if there isn't already ${EXEEXT} in the target file?

**Comment by fredvs** [comment]
MSEide and ideU use the same "Global Settings".
But usually, for convenience for poly-compil, it is easier that the ideU user set his default ${EXEEXT} 
as no extension and tune it with the extended settings in project option of the extension.

Here a project compiled for Linux 64/32, Windows 64/32 completely OOTB, only choose a different number of compilation type:

Linux 64:

![ideulin64](https://user-images.githubusercontent.com/3421249/79693399-ac795b00-826a-11ea-866e-46fa322a4d11.png)

Linux 32

![ideulin32](https://user-images.githubusercontent.com/3421249/79693407-ba2ee080-826a-11ea-86b3-5edc93fbf400.png)

Windows 32

![ideuwin32](https://user-images.githubusercontent.com/3421249/79693413-c61aa280-826a-11ea-8c62-48e52abcf2bb.png)

Windows 64:

![ideuwin64](https://user-images.githubusercontent.com/3421249/79693425-d7fc4580-826a-11ea-863e-02c3ae51b6f0.png)

**Comment by circular17** [comment]
Yep but the problem is that if we work on the same project, and the I have MSEgui and you have ideU or vice versa, we will have to update the target file name each time we share.

**Comment by fredvs** [comment]
> we will have to update the target file name each time we share.

If your project uses as target filename `myfilename${EXEEXT}`, it can be set in your extended  ideU extension option.

But ok, I will test this tonigth maybe I miss something.

**Comment by fredvs** [comment]
OK, I did try and did not find problems is you use `myproc${EXEEXT}` as target name.
Just set the macro in ideU `${EXEEXT}` as empty string.

![Capture d’écran_2020-04-21_03-13-37](https://user-images.githubusercontent.com/3421249/79814664-1f73f600-837f-11ea-9499-6489d3d7ee4a.png)

![Capture d’écran_2020-04-21_03-25-30](https://user-images.githubusercontent.com/3421249/79814953-c9538280-837f-11ea-9c8f-ab2a81cf9763.png)


![Capture d’écran_2020-04-21_03-15-27](https://user-images.githubusercontent.com/3421249/79814698-33b7f300-837f-11ea-8bb8-65d73dae32bd.png)

**Comment by circular17** [comment]
I understand but it is too complicated.

The field "targetfile" has two different meanings:

- if you open it with MSEgui it means targetfile with extension
- and with ideU it means targetfile without extension

To keep things compatible, one need to be able to use the target file with extension. Do to do so, one needs to keep the $EXEEXT value to ".exe" on Windows.

In this case, when using the default in Exe extension, that would not add an additional extension. And at the same time, we would like to customize the extension on the build mode.

So I suggest that the Exe extension tab would do the following:

- when computing the actual target file, append temporarily {$EXEEXT} to the field if it is not there
- in the default mode, replace the $EXEEXT value with the global config setting, otherwise replace $EXEEXT by "", ".exe", etc. depending on the selected item in the tab

Then the project would be compatible between ideU and MSEgui, it would make sense to have the field $EXEEXT in ideU (if we have to set it to empty then what's the point of it?), and you can have multiple build modes with different extensions.

**Comment by fredvs** [comment]
> sense to have the field $EXEEXT in ideU

Huh, did you read my previous post?
It does exactly like you explained.

**Comment by circular17** [comment]
Yes I read your post. I am not saying the same thing.

**Comment by fredvs** [comment]
> and with ideU it means targetfile without extension

I agree it could be misunderstood.
I will change the definition where is added `Target file (without extension)`. 

In fact to be compatible with MSEide, the one should always use in ideU something like:
`myfilename${EXEEXT}` (always add the ${EXEEXT}-macro).

**Comment by circular17** [comment]
Yes, either needing ${EXEEXT} all the time or make it optional.

**Comment by fredvs** [comment]
Fixed with https://github.com/fredvs/ideU/commit/73bae4f7e5a119ba72f158c53ad1b081756d307e
