### ISSUE TITLE
Gettext support for localization

### ISSUE THREAD

**Issue by glixx** [mse-org/mseide-msegui#9]
Needs to implement localization of mseide, msei18n, mselang by MO files.
Example is fpgui and uidesigner.
It should be optional by new compiler option.

**Comment by glixx** [comment]
We have many PO files already. So this issue should be prioritized.

**Comment by glixx** [comment]
Main problem is to know what is translatable and what is not. For example all tsringcontainer, buttons, labels are translatable a priori and they will be translated if string was translated by PO file (using msei18n we can exclude some strings).
But some kinds of strings are not translatable a priori. So needs to move translatable of them into tstringcontainer.

**Comment by fredvs** [comment]
I must first compare a  PO file vs cvs from msei18n.
Then I will better understand what is needed.
My first idea was to work from the PO file and translate it to a csv (and reverse).

But maybe you prefer to work on msei18n code and directly produce a PO file (or import it)

**Comment by fredvs** [comment]
> Main problem is to know what is translatable and what is not

So, no chance to be helped by "`String only"`  (because there are some strings hidden)?

**Comment by fredvs** [comment]
OK,  checked the `PO`  and `csv` files.
IMHO, if the `csv` produced by mse18n is OK, it is easy to transfer from `PO` ---> `csv`.

`PO` original word             `csv` original word
   `msgid`                                `value`

`PO` traduction             `csv` original name
   `msgid`                                `msgstr`

**Comment by glixx** [comment]
> But maybe you prefer to work on msei18n code and directly produce a PO file (or import it)

Yes.

Usually developers mark translatable strings by code. FpGUI uses resourcestrings. But MSE goes own way.
For better understanding we cannot translate absolutelly all strings from mfm, they does not have NT information.

So 2 ways:

* translate by gettext only translatable components.
* add TR (translatable) information in mfm for each string

For example we never translate widgetname, but mfm have these strings. So we will not translate this component by getext, but if string of widgetname should be translated we will move this string into tstringcontainer, cause all tstringcontainer are translatable a priori.

I preffer way №1, less work for us.

**Comment by glixx** [comment]
> So, no chance to be helped by "String only" (because there are some strings hidden)?

I'm not sure, needs to test if it will be possible to translate by gettext by VaString only, but not by component name and VaString.

**Comment by glixx** [comment]
> OK, checked the PO and csv files.

It's easy to export into POT file by msei18n tool, changing of code are minimal, we need for transifex only POT files.

**Comment by fredvs** [comment]
> 'm not sure, needs to test if it will be possible to translate by gettext by VaString only,

Sorry fr tat dummy question but what is the magic of `gettext`?
Is it not possible to have the same result with the "classical" `pos()` to localize a word?

**Comment by fredvs** [comment]
`It's easy to export into POT file by msei18n tool, changing of code are minimal, we need for transifex only POT files.`

Huh, how to do to get `POT` files, when I did download files from `transifex`, it only gives `PO` files?

**Comment by glixx** [comment]
> Sorry for tat dummy question but what is the magic of gettext?
Is it not possible to have the same result with the "classical" pos() to localize a word?

I don't know about localization by pos().

> Huh, how to do to get POT files, when I did download files from transifex, it only gives PO files?

They are in languages dir https://github.com/mse-org/mseide-msegui/blob/master/languages/msei18n/msei18n.pot

**Comment by fredvs** [comment]
> Usually developers mark translatable strings by code. FpGUI uses resourcestrings. But MSE goes own way.

IMHO, msei18n is more than a translator tool.
You may also change width, height, color, etc of each component according with each language.

**Comment by fredvs** [comment]
Hello.
I jumped (a little) into `PO` and `POT` files.
I did not see any difference with both syntax, what is the difference?

IMHO using `PO` and `POT` files as input to translate is easy doable.
Even it can be automatically detect if the format used for data is `csv` from mse or `po`.

But to use the `PO` or `POT` file as `trd`, it will be much more difficult because the `PO` does not have all the info needed.

**Comment by glixx** [comment]
> I did not see any difference with both syntax, what is the difference?

POT file has template for header, but PO files have header with according language.
POT file has msgstr "", but PO file has msgstr "translated_string".

> Even it can automatically detect if the format used for data is csv from mse or po.

There are 3 formats of PO files. So autodetect is not easy to implement.

The first of all try to implement export into POT file based on CSV export alghorith (POT file without msgctxt, but in this case all msgstr must be unique, there is POT file in sources what should be done.). We do not need TRD for POT/PO files generation.

**Comment by glixx** [comment]
I commited in languages/testing POT and PO files with msgctxt. So needs to implement export into both formats, but do not forget about 3rd format - mix msgctxt and nothing.
So at the moment we have 2 formats of POT/PO files.
If to go by Martin way, then he created all strings context dependenced. Qt goes by context way.
Import from/export into msei18n is not problem. Even lang library compilation is not problem. But popential problem is using MO files because if to use msgid needs to send msgctxt to gettext function.
So what way is the best only time knows.

**Comment by glixx** [comment]
So it's important to try localization by gettext MO files. And if context is ok, then to switch on context only.

**Comment by fredvs** [comment]
> And if context is ok, then to switch on context only.

It will be much more complicated.

**Comment by glixx** [comment]
We have no developers and skills to support context. So we go by way without context https://github.com/mse-org/mseide-msegui/issues/33

**Comment by fredvs** [comment]
https://github.com/mse-org/mseide-msegui/issues/7#issuecomment-477594191

**Comment by glixx** [comment]
Fpc can read PO files instead of MO. It means mseide can be localized using current sources and nothing more. And this way will be cross platform.

**Comment by fredvs** [comment]
Wow + congratulation.
